### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by ahoehma** [MovingBlocks/Terasology#1162]
Just download and start ...

java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:192)
	at org.terasology.engine.SimpleUri.<init>(SimpleUri.java:67)
	at org.terasology.engine.SimpleUri.<init>(SimpleUri.java:57)
	at org.terasology.logic.behavior.asset.NodesClassLibrary.scan(NodesClassLibrary.java:42)
	at org.terasology.engine.bootstrap.EntitySystemBuilder.build(EntitySystemBuilder.java:123)
	at org.terasology.engine.modes.StateMainMenu.init(StateMainMenu.java:74)
	at org.terasology.engine.TerasologyEngine.switchState(TerasologyEngine.java:468)
	at org.terasology.engine.TerasologyEngine.changeState(TerasologyEngine.java:298)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:242)
	at org.terasology.engine.Terasology.main(Terasology.java:90)

**Comment by Cervator** [comment]
@ahoehma - fixed now! Should be able to run the game in any named dir now :-)

http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip
