### ISSUE TITLE
NPE #2

### ISSUE THREAD

**Issue by ahoehma** [MovingBlocks/Terasology#1163]
Just download, install in path without spaces ... start, new game, "modules ..." ... bähm:

java.lang.NullPointerException
	at org.terasology.rendering.nui.layers.mainMenu.SelectModulesScreen.setSelectedVersions(SelectModulesScreen.java:290)
	at org.terasology.rendering.nui.layers.mainMenu.SelectModulesScreen.initialise(SelectModulesScreen.java:85)
	at org.terasology.rendering.nui.CoreScreenLayer.onOpened(CoreScreenLayer.java:72)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.prepare(NUIManagerInternal.java:506)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:238)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:202)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:191)
	at org.terasology.rendering.nui.layers.mainMenu.CreateGameScreen$9.onActivated(CreateGameScreen.java:217)
	at org.terasology.rendering.nui.widgets.UIButton.activate(UIButton.java:138)
	at org.terasology.rendering.nui.widgets.UIButton.access$100(UIButton.java:40)
	at org.terasology.rendering.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:81)
	at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:226)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:425)
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:497)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:278)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:257)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:166)
	at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:392)
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:247)
	at org.terasology.input.InputSystem.update(InputSystem.java:204)
	at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:134)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:65)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:445)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:246)
	at org.terasology.engine.Terasology.main(Terasology.java:90)

**Comment by Cervator** [comment]
Closing this as likely fixed / non-issue by now
