### ISSUE TITLE
Unit tests fail when Core module is present

### ISSUE THREAD

**Issue by msteiger** [MovingBlocks/Terasology#1169]
The junit tests in modules fail "sometimes" with an error message similar to this one:
```
12:12:17.288 [main] ERROR org.terasology.Environment - Error
java.lang.NullPointerException: null
    at org.terasology.module.ModuleEnvironment.buildModuleMap(ModuleEnvironment.java:109) ~[gestalt-module-1.2.2.jar:na]
    at org.terasology.module.ModuleEnvironment.<init>(ModuleEnvironment.java:85) ~[gestalt-module-1.2.2.jar:na]
    at org.terasology.module.ModuleEnvironment.<init>(ModuleEnvironment.java:73) ~[gestalt-module-1.2.2.jar:na]
    at org.terasology.engine.module.ModuleManager.loadEnvironment(ModuleManager.java:165) ~[classes/:na]
    at org.terasology.testUtil.ModuleManagerFactory.create(ModuleManagerFactory.java:41) ~[testClasses/:na]
    at org.terasology.HeadlessEnvironment.setupModuleManager(HeadlessEnvironment.java:195) [testClasses/:na]
    at org.terasology.Environment.reset(Environment.java:57) ~[testClasses/:na]
    at org.terasology.Environment.<init>(Environment.java:44) ~[testClasses/:na]
    at org.terasology.HeadlessEnvironment.<init>(HeadlessEnvironment.java:89) [testClasses/:na]
```

The reason seems to be simple: `registry.getLatestModuleVersion(new Name("unittest"))` cannot resolve "unittest" and adds `null` to the set of modules in ModuleManagerFactory which causes gestalt-module to crash with an NPE.

This seems to be caused by the fact that `getResourceAsStream("/module.txt"))` does not load the unittest info, but something else. In my case it was "Core" (PathFinding depends on it). Removing and adding the project dependency solved the issue, apparently because the engine-tests folder is then searched before "Core". 

Similar to #1168, merging engine-tests into engine or renaming the module.txt to a unique name could solve the problem permanently.

**Comment by Cervator** [comment]
@msteiger - do you think this can be closed with your recent work in this area?

**Comment by msteiger** [comment]
Yup - thanks!
