### ISSUE TITLE
Crash in network EntityAwareWorldProvider.updateBlockEntityComponents(EntityAwareWorldProvider.java:240)

### ISSUE THREAD

**Issue by Urfoex** [MovingBlocks/Terasology#1206]
```
[main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception
java.lang.NullPointerException: null
        at org.terasology.world.internal.EntityAwareWorldProvider.updateBlockEntityComponents(EntityAwareWorldProvider.java:240) ~[engine-0.1.0-SNAPSHOT+1122.jar:1122, develop, 2014-09-20_02-42-08, pre-alpha]
        at org.terasology.world.internal.EntityAwareWorldProvider.updateBlockEntity(EntityAwareWorldProvider.java:156) ~[engine-0.1.0-SNAPSHOT+1122.jar:1122, develop, 2014-09-20_02-42-08, pre-alpha]
        at org.terasology.world.internal.EntityAwareWorldProvider.setBlock(EntityAwareWorldProvider.java:127) ~[engine-0.1.0-SNAPSHOT+1122.jar:1122, develop, 2014-09-20_02-42-08, pre-alpha]
        at org.terasology.world.internal.WorldProviderWrapper.setBlock(WorldProviderWrapper.java:52) ~[engine-0.1.0-SNAPSHOT+1122.jar:1122, develop, 2014-09-20_02-42-08, pre-alpha]
        at org.terasology.network.internal.ServerImpl.processBlockChanges(ServerImpl.java:282) ~[engine-0.1.0-SNAPSHOT+1122.jar:1122, develop, 2014-09-20_02-42-08, pre-alpha]
        at org.terasology.network.internal.ServerImpl.processMessages(ServerImpl.java:248) ~[engine-0.1.0-SNAPSHOT+1122.jar:1122, develop, 2014-09-20_02-42-08, pre-alpha]
        at org.terasology.network.internal.ServerImpl.update(ServerImpl.java:168) ~[engine-0.1.0-SNAPSHOT+1122.jar:1122, develop, 2014-09-20_02-42-08, pre-alpha]
        at org.terasology.network.internal.NetworkSystemImpl.update(NetworkSystemImpl.java:279) ~[engine-0.1.0-SNAPSHOT+1122.jar:1122, develop, 2014-09-20_02-42-08, pre-alpha]
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421) ~[engine-0.1.0-SNAPSHOT+1122.jar:1122, origin/develop, 2014-09-20_02-42-08]
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:246) ~[engine-0.1.0-SNAPSHOT+1122.jar:1122, origin/develop, 2014-09-20_02-42-08]
        at org.terasology.engine.Terasology.main(Terasology.java:90) [Terasology.jar:1122, origin/develop, 2014-09-20_02-42-08]
```

**Comment by piter146** [comment]
hi ive got the same problem, anyone knows please how to fix it?

**Comment by msteiger** [comment]
Can you please provide some more details? Java version, game version, log file, etc? The line number of the crash would also be important. Thanks!

**Comment by Cervator** [comment]
Hi @piter146 - also please put in a new issue so we can treat it as its own unique report until we're sure if they relate? :-)

https://github.com/MovingBlocks/Terasology/issues/new

The game log is really important and should be in your user home directory. On Windows7 for instance that'll be at C:\Users\[username]\Saved Games\Terasology\logs
