### ISSUE TITLE
An Exception throws when trying to launch with special characters in path

### ISSUE THREAD

**Issue by Rawieo** [MovingBlocks/Terasology#1310]
```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at org.terasology.engine.SimpleUri.<init>(SimpleUri.java:67)
	at org.terasology.engine.SimpleUri.<init>(SimpleUri.java:57)
	at org.terasology.logic.behavior.asset.NodesClassLibrary.scan(NodesClassLibrary.java:42)
	at org.terasology.engine.bootstrap.EntitySystemBuilder.build(EntitySystemBuilder.java:123)
	at org.terasology.engine.modes.StateMainMenu.init(StateMainMenu.java:74)
	at org.terasology.engine.TerasologyEngine.switchState(TerasologyEngine.java:505)
	at org.terasology.engine.TerasologyEngine.changeState(TerasologyEngine.java:330)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:264)
	at org.terasology.engine.Terasology.main(Terasology.java:115)

**Comment by Cervator** [comment]
Bump - still an issue, had a user report on IRC

```
18:33:25.321 [main] INFO  o.t.module.sandbox.ModuleClassLoader - Module path: C:\Users\Elías\AppData\Roaming\Terasology\STABLE\TerasologyStable\46\modules\Core-0.46.0-SNAPSHOT.jar
18:33:25.322 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
18:33:25.336 [main] INFO  o.terasology.engine.TerasologyEngine - Initialization completed in 1,17sec.
18:33:25.356 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210) ~[guava-18.0.jar:na]
        at org.terasology.engine.SimpleUri.<init>(SimpleUri.java:67) ~[engine-0.46.0-SNAPSHOT.jar:46, origin/master, 2014-12-30_21-39-28]
        at org.terasology.engine.SimpleUri.<init>(SimpleUri.java:57) ~[engine-0.46.0-SNAPSHOT.jar:46, origin/master, 2014-12-30_21-39-28]
        at org.terasology.logic.behavior.asset.NodesClassLibrary.scan(NodesClassLibrary.java:42) ~[engine-0.46.0-SNAPSHOT.jar:46, master, 2014-12-30_21-39-28, pre-alpha]
        at org.terasology.engine.bootstrap.EntitySystemBuilder.build(EntitySystemBuilder.java:123) ~[engine-0.46.0-SNAPSHOT.jar:46, master, 2014-12-30_21-39-28, pre-alpha]
        at org.terasology.engine.modes.StateMainMenu.init(StateMainMenu.java:74) ~[engine-0.46.0-SNAPSHOT.jar:46, master, 2014-12-30_21-39-28, pre-alpha]
        at org.terasology.engine.TerasologyEngine.switchState(TerasologyEngine.java:543) ~[engine-0.46.0-SNAPSHOT.jar:46, origin/master, 2014-12-30_21-39-28]
        at org.terasology.engine.TerasologyEngine.changeState(TerasologyEngine.java:527) ~[engine-0.46.0-SNAPSHOT.jar:46, origin/master, 2014-12-30_21-39-28]
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:352) ~[engine-0.46.0-SNAPSHOT.jar:46, origin/master, 2014-12-30_21-39-28]
        at org.terasology.engine.Terasology.main(Terasology.java:117) [Terasology.jar:46, origin/master, 2014-12-30_21-39-28]
18:33:25.356 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

The special í character. This is still probably an easy fix for us to make sometime soon, anybody? :D

**Comment by immortius** [comment]
I'll take this - it may well be an issue in gestalt-module.

**Comment by Cervator** [comment]
@Rawieo - this should be fixed in the latest develop release now. Feel free to retest / go back to using your user directory :-)

http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip
