### ISSUE TITLE
Fatal Error!

### ISSUE THREAD

**Issue by Orangian** [MovingBlocks/Terasology#1316]
I was going to use the infin blocks thing then I pressed b and I got this java.lang.NullPointerException
	at org.terasology.world.block.internal.BlockPrefabManager.updateBlock(BlockPrefabManager.java:65)
	at org.terasology.world.block.internal.BlockPrefabManager.onBlockFamilyRegistered(BlockPrefabManager.java:47)
	at org.terasology.world.block.internal.BlockManagerImpl.registerFamily(BlockManagerImpl.java:236)
	at org.terasology.world.block.internal.BlockManagerImpl.getBlockFamily(BlockManagerImpl.java:370)
	at org.terasology.blockPicker.ui.BlockPickerScreen.refreshAllItemEntities(BlockPickerScreen.java:150)
	at org.terasology.blockPicker.ui.BlockPickerScreen.initialise(BlockPickerScreen.java:56)
	at org.terasology.rendering.nui.CoreScreenLayer.onOpened(CoreScreenLayer.java:72)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.prepare(NUIManagerInternal.java:511)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:243)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:207)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:196)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:225)
	at org.terasology.blockPicker.systems.BlockPickerClientSystem.onOpenContainer(BlockPickerClientSystem.java:37)
	at org.terasology.blockPicker.systems.BlockPickerClientSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:497)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:278)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:257)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:166)
	at org.terasology.input.internal.BindableButtonImpl.updateBindState(BindableButtonImpl.java:178)
	at org.terasology.input.InputSystem.processKeyboardInput(InputSystem.java:319)
	at org.terasology.input.InputSystem.update(InputSystem.java:205)
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:168)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:65)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:482)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:268)
	at org.terasology.engine.Terasology.main(Terasology.java:115)
 Here is the log file link https://www.dropbox.com/s/vomdxe0b7md27y0/Error.txt?dl=0 Im using the stable version on 10-26-2014

**Comment by Cervator** [comment]
Closing this - we just removed the "Enable all" button so it should be harder to encounter this. Also been a while so some of the other issues are likely gone too (or invalid after a lot of related changes have happened - could be broken in new and interesting ways!)
