### ISSUE TITLE
Likely access issue on using config/preview on world with certain dependencies

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1373]
This was reported by @OvermindDL1 over at https://github.com/Terasology/ClimateConditions/issues/1 but really looks like an engine issue. I think what happens is that a world with certain dependency structure trips on our module sandboxing from a spot where it doesn't have a privileged path to what preview/config needs.

I can reproduce with latest develop and the Throughout the Ages II template active. Probably a relatively easy fix with a privileged block in the right place. Log snippet:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/terasology/climateConditions/ClimateConditionsSystem
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
        at java.lang.Class.getMethod0(Class.java:2856)
        at java.lang.Class.getMethod0(Class.java:2865)
        at java.lang.Class.getMethod(Class.java:1668)
        at org.terasology.utilities.ReflectionUtil.findMethod(ReflectionUtil.java:109)
        at org.terasology.utilities.ReflectionUtil.findGetter(ReflectionUtil.java:81)
        at org.terasology.reflection.metadata.FieldMetadata.determineType(FieldMetadata.java:70)
        at org.terasology.reflection.metadata.FieldMetadata.<init>(FieldMetadata.java:57)
        at org.terasology.reflection.metadata.DefaultClassMetadata.createField(DefaultClassMetadata.java:49)
        at org.terasology.reflection.metadata.ClassMetadata.addFields(ClassMetadata.java:106)
        at org.terasology.reflection.metadata.ClassMetadata.<init>(ClassMetadata.java:85)
        at org.terasology.reflection.metadata.DefaultClassMetadata.<init>(DefaultClassMetadata.java:44)
        at org.terasology.reflection.metadata.DefaultClassLibrary.createMetadata(DefaultClassLibrary.java:39)
        at org.terasology.reflection.metadata.AbstractClassLibrary.register(AbstractClassLibrary.java:65)
        at org.terasology.world.generator.plugin.DefaultWorldGeneratorPluginLibrary.<init>(DefaultWorldGeneratorPluginLibrary.java:41)
        at org.terasology.world.generator.plugin.TempWorldGeneratorPluginLibrary.<init>(TempWorldGeneratorPluginLibrary.java:40)
        at org.terasology.rendering.nui.layers.mainMenu.ConfigWorldGenScreen.onOpened(ConfigWorldGenScreen.java:77)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.prepare(NUIManagerInternal.java:511)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:243)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:207)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:196)
        at org.terasology.rendering.nui.layers.mainMenu.CreateGameScreen$11.onActivated(CreateGameScreen.java:306)
        at org.terasology.rendering.nui.widgets.UIButton.activate(UIButton.java:138)
        at org.terasology.rendering.nui.widgets.UIButton.access$100(UIButton.java:40)
        at org.terasology.rendering.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:81)
        at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:226)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:430)
        at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
        at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:497)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:278)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:257)
        at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:166)
        at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:393)
        at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:248)
        at org.terasology.input.InputSystem.update(InputSystem.java:204)
        at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:134)
        at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:65)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:482)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:268)
        at org.terasology.engine.Terasology.main(Terasology.java:115)
Caused by: java.lang.ClassNotFoundException: Failed to find or load class org.terasology.climateConditions.ClimateConditionsSystem
        at org.terasology.module.sandbox.ModuleClassLoader.findClass(ModuleClassLoader.java:126)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at org.terasology.module.sandbox.ModuleClassLoader.loadClass(ModuleClassLoader.java:94)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 41 more
Caused by: javassist.NotFoundException: org.terasology.climateConditions.ClimateConditionsSystem
        at javassist.ClassPool.get(ClassPool.java:450)
        at org.terasology.module.sandbox.ModuleClassLoader$1.run(ModuleClassLoader.java:113)
        at org.terasology.module.sandbox.ModuleClassLoader$1.run(ModuleClassLoader.java:110)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.terasology.module.sandbox.ModuleClassLoader.findClass(ModuleClassLoader.java:110)
        ... 44 more
```

**Comment by Cervator** [comment]
Closing from age, changes made since, and TTA 2 not even being a module anymore. Preview issues are covered well in other issues as well.
