### ISSUE TITLE
Crash on kicking a user

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1375]
On kicking a user in a multiplayer situation (just two normal clients will do) the server crashes.

```java
23:33:38.891 [main] INFO  o.t.l.console.server.ServerCommands - Kicking user 2
23:33:38.891 [main] INFO  o.t.l.console.internal.ConsoleImpl - [CONSOLE] User kick triggered for '2'
23:33:38.891 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: 2
23:33:38.907 [main] INFO  o.t.l.console.internal.ConsoleImpl - [NOTIFICATION] Player "2" has left the game
23:33:38.940 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: 2
23:33:38.955 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.persistence.internal.StorageManagerInternal.deactivatePlayer(StorageManagerInternal.java:184) ~[classes/:na]
	at org.terasology.network.internal.NetworkSystemImpl.processRemovedClient(NetworkSystemImpl.java:724) ~[classes/:na]
	at org.terasology.network.internal.NetworkSystemImpl.processPendingDisconnects(NetworkSystemImpl.java:290) ~[classes/:na]
	at org.terasology.network.internal.NetworkSystemImpl.update(NetworkSystemImpl.java:266) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:458) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:268) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:115) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_55]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_55]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_55]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_55]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:na]
```

**Comment by Cervator** [comment]
Just as a note I confirmed this is still an active issue while testing #1489 (which fixes multiplayer commands from recent changes):

```
16:05:15.810 [main] INFO  o.t.l.c.commands.ServerCommands - Kicking user 1st
16:05:15.811 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: 1st
16:05:15.832 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: 1st
16:05:15.848 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.persistence.internal.ReadWriteStorageManager.deactivatePlayer(ReadWriteStorageManager.java:163) ~[classes/:na]
	at org.terasology.network.internal.NetworkSystemImpl.processRemovedClient(NetworkSystemImpl.java:730) ~[classes/:na]
	at org.terasology.network.internal.NetworkSystemImpl.processPendingDisconnects(NetworkSystemImpl.java:296) ~[classes/:na]
	at org.terasology.network.internal.NetworkSystemImpl.update(NetworkSystemImpl.java:272) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:432) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:371) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:122) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_55]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_55]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_55]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_55]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:na]
16:05:15.849 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
16:05:15.857 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
16:05:15.894 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
16:05:15.916 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: 2nd
16:05:15.922 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
16:05:17.224 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
16:05:17.224 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
```

Pinging @flo since it looks like it might be storage related and I know you're working on some more auto save fun :-)

**Comment by Cervator** [comment]
Heyo @Limeth - up for looking at this sometime? :-)
