### ISSUE TITLE
Commands requiring "op" from unprivileged client on headless server causes crash

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1516]
For "hspeed" anyway - tested via headless server + connecting with a client. Simply executing "hspeed" in the console crashed the game:

```
22:09:36.589 [main] INFO  o.t.logic.console.ConsoleImpl - [CONSOLE] Welcome to the wonderful world of Terasology!

Type 'help' to see a list with available commands or 'help "<commandName>"' for command details.
Text parameters should be in quotes, no commas needed between multiple parameters.
You can use auto-completion by typing a partial command then hitting 'tab' - examples:
'gh' + 'tab' = 'ghost'
'lS' + 'tab' = 'listShapes' (camel casing abbreviated commands)

22:09:39.126 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.reflection.metadata.ClassMetadata.newInstance(ClassMetadata.java:165) ~[classes/:na]
	at org.terasology.persistence.serializers.EventSerializer.deserialize(EventSerializer.java:89) ~[classes/:na]
	at org.terasology.network.internal.ServerImpl.processEvent(ServerImpl.java:222) ~[classes/:na]
	at org.terasology.network.internal.ServerImpl.processMessages(ServerImpl.java:262) ~[classes/:na]
	at org.terasology.network.internal.ServerImpl.update(ServerImpl.java:172) ~[classes/:na]
	at org.terasology.network.internal.NetworkSystemImpl.update(NetworkSystemImpl.java:307) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:433) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:372) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:137) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_55]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_55]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_55]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_55]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:na]
22:09:39.126 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
22:09:39.168 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
22:09:39.191 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
```

Works fine if you do usePermissionKey first to gain op power

@Limeth - is this something you could please look at? Maybe together with the other couple command fixes you've got hiding somewhere :-)

@immortius - is there any way we can improve the logging in cases like this? Often we seem to end up with these sort of generic NPEs when execution is floating around in the innards of the ES / reflection stuff, where the exact state is probably hidden in variables somewhere close by.

**Comment by Cervator** [comment]
Closing as complete
