### ISSUE TITLE
Crash on "preview" or "config" buttons on create world screen, TTA active

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1524]
If you select Throughout the Ages then use either the "Config" or "Preview" button the game crashes:

```
18:23:27.882 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
org.reflections.ReflectionsException: could not get type for name org.terasology.was.generator.plant.forest.tree.BroomForestSpawnDefinition
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:378) ~[reflections-0.9.9-RC1.jar:na]
	at org.reflections.ReflectionUtils.forNames(ReflectionUtils.java:387) ~[reflections-0.9.9-RC1.jar:na]
	at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:351) ~[reflections-0.9.9-RC1.jar:na]
	at org.terasology.module.ModuleEnvironment.getTypesAnnotatedWith(ModuleEnvironment.java:279) ~[gestalt-module-2.1.0.jar:na]
	at org.terasology.world.generator.plugin.DefaultWorldGeneratorPluginLibrary.<init>(DefaultWorldGeneratorPluginLibrary.java:39) ~[classes/:na]
	at org.terasology.world.generator.plugin.TempWorldGeneratorPluginLibrary.<init>(TempWorldGeneratorPluginLibrary.java:40) ~[classes/:na]
	at org.terasology.rendering.nui.layers.mainMenu.ConfigWorldGenScreen.onOpened(ConfigWorldGenScreen.java:68) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.prepare(NUIManagerInternal.java:639) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:285) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:249) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:236) ~[classes/:na]
	at org.terasology.rendering.nui.layers.mainMenu.CreateGameScreen$11.onActivated(CreateGameScreen.java:309) ~[classes/:na]
	at org.terasology.rendering.nui.widgets.UIButton.activate(UIButton.java:138) ~[classes/:na]
	at org.terasology.rendering.nui.widgets.UIButton.access$100(UIButton.java:40) ~[classes/:na]
	at org.terasology.rendering.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:81) ~[classes/:na]
	at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:227) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:558) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source) ~[reflectasm-1.09.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:497) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:278) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:257) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:168) ~[classes/:na]
	at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:393) ~[classes/:na]
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:248) ~[classes/:na]
	at org.terasology.input.InputSystem.update(InputSystem.java:204) ~[classes/:na]
	at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:139) ~[classes/:na]
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:65) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:458) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:372) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:137) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_55]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_55]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_55]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_55]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:na]
18:23:27.883 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

We had a similar issue before and hardened those options to deal with modules not fully compatible for whatever reason with preview/config. We probably need to harden it again with the scenario above in mind, and maybe fix something in a TTA module too.

**Comment by Cervator** [comment]
Still a thing - updated log from Halamix: http://pastebin.com/uW2UjZqu

**Comment by msteiger** [comment]
The problem here is that the `TempWorldGeneratorPluginLibrary` only loads direct module dependencies. As a result, classes from indirect deps. cannot be loaded. A fix will be PRed soon.
