### ISSUE TITLE
Crash able to escape CR / normal log file (Error vs. Exception)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1557]
I've been debugging what is *likely* a quirk in Jenkins/Artifactory I suspect relates to build order, snapshots, and dependency caching after the recent Math change, as something is still out of date. Still working on that, but the symptom is the Omega zip crashes on right clicking two logs with the crude hammer-axe in TTA. 

Example Omega zip 67 does it: http://jenkins.terasology.org/job/DistroOmega/67/artifact/distros/omega/build/distributions/TerasologyOmega.zip

* If running from source or locally build binaries it doesn't happen (thus blaming Jenkins/Artifactory). 
* If running via exe the game window just disappears and there's nothing at the end of the game log file (which is the problem intended for this issue)
* If running via jar you crash with the following error:

```
22:27:34.900 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
22:27:51.056 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[WoodAndStone:MapleLog]
22:27:51.057 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block WoodAndStone:MapleLog with id 1096
Exception in thread "main" java.lang.NoSuchMethodError: org.terasology.math.Region3i.center()Ljavax/vecmath/Vector3f;
        at org.terasology.multiBlock.recipe.UniformMultiBlockFormItemRecipe.processActivation(UniformMultiBlockFormItemR
ecipe.java:121)
        at org.terasology.multiBlock.MultiBlockFormingSystem.formMultiBlockWithItem(MultiBlockFormingSystem.java:40)
        at org.terasology.multiBlock.MultiBlockFormingSystemMethodAccess.invoke(Unknown Source)
        at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.ja
va:497)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:278)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:257)
        at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:168)
        at org.terasology.logic.characters.CharacterSystem.onActivationRequest(CharacterSystem.java:139)
        at org.terasology.logic.characters.CharacterSystemMethodAccess.invoke(Unknown Source)
        at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.ja
va:497)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:268)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:259)
        at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:168)
        at org.terasology.logic.players.LocalPlayer.activateTargetOrOwnedEntity(LocalPlayer.java:184)
        at org.terasology.logic.players.LocalPlayer.activateOwnedEntityAsClient(LocalPlayer.java:149)
        at org.terasology.logic.players.LocalPlayerSystem.onUseItemButton(LocalPlayerSystem.java:326)
        at org.terasology.logic.players.LocalPlayerSystemMethodAccess.invoke(Unknown Source)
        at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.ja
va:497)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:278)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:257)
        at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:168)
        at org.terasology.input.internal.BindableButtonImpl.updateBindState(BindableButtonImpl.java:177)
        at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:252)
        at org.terasology.input.InputSystem.update(InputSystem.java:204)
        at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:182)
        at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:65)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:458)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:372)
        at org.terasology.engine.Terasology.main(Terasology.java:139)
```

I'm trying to figure out why the actual crash happens, but I'm more curious why this escapes the crash reporter and doesn't log the above error if running from .exe. I guess it is because it is an Error instead of an Exception? `java.lang.NoSuchMethodError`

Usually errors are non-recoverable and this is no exception (hah). However, this seems like the sort of "soft" Error we could correctly catch via CR and present to the user. Unless we're in some state at this point where we can't get to what we need for the CR.

Thoughts?

**Comment by Cervator** [comment]
Sorted out the original cause. Quite a ways back I tested the new release approach for modules, and the only module I did it with was MultiBlock. As such there was a non-snapshot release jar in Artifactory getting preferred over the snapshot we kept building.

Latest Omega zip now works. Yay!

**Comment by msteiger** [comment]
I think that you're right. Should be easy to fix though. I will have a look.
