### ISSUE TITLE
Crash with FloraRasterizer after noise change? (#1573)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1578]
At least for me if I try any world with the basic Flora active (Perlin, flat, heightmap) all the chunk generators die:

```
23:45:42.586 [Chunk-Generator-7] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-7
java.lang.IndexOutOfBoundsException: index (-5) must not be negative
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:310) ~[guava-18.0.jar:na]
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:292) ~[guava-18.0.jar:na]
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:65) ~[guava-18.0.jar:na]
	at org.terasology.core.world.generator.rasterizers.FloraRasterizer.generateChunk(FloraRasterizer.java:82) ~[na:na]
	at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:62) ~[classes/:na]
	at org.terasology.world.generation.BaseFacetedWorldGenerator.createChunk(BaseFacetedWorldGenerator.java:67) ~[classes/:na]
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$4.run(LocalChunkProvider.java:632) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_55]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_55]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]
```

Code snippet:

```java
                FloraType type = entries.get(pos);
                List<Block> list = flora.get(type);
                int blockIdx = noise.intNoise(pos.x, pos.y, pos.z) % list.size();
                Block block = list.get(blockIdx);
```

`blockIdx` can end up with a negative value, maybe from the intNoise returning invalid values with some combinations / seeds?

Other worlds work fine, like the Pathfinder test world (no flowers). @msteiger - ping! :-)

Edit: I tried with both Java 7 and Java 8, just in case, I remember something came up (on IRC sometime?). But maybe that was PolyWorld related instead.

**Comment by Cervator** [comment]
Fixed by #1584
