### ISSUE TITLE
Logging an issue is failing due to security settings

### ISSUE THREAD

**Issue by MarcinSc** [MovingBlocks/Terasology#1724]
I just got a following stack trace, which makes it impossible to figure out what I'm doing wrong, because SecurityPermissions are preventing any logging:

java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.reflect")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at org.terasology.module.sandbox.ModuleSecurityManager.checkPermission(ModuleSecurityManager.java:83)
	at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:305)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at ch.qos.logback.classic.spi.PackagingDataCalculator.loadClass(PackagingDataCalculator.java:207)
	at ch.qos.logback.classic.spi.PackagingDataCalculator.bestEffortLoadClass(PackagingDataCalculator.java:232)
	at ch.qos.logback.classic.spi.PackagingDataCalculator.computeBySTEP(PackagingDataCalculator.java:138)
	at ch.qos.logback.classic.spi.PackagingDataCalculator.populateFrames(PackagingDataCalculator.java:101)
	at ch.qos.logback.classic.spi.PackagingDataCalculator.calculate(PackagingDataCalculator.java:57)
	at ch.qos.logback.classic.spi.ThrowableProxy.calculatePackagingData(ThrowableProxy.java:147)
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:124)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:440)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
	at ch.qos.logback.classic.Logger.error(Logger.java:559)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:513)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:358)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.saveComponent(PojoEntityManager.java:651)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.saveComponent(BaseEntityRef.java:135)

**Comment by immortius** [comment]
Try with  ```moduleSecurityManager.getBasePermissionSet().grantPermission("ch.qos.logback.classic", new RuntimePermission("accessClassInPackage.sun.reflect"));``` added in ModuleManagerImpl.

**Comment by Cervator** [comment]
Also, wouldn't this potentially be an ideal candidate for the warning only mode introduced in Gestalt (https://github.com/MovingBlocks/gestalt/pull/13) but not yet enabled in the engine? At least I think we just need to increase the Gestalt version and hook it up.

**Comment by msteiger** [comment]
I wonder why this happens in this particular case, but not in all the other logging events. 

It might be related to the error type `ERROR`, which is probably not used during initialization and thus loaded only in-game, which is sandboxed.

How about adding `org.slf4j.Logger` and `org.slf4j.LoggerFactory` to the set of permissions instead?

**Comment by immortius** [comment]
They're not in the stack trace, so won't have any effect.
