### ISSUE TITLE
Follow-up to #1740 - various issues and broken modules

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1762]
With the big #1740 merged and the Omega lineup of modules tweaked there are some smaller things we get to start working on now, yay! :sparkles: Considering the magnitude of the changes the game is looking pretty good :-) No trouble in multiplayer that I noted, for instance.

*Notes*

* Post-merge engine build: http://jenkins.terasology.org/job/Terasology/1433/
* Post-merge Omega 166 zip: http://jenkins.terasology.org/job/DistroOmega/166/artifact/distros/omega/build/distributions/TerasologyOmega.zip (broken - item below in the bugs list)
* Should we reintroduce a `BlockManager.AIR` block of some sort or is that bad? I added a @In blockManager a couple places and did a getBlock to compare with air in a few more modules
* Need @synopia for some Pathfinding review, although I think all unit tests and working locally, just broken in Jenkins from environment issues
* Need @MarcinSc for some computer review - we fixed up some of the modules, are the fixes acceptable? Two more remain broken in part from the engine PR that was delayed due to the big merge (BlockFamily / side stuff). Marcin please let us know what else on the engine side you run into that might need fixing :-)
* Need @small-jeeper for Rails - it is pretty broken, but could be put on vacation from the lineup (no integration with anything else)
* I did version increments in lots of places when adding -SNAPSHOT but just patch level. Probably minor would be more right at least in some places, but for the sake of expediency and all that + not formally in release management land yet. I did have a bit of a related breakthrough, but no time tonight to pursue it further
* @flo I increased the minVersion in a few places where it seemed unlikely an older version would've been appropriate, making maxVersion no longer needed. We'll probably need this more seriously later, right now increasing min seems a non-issue

*Broken modules*
- [x] Signalling
- [x] ComputerMonitors
- [ ] ~~Rails~~ - deactivating from primary lineup

*Bugs*
- [ ] ~~Attempting to fill a wooden bucket in TTA causes index out of bounds crash (probably in trying to retrieve/customize the updated bucket icon?) - we've seen that one before. Didn't grab a log, but easy to replicate with `giveItem woodenbucket` in the console + go scoop some water~~ - split out
- [ ] ~~Stall on startup in JoshariasSurvival, stack thrown during char spawn (1). Didn't happen a second time though. Later on leaving a reloaded game got another stack but no crash/stall (2)~~ - not seeing again, hoping fixed or non-issue
- [ ] ~~Crash on world gen in L&S over seed not set yet - yet clearly some seed is set based on how LASMapGenerator looks, huh (3)~~ - split out
- [ ] ~~Odd crash starting a game with some misc modules enabled (4) - module/asset scanning? Hit it again later on trying to join a headless server. I wonder if this might relate to having crashed instances of the game idling in the background - if so it may be a non-issue (or maybe we could catch it better?)~~ - not seeing again, hoping fixed or non-issue
- [ ] ~~Unrelated probably split out: If you kill a wandering deer its highlighted target square never un-highlights (Pathfinding or WildAnimals fix?) - just noticed and had it in my notes~~ - ignoring for now, probably will get reworked anyway
- [ ] ~~Cities worldgen doesn't register: `o.t.w.g.i.WorldGeneratorManager - class org.terasology.cities.CityWorldGenerator marked to be registered as a World Generator, but is not a subclass of WorldGenerator or lacks the correct constructor` - @msteiger ?~~ - split out
- [ ] ~~Weird sandbox denial on game startup: `o.t.module.sandbox.ModuleClassLoader - Denied access to class (not allowed with this module's permissions): org.terasology.logic.spawner.Spawner `(related to new player spawning?)~~ - ignoring for now since it is logged, doesn't seem to cause trouble, and will likely be addressed or disappear in the future on its own
- [x] Crash on startup from binary download (Omega 166) - permission/asset issue? @immortius ? Same with exe and straight jar (5)
- [x] It can take a nice chunk of time to scan for assets (at least from source) - might be ways to optimize further or perhaps just update the status message ("Scanning for assets - may take a little while" ?) if we want to live with it for a while, it does work eventually :-)

(1)

```
21:13:38.091 [Chunk-Generator-5] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:GreenLeaf with id 59
21:13:38.155 [Chunk-Generator-6] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:OakTrunk]
21:13:38.155 [Chunk-Generator-6] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:OakTrunk with id 60
21:13:38.397 [Chunk-Generator-4] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Generator-4
java.lang.NullPointerException: null
	at org.terasology.world.block.Block.setCollision(Block.java:597) ~[classes/:na]
	at org.terasology.world.block.internal.BlockBuilder.constructCustomBlock(BlockBuilder.java:135) ~[classes/:na]
	at org.terasology.world.block.internal.BlockBuilder.constructTransformedBlock(BlockBuilder.java:116) ~[classes/:na]
	at org.terasology.world.block.family.HorizontalBlockFamilyFactory.createBlockFamily(HorizontalBlockFamilyFactory.java:53) ~[classes/:na]
	at org.terasology.world.block.loader.BlockFamilyDefinition.createFamily(BlockFamilyDefinition.java:67) ~[classes/:na]
	at org.terasology.world.block.internal.BlockManagerImpl.loadFamily(BlockManagerImpl.java:271) ~[classes/:na]
	at org.terasology.world.block.internal.BlockManagerImpl.getBlockFamily(BlockManagerImpl.java:239) ~[classes/:na]
	at org.terasology.world.block.internal.BlockManagerImpl.getBlock(BlockManagerImpl.java:297) ~[classes/:na]
	at org.terasology.core.world.generator.trees.TreeGeneratorCactus.generate(TreeGeneratorCactus.java:35) ~[na:na]
	at org.terasology.core.world.generator.rasterizers.TreeRasterizer.generateChunk(TreeRasterizer.java:57) ~[na:na]
	at org.terasology.world.generation.WorldImpl.rasterizeChunk(WorldImpl.java:64) ~[classes/:na]
	at org.terasology.world.generation.BaseFacetedWorldGenerator.createChunk(BaseFacetedWorldGenerator.java:77) ~[classes/:na]
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider$4.run(LocalChunkProvider.java:631) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
21:13:38.497 [Chunk-Generator-2] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[core:Cactus]
21:13:38.498 [Chunk-Generator-2] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:Cactus.LEFT with id 61
21:13:38.498 [Chunk-Generator-2] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:Cactus.RIGHT with id 62
```

(2)

```
21:19:29.246 [main] WARN  o.t.w.internal.WorldProviderCoreImpl - Attempted to access unavailable chunk via block at -69, -12, -46
21:19:29.246 [main] WARN  o.t.w.internal.WorldProviderCoreImpl - Attempted to access unavailable chunk via block at -69, -13, -46
21:19:36.610 [Chunk-Updater-3] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Updater-3
java.lang.NullPointerException: null
	at org.terasology.world.chunks.internal.ChunkImpl.getSunlight(ChunkImpl.java:206) ~[classes/:na]
	at org.terasology.world.chunks.internal.ChunkImpl.getSunlight(ChunkImpl.java:201) ~[classes/:na]
	at org.terasology.world.internal.ChunkViewCoreImpl.getSunlight(ChunkViewCoreImpl.java:141) ~[classes/:na]
	at org.terasology.world.internal.ChunkViewCoreImpl.getSunlight(ChunkViewCoreImpl.java:116) ~[classes/:na]
	at org.terasology.rendering.primitives.ChunkTessellator.calcLightingValuesForVertexPos(ChunkTessellator.java:181) ~[classes/:na]
	at org.terasology.rendering.primitives.ChunkTessellator.generateOptimizedBuffers(ChunkTessellator.java:116) ~[classes/:na]
	at org.terasology.rendering.primitives.ChunkTessellator.generateMesh(ChunkTessellator.java:69) ~[classes/:na]
	at org.terasology.rendering.world.ChunkMeshUpdateManager$ChunkUpdateTask.run(ChunkMeshUpdateManager.java:169) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
21:19:36.651 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
21:19:36.652 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
21:19:36.652 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Cervator
21:19:36.653 [main] INFO  o.t.logic.console.ConsoleImpl - [NOTIFICATION] Player "Cervator" has left the game
```

(3)

```
21:24:24.477 [main] INFO  o.t.e.m.l.InitialiseWorld - World seed: "wzobxM5aubjKD7DcdqJcp7YlwUksYDXf"
21:24:24.615 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.IllegalStateException: Seed has not been set
	at org.terasology.world.generation.WorldBuilder.build(WorldBuilder.java:86) ~[classes/:na]
	at org.terasology.ligthandshadow.logic.LASMapGenerator.setWorldSeed(LASMapGenerator.java:93) ~[na:na]
	at org.terasology.engine.modes.loadProcesses.InitialiseWorld.step(InitialiseWorld.java:107) ~[classes/:na]
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:237) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:458) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:384) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:151) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
21:24:24.616 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

(4)

```
21:26:54.975 [main] INFO  o.terasology.engine.TerasologyEngine - Initialization completed in 8.79sec.
21:26:56.215 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (36241056), capping to 1000
21:28:26.456 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: engine:0.54.0-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Breathing:0.1.1-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CakeLie:0.1.1-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: MusicDirector:0.2.1-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: ChrisVolume1OST:0.2.1-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Core:0.54.0-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CoreSampleGameplay:0.54.0-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Fences:0.1.1-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: FunnyBlocks:0.1.1-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Hunger:0.1.1-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: MarkovChains:1.5.1-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: NameGenerator:0.4.1-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Oreons:0.2.1-SNAPSHOT
21:28:26.463 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Pathfinding:0.1.1-SNAPSHOT
21:28:26.464 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Spawning:0.1.1-SNAPSHOT
21:28:26.464 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Portals:0.1.1-SNAPSHOT
21:28:26.464 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: TutorialWorldGeneration:0.1.1-SNAPSHOT
21:28:26.464 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: Valentines:0.1.1-SNAPSHOT
21:28:26.464 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: WildAnimals:0.1.1-SNAPSHOT
21:28:26.959 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.nio.file.ClosedWatchServiceException: null
	at sun.nio.fs.AbstractWatchService.checkOpen(AbstractWatchService.java:80) ~[na:1.8.0_45]
	at sun.nio.fs.AbstractWatchService.poll(AbstractWatchService.java:97) ~[na:1.8.0_45]
	at org.terasology.module.filesystem.ModuleWatchService.poll(ModuleWatchService.java:61) ~[gestalt-module-4.0.2.jar:4.0.2]
	at org.terasology.assets.module.ModuleWatcher.checkForChanges(ModuleWatcher.java:132) ~[gestalt-asset-core-4.0.2.jar:4.0.2]
	at org.terasology.assets.module.ModuleAwareAssetTypeManager.reloadChangedOnDisk(ModuleAwareAssetTypeManager.java:164) ~[gestalt-asset-core-4.0.2.jar:4.0.2]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:438) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:384) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:151) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
21:28:26.960 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

(5)

```
01:03:44.440 [main] ERROR org.terasology.assets.AssetType - Failed to load asset 'engine:UITexture'
java.security.PrivilegedActionException: null
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_45]
	at org.terasology.assets.AssetType.reload(AssetType.java:323) [gestalt-asset-core-4.0.2.jar:4.0.2]
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:352) [gestalt-asset-core-4.0.2.jar:4.0.2]
	at org.terasology.assets.AssetType.getAsset(AssetType.java:232) [gestalt-asset-core-4.0.2.jar:4.0.2]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:206) [gestalt-asset-core-4.0.2.jar:4.0.2]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:186) [gestalt-asset-core-4.0.2.jar:4.0.2]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:170) [gestalt-asset-core-4.0.2.jar:4.0.2]
	at org.terasology.asset.Assets.get(Assets.java:80) [engine-0.54.0-SNAPSHOT.jar:1433, develop, 1433, pre-alpha]
	at org.terasology.asset.Assets.getMaterial(Assets.java:226) [engine-0.54.0-SNAPSHOT.jar:1433, develop, 1433, pre-alpha]
	at org.terasology.rendering.nui.internal.LwjglCanvasRenderer.<init>(LwjglCanvasRenderer.java:108) [engine-0.54.0-SNAPSHOT.jar:1433, develop, 1433, pre-alpha]
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postInitialise(LwjglGraphics.java:125) [engine-0.54.0-SNAPSHOT.jar:1433, develop, 1433, pre-alpha]
	at org.terasology.engine.TerasologyEngine.postInitSubsystems(TerasologyEngine.java:295) [engine-0.54.0-SNAPSHOT.jar:1433, origin/develop, 1433]
	at org.terasology.engine.TerasologyEngine.<init>(TerasologyEngine.java:188) [engine-0.54.0-SNAPSHOT.jar:1433, origin/develop, 1433]
	at org.terasology.engine.Terasology.main(Terasology.java:122) [Terasology.jar:1433, origin/develop, 1433]
Caused by: java.io.IOException: Unable to resolve shader 'engine:uiTexture'
	at org.terasology.rendering.assets.material.MaterialFormat.load(MaterialFormat.java:72) ~[engine-0.54.0-SNAPSHOT.jar:1433, develop, 1433, pre-alpha]
	at org.terasology.rendering.assets.material.MaterialFormat.load(MaterialFormat.java:47) ~[engine-0.54.0-SNAPSHOT.jar:1433, develop, 1433, pre-alpha]
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292) ~[gestalt-asset-core-4.0.2.jar:4.0.2]
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180) ~[gestalt-asset-core-4.0.2.jar:4.0.2]
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228) ~[gestalt-asset-core-4.0.2.jar:4.0.2]
	at org.terasology.assets.AssetType.lambda$reload$1(AssetType.java:325) [gestalt-asset-core-4.0.2.jar:4.0.2]
	at org.terasology.assets.AssetType$$Lambda$42/1463022229.run(Unknown Source) ~[na:na]
	... 14 common frames omitted
01:03:44.441 [main] ERROR o.terasology.engine.TerasologyEngine - Failed to initialise Terasology
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[na:1.8.0_45]
	at org.terasology.rendering.nui.internal.LwjglCanvasRenderer.<init>(LwjglCanvasRenderer.java:108) ~[engine-0.54.0-SNAPSHOT.jar:1433, develop, 1433, pre-alpha]
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postInitialise(LwjglGraphics.java:125) ~[engine-0.54.0-SNAPSHOT.jar:1433, develop, 1433, pre-alpha]
	at org.terasology.engine.TerasologyEngine.postInitSubsystems(TerasologyEngine.java:295) ~[engine-0.54.0-SNAPSHOT.jar:1433, origin/develop, 1433]
	at org.terasology.engine.TerasologyEngine.<init>(TerasologyEngine.java:188) ~[engine-0.54.0-SNAPSHOT.jar:1433, origin/develop, 1433]
	at org.terasology.engine.Terasology.main(Terasology.java:122) [Terasology.jar:1433, origin/develop, 1433]
01:03:44.441 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by MarcinSc** [comment]
I wouldn't count on loading game working well for now. I found about 3-4 issues with it and will create issues once I get some time and proper internet access, and that was with old code, so new one might have introduced more stuff.

**Comment by Cervator** [comment]
Yep we are expecting further issues. Some were fixed during the big PR. The more we identify the more we can fix :-)

Will appreciate it!

**Comment by immortius** [comment]
(4) Is possibly a threading issue related to environment switch, depending when it occurs. Will investigate but would be easier with instructions to reproduce if it is consistent.
(5) Ignore the PrivilegedActionException (I probably need to filter that out), the important bit is the inner exception (shader not found) and the following exception. Is the uiTexture shader asset being included in the distro correctly?

**Comment by MarcinSc** [comment]
Just a mental note, in case someone wants to take a look at it, before I manage to create proper issues.

1. Block entities without components that require persistence get stored, if they are active when save is made.
2. Entities with component that has a collection of @ManagedContainer objects throw exception when getting deserialized (with old asset code, did not check new one).
3. Block entities in the same chunk are getting loaded and have their lifecycle events called one by one. As a result, if during OnActivatedComponent of a block entity I make a call to get an entity of another block (that was persisted), I will get default (from prefab) entity for that block.
4. When block entities have their lifecycle events called upon loading chunk, it's impossible to get any block from that chunk.
5. PreBegin method of ComponentSystem is called after world is loaded, which is the opposite of what the javadoc for that method says.

**Comment by Cervator** [comment]
(4) is not consistent :-( Encountered it twice. I *suspect* it might only occur if there is a crashed version of the game holding file watchers in some bad state, and you run a new game instance on top.

(5) I see assets/shaders/ui/[stuff] in the engine jar packaged with the zip, yep. Includes `uitexture.info`, `uitexture_frag.glsl`, `uitexture_vert.glsl`. Material file seems to be there too.

**Comment by immortius** [comment]
(5) On further investigation, apparently the reflections.cache in engine has list the GLSLShaderFormat as being marked with the RegisterAssetFileFormat annotation, which results it not being set up and shaders not being discovered.

**Comment by immortius** [comment]
@MarcinSc On your number 5, I intend to improve the initialisation code shortly, and will attempt to deal with issues like these as part of that. Please let me know of any similar issues.

**Comment by MarcinSc** [comment]
I have created issues from my list - #1763 #1764 #1765 #1766 and #1767 with some more detail (where available and needed).

**Comment by MarcinSc** [comment]
Signalling and ComputerMonitors should compile after my PR #1768 gets accepted.

**Comment by immortius** [comment]
I spent some more time investigating (5). Still not sure is going wrong - the same code outside of the gradle context works correctly, so something odd in there I guess. Perhaps we need to encapsulate the reflections caching into a gradle plugin or some such?

Easy fix for now is to turn off the compile time caching of reflections and allow it to be calculated at runtime, although this obviously comes with a load time cost.

**Comment by immortius** [comment]
Investigated (4). Error occurred if an asset reload check occurs after the module environment is changed and the old environment shut down, but the asset manager hasn't been switched to the new environment yet. I've patched the issue in #1769 but this is just another indication of the need to revisit the core engine handling of initialisation and game lifecycle. Will start this next.

**Comment by MarcinSc** [comment]
Fantastic!

**Comment by Cervator** [comment]
Closing this as resolved, split out, or likely fixed over time without more specific poking
