### ISSUE TITLE
Crash on placing starting workbench in JoshariasSurvival

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1779]
Found while testing #1739 but unknown if it relates. We've broken a lot of stuff lately so lots of possibilities :-)

To reproduce: Start JoshariasSurvival, place the workbench block you start with, boom:

```
00:18:20.578 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block ManualLabor:WoodenChest.BACK with id 199
00:18:20.580 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[ManualLabor:ToolAssemblyTable]
00:18:20.580 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block ManualLabor:ToolAssemblyTable with id 200
00:18:20.608 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.rendering.primitives.BlockMeshGeneratorSingleShape.generateMesh(BlockMeshGeneratorSingleShape.java:188) ~[classes/:na]
	at org.terasology.rendering.primitives.BlockMeshGeneratorSingleShape.getStandaloneMesh(BlockMeshGeneratorSingleShape.java:171) ~[classes/:na]
	at org.terasology.world.block.Block.getMesh(Block.java:545) ~[classes/:na]
	at org.terasology.rendering.nui.layers.ingame.inventory.ItemCell$3.get(ItemCell.java:84) ~[classes/:na]
	at org.terasology.rendering.nui.layers.ingame.inventory.ItemCell$3.get(ItemCell.java:79) ~[classes/:na]
	at org.terasology.rendering.nui.layers.ingame.inventory.ItemIcon.getMesh(ItemIcon.java:127) ~[classes/:na]
	at org.terasology.workstation.ui.InventoryItem.<init>(InventoryItem.java:34) ~[na:na]
	at org.terasology.workstation.process.inventory.InventoryInputComponent.getInputDescription(InventoryInputComponent.java:161) ~[na:na]
	at org.terasology.workstation.system.ProcessPartWorkstationProcess.getInputDescription(ProcessPartWorkstationProcess.java:244) ~[na:na]
	at org.terasology.workstation.ui.ProcessSummaryWidget.<init>(ProcessSummaryWidget.java:40) ~[na:na]
	at org.terasology.workstation.ui.ProcessListWidget.initializeWorkstation(ProcessListWidget.java:59) ~[na:na]
	at org.terasology.machines.ui.DefaultMachineWindow.initializeWithInteractionTarget(DefaultMachineWindow.java:184) ~[na:na]
	at org.terasology.rendering.nui.BaseInteractionScreen.onOpened(BaseInteractionScreen.java:42) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.prepare(NUIManagerInternal.java:543) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:269) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:233) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:220) ~[classes/:na]
	at org.terasology.logic.characters.interactions.InteractionSystem.onInteractionStartPredicted(InteractionSystem.java:122) ~[classes/:na]
	at org.terasology.logic.characters.interactions.InteractionSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:270) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:261) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[classes/:na]
	at org.terasology.logic.characters.interactions.InteractionSystem.onActivationPredicted(InteractionSystem.java:83) ~[classes/:na]
	at org.terasology.logic.characters.interactions.InteractionSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:270) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:261) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayer.activateTargetOrOwnedEntity(LocalPlayer.java:190) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayer.activateTargetAsClient(LocalPlayer.java:168) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayerSystem.onFrobButton(LocalPlayerSystem.java:307) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayerSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:280) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:259) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[classes/:na]
	at org.terasology.input.internal.BindableButtonImpl.updateBindState(BindableButtonImpl.java:176) ~[classes/:na]
	at org.terasology.input.InputSystem.processKeyboardInput(InputSystem.java:319) ~[classes/:na]
	at org.terasology.input.InputSystem.update(InputSystem.java:205) ~[classes/:na]
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:198) ~[classes/:na]
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:76) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:495) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:404) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:151) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
00:18:20.612 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by immortius** [comment]
I would guess whatever BlockFamilyFactory that block uses isn't assigning the blocks uris.

**Comment by Josharias** [comment]
Immortius is correct.  The URI setting code was removed via merge failure.  It has been fixed with https://github.com/Terasology/Machines/commit/a1f1d5a25d2b57bded16fde2c9ed03d7fb7cc773.  (I still havent quite got the knack of referring to issues in a different git repo, so I am going the opposite way around)
