### ISSUE TITLE
Crash on filling bucket with liquid in TTA

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1802]
Split out from #1762. Unsure which module needs to be changed.

Probably a simple fix, just a bit more tweaking needed after the big gestalt-asset-core merge.

@MarcinSc - ping if you are up for fixing it real quick :-)

Edit: Also pinging @Josharias just in case, since you've done some fun with fluids for some time now

```
20:54:12.581 [main] INFO  o.t.logic.console.ConsoleImpl - [CONSOLE] You received an item of WoodAndStone:WoodenBucket
20:54:30.756 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.terasology.fluid.system.FluidContainerAssetResolver.getAssetData(FluidContainerAssetResolver.java:97) ~[na:na]
	at org.terasology.assets.AssetType.lambda$reload$1(AssetType.java:325) ~[gestalt-asset-core-4.0.3.jar:4.0.3]
	at org.terasology.assets.AssetType$$Lambda$43/1167088639.run(Unknown Source) ~[na:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_45]
	at org.terasology.assets.AssetType.reload(AssetType.java:323) ~[gestalt-asset-core-4.0.3.jar:4.0.3]
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:352) ~[gestalt-asset-core-4.0.3.jar:4.0.3]
	at org.terasology.assets.AssetType.getAsset(AssetType.java:232) ~[gestalt-asset-core-4.0.3.jar:4.0.3]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:206) ~[gestalt-asset-core-4.0.3.jar:4.0.3]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:186) ~[gestalt-asset-core-4.0.3.jar:4.0.3]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:170) ~[gestalt-asset-core-4.0.3.jar:4.0.3]
	at org.terasology.fluid.system.FluidClientSystem.setFluidContainerIcon(FluidClientSystem.java:65) ~[na:na]
	at org.terasology.fluid.system.FluidClientSystem.onFluidContentsChanged(FluidClientSystem.java:47) ~[na:na]
	at org.terasology.fluid.system.FluidClientSystemMethodAccess.invoke(Unknown Source) ~[na:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:358) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.saveComponent(PojoEntityManager.java:651) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.saveComponent(BaseEntityRef.java:122) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.fluid.system.FluidUtils.setFluidForContainerItem(FluidUtils.java:30) ~[na:na]
	at org.terasology.fluid.system.FluidAuthoritySystem.fillFluidContainerItem(FluidAuthoritySystem.java:61) ~[na:na]
	at org.terasology.fluid.system.FluidAuthoritySystemMethodAccess.invoke(Unknown Source) ~[na:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:280) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:259) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.logic.characters.CharacterSystem.onActivationRequest(CharacterSystem.java:139) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.logic.characters.CharacterSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:270) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:261) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.logic.players.LocalPlayer.activateTargetOrOwnedEntity(LocalPlayer.java:198) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.logic.players.LocalPlayer.activateOwnedEntityAsClient(LocalPlayer.java:157) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.logic.players.LocalPlayerSystem.onUseItemButton(LocalPlayerSystem.java:325) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.logic.players.LocalPlayerSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:280) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:259) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.input.internal.BindableButtonImpl.updateBindState(BindableButtonImpl.java:176) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:252) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.input.InputSystem.update(InputSystem.java:204) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:198) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:76) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:495) ~[engine-0.54.0-SNAPSHOT.jar:1452, origin/develop, 1452]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:404) ~[engine-0.54.0-SNAPSHOT.jar:1452, origin/develop, 1452]
	at org.terasology.engine.Terasology.main(Terasology.java:151) [Terasology.jar:1452, origin/develop, 1452]
20:54:30.756 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by Cervator** [comment]
Looked into this a bit more to see if I could fix it. *Kinda* but not really.

The issue is `FluidContainerAssetResolver.getAssetData` which when fed a urn fails to parse it correctly. The method is a bit fragile and depends on multiple String splits without error checking. Currently it uses the urn.getResourceName but ends up only parsing one of the six needed parameters.

If I simply switch the split steps with a single split from the fragment name instead of resource name: 

`String[] parameters = urn.getFragmentName().toString().toLowerCase().split(",");`

Then all six parameters *look* right but the first one is meant to hold an asset reference to the container with a hole in it (so a liquid can be rendered on top) and only has plain "woodenbucket" which fails to resolve - it looks like it works better with "WoodAndStone:items#WoodenBucket" in that spot but that would need to be parsed out properly.

Even with that hacked in I still end up with an empty looking bucket though, so maybe more tweaking is needed.

I put a small validation in place that currently fails (expects 6 parsed tokens, gets 1) but at least now it doesn't crash the game. I still get an empty looking bucket and am unsure if it is actually empty or just not rendering a liquid type.

https://github.com/Terasology/Fluid/commit/e95eedcf11a82b163cb13396fb76d95064862458

I'm closing this as the crash is fixed and submitting an issue against the Fluid module instead for reviewing and fixing the rendering.
