### ISSUE TITLE
Cities not registering its world generator + L&S world crashes

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1803]
Likely collateral damage from some of the recent major changes, split out from #1762

I figure the two issues are closely related as L&S builds on the world gen in Cities. Sending this @msteiger's way since he's probably ideal for a quick fix.

Issue 1 - Cities' world gen is not registered in a fashion that lets it show up in the world selection box

`o.t.w.g.i.WorldGeneratorManager - class org.terasology.cities.CityWorldGenerator marked to be registered as a World Generator, but is not a subclass of WorldGenerator or lacks the correct constructor`

Issue 2 - L&S world gen crashes on startup with a seed issue

```
21:00:59.520 [main] INFO  o.t.e.m.l.InitialiseWorld - World seed: "1FMPdvL1djHP7wKFKh3VWWZOOysy8GMV"
21:00:59.553 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.IllegalStateException: Seed has not been set
	at org.terasology.world.generation.WorldBuilder.build(WorldBuilder.java:86) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.ligthandshadow.logic.LASMapGenerator.setWorldSeed(LASMapGenerator.java:93) ~[na:na]
	at org.terasology.engine.modes.loadProcesses.InitialiseWorld.step(InitialiseWorld.java:107) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:240) ~[engine-0.54.0-SNAPSHOT.jar:1452, develop, 1452, pre-alpha]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:478) ~[engine-0.54.0-SNAPSHOT.jar:1452, origin/develop, 1452]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:404) ~[engine-0.54.0-SNAPSHOT.jar:1452, origin/develop, 1452]
	at org.terasology.engine.Terasology.main(Terasology.java:151) [Terasology.jar:1452, origin/develop, 1452]
21:00:59.553 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by Cervator** [comment]
All fixed by @Josharias and I tossed in a dependency fix for LASR so overrides on world textures would work. Still a bit more work to do, will detail elsewhere.
