### ISSUE TITLE
ViewDistance is not able to be changed after recent Context changes (even crashes the game)

### ISSUE THREAD

**Issue by Josharias** [MovingBlocks/Terasology#1832]
This binding in the video screen no longer works because there is no setter method like it expects...
https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/videoSettings/VideoSettingsScreen.java#L74

Probably is on someones todo list already. Making sure it was mentioned.

**Comment by emanuele3d** [comment]
Please assign it to me. Will check it out as soon as possible.

**Comment by Cervator** [comment]
Happy to oblige! :-)

**Comment by Cervator** [comment]
Bump. This may have gotten a bit worse, the game actually crashes for me right now if you try to enter the graphic settings.

Was testing around seeing if we might be ready for a release, so marking this an outright blocker now. Help appreciated :-)

Log:

```
21:18:52.397 [main] WARN  o.t.r.nui.databinding.BindHelper - Failed to resolve property viewDistance of type class org.terasology.config.RenderingConfig - is the getter or setter missing?
21:18:52.415 [main] WARN  o.t.r.nui.databinding.BindHelper - Failed to resolve property fullscreen of type class org.terasology.engine.TerasologyEngine - is the getter or setter missing?
21:18:52.432 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.rendering.nui.widgets.UICheckbox.getMode(UICheckbox.java:67) ~[classes/:na]
	at org.terasology.rendering.nui.internal.CanvasImpl.calculateRestrictedSize(CanvasImpl.java:325) ~[classes/:na]
	at org.terasology.rendering.nui.layouts.ColumnLayout.calculateRowSize(ColumnLayout.java:204) ~[classes/:na]
	at org.terasology.rendering.nui.layouts.ColumnLayout.getPreferredContentSize(ColumnLayout.java:230) ~[classes/:na]
	at org.terasology.rendering.nui.internal.CanvasImpl.calculateRestrictedSize(CanvasImpl.java:328) ~[classes/:na]
	at org.terasology.rendering.nui.widgets.UIBox.getPreferredContentSize(UIBox.java:46) ~[classes/:na]
	at org.terasology.rendering.nui.internal.CanvasImpl.calculateRestrictedSize(CanvasImpl.java:328) ~[classes/:na]
	at org.terasology.rendering.nui.layouts.ScrollableArea.onDraw(ScrollableArea.java:75) ~[classes/:na]
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:373) ~[classes/:na]
	at org.terasology.rendering.nui.layouts.relative.RelativeLayout.onDraw(RelativeLayout.java:69) ~[classes/:na]
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:373) ~[classes/:na]
	at org.terasology.rendering.nui.CoreScreenLayer.onDraw(CoreScreenLayer.java:103) ~[classes/:na]
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:373) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.render(NUIManagerInternal.java:369) ~[classes/:na]
	at org.terasology.engine.modes.StateMainMenu.render(StateMainMenu.java:153) ~[classes/:na]
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:171) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:447) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:358) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:158) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
```
