### ISSUE TITLE
Sometimes terasology crashes with ClosedWatchServiceException while loading

### ISSUE THREAD

**Issue by flo** [MovingBlocks/Terasology#1837]
@immortius  can you have a look at this one:
```
23:17:07.573 [main] INFO  o.t.e.m.loadProcesses.RegisterMods - Activating module: CoreSampleGameplay:0.54.0-SNAPSHOT
23:17:08.797 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.nio.file.ClosedWatchServiceException: null
	at sun.nio.fs.AbstractWatchService.checkOpen(AbstractWatchService.java:80) ~[na:1.8.0_40]
	at sun.nio.fs.AbstractWatchService.poll(AbstractWatchService.java:97) ~[na:1.8.0_40]
	at org.terasology.module.filesystem.ModuleWatchService.poll(ModuleWatchService.java:61) ~[gestalt-module-4.0.3.jar:4.0.3]
	at org.terasology.assets.module.ModuleWatcher.checkForChanges(ModuleWatcher.java:132) ~[gestalt-asset-core-4.0.3.jar:4.0.3]
	at org.terasology.assets.module.ModuleAwareAssetTypeManager.reloadChangedOnDisk(ModuleAwareAssetTypeManager.java:164) ~[gestalt-asset-core-4.0.3.jar:4.0.3]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:410) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:358) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:158) [classes/:na]
23:17:08.799 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
java.nio.file.ClosedWatchServiceException
	at sun.nio.fs.AbstractWatchService.checkOpen(AbstractWatchService.java:80)
	at sun.nio.fs.AbstractWatchService.poll(AbstractWatchService.java:97)
	at org.terasology.module.filesystem.ModuleWatchService.poll(ModuleWatchService.java:61)
	at org.terasology.assets.module.ModuleWatcher.checkForChanges(ModuleWatcher.java:132)
	at org.terasology.assets.module.ModuleAwareAssetTypeManager.reloadChangedOnDisk(ModuleAwareAssetTypeManager.java:164)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:410)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:358)
	at org.terasology.engine.Terasology.main(Terasology.java:158)
For more details, see the log files in /home/flo/programs/Terasology/logs/2015-07-18_23-15-55
```

**Comment by Josharias** [comment]
I also get this one a lot.  In fact most every time I run headless. If I put a breakpoint and rerun the code after this error, it always works.
Will post my logs later today.  It kind of feels like its a file system asynchrony thing as I also get odd out of turn things happen when doing game saves.

**Comment by immortius** [comment]
It is some sort of race condition, I haven't been able to work out exactly where yet. In theory the engine must be holding an old reference to a closed module environment after it has been closed.

**Comment by immortius** [comment]
Oh, please also ensure your workspace is up to date and using the correct version of gestalt (4.0.3, probably could update terasology to use 4.1.0), older version may have some threading issues.

I haven't had this issue in a while, so I thought it was fixed.

**Comment by flo** [comment]
In the stacktrace you can see that the bug occured with gestalt-module-4.0.3

**Comment by Cervator** [comment]
I tried a headless + client connecting real quick using Gestalt 4.1.0, but crashed immediately on trying to join with the client :-(

Also, what's with the weird delta? We've gotten reports about that occasionally.

```
21:26:52.570 [main] INFO  o.terasology.engine.TerasologyEngine - Initialization completed in 9.39sec.
21:26:53.965 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (34473803), capping to 1000
21:27:12.219 [Parallel Operation] INFO  o.t.n.internal.NetworkSystemImpl - Connected to server
21:27:12.465 [New I/O worker #3] INFO  o.t.n.i.ClientHandshakeHandler - Received Server Hello
21:27:12.471 [New I/O worker #3] INFO  o.t.n.i.ClientHandshakeHandler - No existing identity, requesting one
21:27:13.201 [New I/O worker #3] INFO  o.t.n.i.ClientHandshakeHandler - Received identity from server
21:27:13.291 [New I/O worker #3] INFO  o.t.n.i.ClientConnectionHandler - Received server info
21:27:13.326 [New I/O worker #3] INFO  o.t.n.i.ClientConnectionHandler - Join complete received
21:27:13.331 [main] INFO  o.t.e.modes.loadProcesses.JoinServer - Activating module: CoreSampleGameplay:0.54.0-SNAPSHOT
21:27:13.334 [main] INFO  o.t.e.modes.loadProcesses.JoinServer - Activating module: Core:0.54.0-SNAPSHOT
21:27:13.334 [main] INFO  o.t.e.modes.loadProcesses.JoinServer - Activating module: engine:0.54.0-SNAPSHOT
21:27:13.335 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:27:13.481 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.nio.file.ClosedWatchServiceException: null
	at sun.nio.fs.AbstractWatchService.checkOpen(AbstractWatchService.java:80) ~[na:1.8.0_45]
	at sun.nio.fs.AbstractWatchService.poll(AbstractWatchService.java:97) ~[na:1.8.0_45]
	at org.terasology.module.filesystem.ModuleWatchService.poll(ModuleWatchService.java:61) ~[gestalt-module-4.1.0.jar:4.1.0]
	at org.terasology.assets.module.ModuleWatcher.checkForChanges(ModuleWatcher.java:132) ~[gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.module.ModuleAwareAssetTypeManager.reloadChangedOnDisk(ModuleAwareAssetTypeManager.java:164) ~[gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:410) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:358) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:158) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
21:27:13.481 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by immortius** [comment]
Oh, so it happens when a client joins? Ok, will see if I can reproduce.

Not sure exactly what is going on with the time, but something to do with how time is managed during loading I would guess. Probably doesn't affect much, may be losing a second of time at the start of the game.

**Comment by immortius** [comment]
Ok, should be fixed now. I stepped through the background thread that does the asset manger environment switch and could see where the crash was happening.

**Comment by Cervator** [comment]
Awesome! Thanks :-)
