### ISSUE TITLE
Issue with behavior assets

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1840]
One of the remaining issues in L&S (and really Pathfinding) is that the behavior assets don't seem to work, I figure that happened after the gestalt-asset-core merge.

Errors like this get logged on startup when running L&S (or just with WildAnimals enabled):

```
22:39:17.379 [main] ERROR org.terasology.assets.AssetType - Failed to load asset 'pathfinding:movetowork'
java.io.IOException: Cannot load tree! java.io.NotSerializableException: Pathfinding:SetTargetToWorkNode
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:97) [classes/:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:84) [classes/:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:60) [classes/:na]
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType.lambda$reload$1(AssetType.java:325) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType$$Lambda$46/644052207.run(Unknown Source) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_45]
	at org.terasology.assets.AssetType.reload(AssetType.java:323) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:352) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType.getAsset(AssetType.java:232) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:206) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:186) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:170) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.asset.Assets.get(Assets.java:80) [classes/:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:202) [classes/:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:215) [classes/:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:205) [classes/:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:215) [classes/:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:205) [classes/:na]
	at com.google.gson.Gson.fromJson(Gson.java:810) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson.loadTree(BehaviorTreeFormat.java:128) [classes/:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:94) [classes/:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:84) [classes/:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:60) [classes/:na]
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType.lambda$reload$1(AssetType.java:325) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType$$Lambda$46/644052207.run(Unknown Source) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_45]
	at org.terasology.assets.AssetType.reload(AssetType.java:323) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:352) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType.getAsset(AssetType.java:232) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:206) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:186) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:170) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.asset.Assets.get(Assets.java:80) [classes/:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:202) [classes/:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:215) [classes/:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:205) [classes/:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:215) [classes/:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:205) [classes/:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:205) [classes/:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:205) [classes/:na]
	at com.google.gson.Gson.fromJson(Gson.java:810) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson.loadTree(BehaviorTreeFormat.java:128) [classes/:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:94) [classes/:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:84) [classes/:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:60) [classes/:na]
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType.lambda$reload$1(AssetType.java:325) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType$$Lambda$46/644052207.run(Unknown Source) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_45]
	at org.terasology.assets.AssetType.reload(AssetType.java:323) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:352) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType.getAsset(AssetType.java:232) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:206) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:186) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:170) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.asset.Assets.get(Assets.java:80) [classes/:na]
	at org.terasology.persistence.typeHandling.extensionTypes.AssetTypeHandler.getFromString(AssetTypeHandler.java:49) [classes/:na]
	at org.terasology.persistence.typeHandling.extensionTypes.AssetTypeHandler.getFromString(AssetTypeHandler.java:29) [classes/:na]
	at org.terasology.persistence.typeHandling.StringRepresentationTypeHandler.deserialize(StringRepresentationTypeHandler.java:45) [classes/:na]
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:98) [classes/:na]
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:153) [classes/:na]
	at org.terasology.persistence.serializers.ComponentSerializer.deserializeOnto(ComponentSerializer.java:203) [classes/:na]
	at org.terasology.persistence.serializers.ComponentSerializer.deserialize(ComponentSerializer.java:119) [classes/:na]
	at org.terasology.persistence.serializers.PrefabSerializer.applyComponentChanges(PrefabSerializer.java:165) [classes/:na]
	at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:137) [classes/:na]
	at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:117) [classes/:na]
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:54) [classes/:na]
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:37) [classes/:na]
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType.lambda$reload$1(AssetType.java:325) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType$$Lambda$46/644052207.run(Unknown Source) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_45]
	at org.terasology.assets.AssetType.reload(AssetType.java:323) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:352) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.AssetType.getAsset(AssetType.java:232) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:206) [gestalt-asset-core-4.1.0.jar:4.1.0]
	at org.terasology.engine.modes.loadProcesses.LoadPrefabs.step(LoadPrefabs.java:45) [classes/:na]
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:243) [classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:430) [classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:358) [classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:158) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
Caused by: com.google.gson.JsonSyntaxException: java.io.NotSerializableException: Pathfinding:SetTargetToWorkNode
	at com.google.gson.Gson.fromJson(Gson.java:825) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson.loadTree(BehaviorTreeFormat.java:128) [classes/:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:94) [classes/:na]
	... 119 common frames omitted
Caused by: java.io.NotSerializableException: Pathfinding:SetTargetToWorkNode
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:212) [classes/:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:215) [classes/:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103) [gson-2.3.1.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196) [gson-2.3.1.jar:na]
	at org.terasology.logic.behavior.asset.BehaviorTreeFormat$BehaviorTreeGson$NodeTypeAdapterFactory$1.read(BehaviorTreeFormat.java:205) [classes/:na]
	at com.google.gson.Gson.fromJson(Gson.java:810) [gson-2.3.1.jar:na]
	... 121 common frames omitted
22:39:17.382 [main] ERROR org.terasology.assets.AssetType - Failed to load asset 'Pathfinding:doWalkTo'
```

And the behaviors that make the creatures move and do stuff do not work.

I don't know if this'll be tricky without @synopia around as for all I know the behavior system needs updates (and was about to get some with the behavior tree 2.0 changes, but alas).

@immortius any idea how involved this would be to fix?

**Comment by immortius** [comment]
Something knocked loose when converting asset types over to the new system presumably - maybe a type not handled correctly? Would need to check the type if SetTargetToWorkNode or what it uses

**Comment by Cervator** [comment]
Yup it has its own .behaviors type

I figure some of the related stuff includes: 

* https://github.com/MovingBlocks/Terasology/tree/develop/engine/src/main/java/org/terasology/logic/behavior
* https://github.com/MovingBlocks/Terasology/tree/develop/engine/src/main/resources/assets/behaviors
* https://github.com/MovingBlocks/Terasology/tree/develop/engine/src/main/resources/assets/prefabs/behaviorNodes

**Comment by immortius** [comment]
I'm having difficulty reproducing this. I'm starting a new world with WildAnimals activated (and thus its dependencies), spawned a deer, no errors log and there is a deer wandering around. Is there something I'm missing?

**Comment by Cervator** [comment]
Hmm, I tried to clean my local workspace really well, but it must have not been good enough. I can't reproduce with the latest binary from Jenkins.

Thanks for looking into it, I appreciate it :-)
