### ISSUE TITLE
MusicDirector unable to load music assets

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1849]
Maybe because they live in a different module, rather than in Core?

To reproduce: Enable ChrisVolume1OST (which'll enable MusicDirector) and start a game. Wait a few moments for the first piece to be queued up, boom access denied:

```
15:49:59.813 [main] INFO  o.t.musicdirector.MusicDirectorImpl - Enqueued Heroes
15:49:59.817 [main] INFO  o.t.musicdirector.MusicDirectorImpl - Starting to play 'Heroes'
15:49:59.836 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Dev\Terasology\Git\integrate\Terasology\engine\build\classes" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457) ~[na:1.8.0_45]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[na:1.8.0_45]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[na:1.8.0_45]
	at org.terasology.module.sandbox.ModuleSecurityManager.checkPermission(ModuleSecurityManager.java:49) ~[gestalt-module-4.1.1.jar:4.1.1]
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[na:1.8.0_45]
	at sun.nio.fs.WindowsPath.checkRead(WindowsPath.java:792) ~[na:1.8.0_45]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:49) ~[na:1.8.0_45]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[na:1.8.0_45]
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193) ~[na:1.8.0_45]
	at java.nio.file.Files.readAttributes(Files.java:1737) ~[na:1.8.0_45]
	at java.nio.file.Files.isDirectory(Files.java:2192) ~[na:1.8.0_45]
	at org.terasology.module.filesystem.ModulePath.getUnderlyingPath(ModulePath.java:434) ~[gestalt-module-4.1.1.jar:4.1.1]
	at org.terasology.module.filesystem.ModuleFileSystemProvider.getUnderlyingPath(ModuleFileSystemProvider.java:240) ~[gestalt-module-4.1.1.jar:4.1.1]
	at org.terasology.module.filesystem.ModuleFileSystemProvider.readAttributes(ModuleFileSystemProvider.java:202) ~[gestalt-module-4.1.1.jar:4.1.1]
	at java.nio.file.Files.readAttributes(Files.java:1737) ~[na:1.8.0_45]
	at java.nio.file.Files.isRegularFile(Files.java:2229) ~[na:1.8.0_45]
	at org.terasology.assets.format.AssetDataFile.openStream(AssetDataFile.java:99) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.audio.formats.OggStreamingSoundData.reset(OggStreamingSoundData.java:74) ~[classes/:na]
	at org.terasology.audio.openAL.streamingSound.OpenALStreamingSound.reset(OpenALStreamingSound.java:125) ~[classes/:na]
	at org.terasology.audio.openAL.streamingSound.OpenALStreamingSoundSource.stop(OpenALStreamingSoundSource.java:49) ~[classes/:na]
	at org.terasology.audio.openAL.BaseSoundPool.stopAll(BaseSoundPool.java:128) ~[classes/:na]
	at org.terasology.audio.openAL.OpenALManager.playMusic(OpenALManager.java:226) ~[classes/:na]
	at org.terasology.audio.openAL.OpenALManager.playMusic(OpenALManager.java:214) ~[classes/:na]
	at org.terasology.musicdirector.MusicDirectorImpl.checkTriggers(MusicDirectorImpl.java:126) ~[na:na]
	at org.terasology.musicdirector.MusicDirectorImpl.enqueue(MusicDirectorImpl.java:82) ~[na:na]
	at org.terasology.musicdirector.TimedTriggerSystem.onTimeEvent(TimedTriggerSystem.java:87) ~[na:na]
	at org.terasology.musicdirector.TimedTriggerSystemMethodAccess.invoke(Unknown Source) ~[na:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:270) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:261) ~[classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[classes/:na]
	at org.terasology.world.time.WorldTimeImpl.update(WorldTimeImpl.java:87) ~[classes/:na]
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:178) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:430) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:358) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:145) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
15:49:59.838 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

On a mildly related note if any changes to the MusicDirector module are needed there are a few notes about changes we can make now that we're on Java 8

**Comment by Cervator** [comment]
Closing as fixed
