### ISSUE TITLE
Inconsistent crash on game shutdown

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1855]
While release testing I hit the same crash 2-3 times. I would often have provoked an assortment of stuff in-game but couldn't catch a pattern or way to easily reproduce. I thought I'd copy in the stacktrace in case it proves useful or if somebody replicates it again. If not we can close later.

Last time (when I got this stacktrace) I had been running Josharias Survival and encountered the performance issue noted in #1854

```
17:23:46.334 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1183), capping to 1000
17:23:48.775 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
17:24:30.570 [Engine-Task-Pool] INFO  o.t.r.opengl.LwjglRenderingProcess - Screenshot 'Terasology-150726172430-1152x720.jpg' saved! 
17:24:43.111 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
17:24:43.182 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
17:24:43.184 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
17:24:43.184 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Cervator2
17:24:43.185 [main] INFO  o.t.logic.console.ConsoleImpl - [NOTIFICATION] Player "Cervator2" has left the game
17:24:43.186 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
17:24:48.886 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
17:24:48.887 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
17:24:52.367 [main] ERROR o.terasology.engine.TerasologyEngine - Clean game shutdown after an uncaught exception failed
java.lang.NullPointerException: null
	at org.terasology.rendering.opengl.OpenGLTexture.getData(OpenGLTexture.java:178) ~[classes/:na]
	at org.terasology.rendering.iconmesh.IconMeshFactory.generateIconMeshData(IconMeshFactory.java:74) ~[classes/:na]
	at org.terasology.rendering.iconmesh.IconMeshFactory.generateIconMeshData(IconMeshFactory.java:62) ~[classes/:na]
	at org.terasology.rendering.iconmesh.IconMeshDataProducer.getAssetData(IconMeshDataProducer.java:80) ~[classes/:na]
	at org.terasology.assets.AssetType.reloadFromProducers(AssetType.java:467) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.AssetType.refresh(AssetType.java:155) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.module.ModuleAwareAssetTypeManager.switchEnvironment(ModuleAwareAssetTypeManager.java:389) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.engine.bootstrap.EnvironmentSwitchHandler.cheapAssetManagerUpdate(EnvironmentSwitchHandler.java:128) ~[classes/:na]
	at org.terasology.engine.bootstrap.EnvironmentSwitchHandler.handleSwitchToEmptyEnivronment(EnvironmentSwitchHandler.java:144) ~[classes/:na]
	at org.terasology.engine.modes.StateIngame.dispose(StateIngame.java:157) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.cleanup(TerasologyEngine.java:462) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:364) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:145) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
```

**Comment by Cervator** [comment]
Hit it again this time in Light & Shadow after having placed the spawners and issued a command or two. The work system used is fragile and throws a lot of exceptions. Dunno if that leaves something in a bad state that encourages the shutdown crash. This was merely a return to the main menu rather than exit game, so maybe it is more a "leave world" issue

```
18:24:53.576 [main] INFO  org.terasology.work.WorkBoard - Pathfinding:buildBlock: open=0 requestable=0 targets=0 
18:24:53.759 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
18:24:53.764 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
18:24:53.768 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Cervator
18:24:53.775 [main] INFO  o.t.logic.console.ConsoleImpl - [NOTIFICATION] Player "Cervator" has left the game
18:24:53.778 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
18:24:54.471 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
18:24:54.471 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
18:24:57.937 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.rendering.opengl.OpenGLTexture.getData(OpenGLTexture.java:178) ~[classes/:na]
	at org.terasology.rendering.iconmesh.IconMeshFactory.generateIconMeshData(IconMeshFactory.java:74) ~[classes/:na]
	at org.terasology.rendering.iconmesh.IconMeshFactory.generateIconMeshData(IconMeshFactory.java:62) ~[classes/:na]
	at org.terasology.rendering.iconmesh.IconMeshDataProducer.getAssetData(IconMeshDataProducer.java:80) ~[classes/:na]
	at org.terasology.assets.AssetType.reloadFromProducers(AssetType.java:467) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.AssetType.refresh(AssetType.java:155) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.module.ModuleAwareAssetTypeManager.switchEnvironment(ModuleAwareAssetTypeManager.java:389) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.engine.bootstrap.EnvironmentSwitchHandler.cheapAssetManagerUpdate(EnvironmentSwitchHandler.java:128) ~[classes/:na]
	at org.terasology.engine.bootstrap.EnvironmentSwitchHandler.handleSwitchToEmptyEnivronment(EnvironmentSwitchHandler.java:144) ~[classes/:na]
	at org.terasology.engine.modes.StateIngame.dispose(StateIngame.java:157) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.switchState(TerasologyEngine.java:522) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.processPendingState(TerasologyEngine.java:515) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:412) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:358) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:145) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) ~[idea_rt.jar:na]
18:24:57.938 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
18:24:57.938 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
18:24:57.939 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
18:24:57.939 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
18:24:57.942 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
java.lang.NullPointerException
	at org.terasology.rendering.opengl.OpenGLTexture.getData(OpenGLTexture.java:178)
	at org.terasology.rendering.iconmesh.IconMeshFactory.generateIconMeshData(IconMeshFactory.java:74)
	at org.terasology.rendering.iconmesh.IconMeshFactory.generateIconMeshData(IconMeshFactory.java:62)
	at org.terasology.rendering.iconmesh.IconMeshDataProducer.getAssetData(IconMeshDataProducer.java:80)
	at org.terasology.assets.AssetType.reloadFromProducers(AssetType.java:467)
	at org.terasology.assets.AssetType.refresh(AssetType.java:155)
	at org.terasology.assets.module.ModuleAwareAssetTypeManager.switchEnvironment(ModuleAwareAssetTypeManager.java:389)
	at org.terasology.engine.bootstrap.EnvironmentSwitchHandler.cheapAssetManagerUpdate(EnvironmentSwitchHandler.java:128)
	at org.terasology.engine.bootstrap.EnvironmentSwitchHandler.handleSwitchToEmptyEnivronment(EnvironmentSwitchHandler.java:144)
	at org.terasology.engine.modes.StateIngame.dispose(StateIngame.java:157)
	at org.terasology.engine.TerasologyEngine.switchState(TerasologyEngine.java:522)
	at org.terasology.engine.TerasologyEngine.processPendingState(TerasologyEngine.java:515)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:412)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:358)
	at org.terasology.engine.Terasology.main(Terasology.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
For more details, see the log files in C:\Dev\Terasology\Git\integrate\Terasology\logs\2015-07-26_18-22-17
18:25:01.365 [main] ERROR o.terasology.engine.TerasologyEngine - Clean game shutdown after an uncaught exception failed
java.lang.NullPointerException: null
	at org.terasology.rendering.opengl.OpenGLTexture.getData(OpenGLTexture.java:178) ~[classes/:na]
	at org.terasology.rendering.iconmesh.IconMeshFactory.generateIconMeshData(IconMeshFactory.java:74) ~[classes/:na]
	at org.terasology.rendering.iconmesh.IconMeshFactory.generateIconMeshData(IconMeshFactory.java:62) ~[classes/:na]
	at org.terasology.rendering.iconmesh.IconMeshDataProducer.getAssetData(IconMeshDataProducer.java:80) ~[classes/:na]
	at org.terasology.assets.AssetType.reloadFromProducers(AssetType.java:467) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.AssetType.refresh(AssetType.java:155) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.assets.module.ModuleAwareAssetTypeManager.switchEnvironment(ModuleAwareAssetTypeManager.java:389) ~[gestalt-asset-core-4.1.1.jar:4.1.1]
	at org.terasology.engine.bootstrap.EnvironmentSwitchHandler.cheapAssetManagerUpdate(EnvironmentSwitchHandler.java:128) ~[classes/:na]
	at org.terasology.engine.bootstrap.EnvironmentSwitchHandler.handleSwitchToEmptyEnivronment(EnvironmentSwitchHandler.java:144) ~[classes/:na]
	at org.terasology.engine.modes.StateIngame.dispose(StateIngame.java:157) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.cleanup(TerasologyEngine.java:462) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:364) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:145) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) ~[idea_rt.jar:na]
```

**Comment by Cervator** [comment]
Getting this more consistently on shutting down from TTA

**Comment by Cervator** [comment]
Checked again to see if this had gone away before trying to do a checkpoint release, but nope, still seems to be there:

```
15:41:52.583 [main] ERROR o.terasology.engine.TerasologyEngine - Clean game shutdown after an uncaught exception failed
java.lang.NullPointerException: null
	at org.terasology.rendering.opengl.OpenGLTexture.getData(OpenGLTexture.java:178) ~[classes/:na]
	at org.terasology.rendering.iconmesh.IconMeshFactory.generateIconMeshData(IconMeshFactory.java:74) ~[classes/:na]
	at org.terasology.rendering.iconmesh.IconMeshFactory.generateIconMeshData(IconMeshFactory.java:62) ~[classes/:na]
	at org.terasology.rendering.iconmesh.IconMeshDataProducer.getAssetData(IconMeshDataProducer.java:80) ~[classes/:na]
	at org.terasology.assets.AssetType.reloadFromProducers(AssetType.java:467) ~[gestalt-asset-core-4.1.2.jar:4.1.2]
	at org.terasology.assets.AssetType.refresh(AssetType.java:155) ~[gestalt-asset-core-4.1.2.jar:4.1.2]
	at org.terasology.assets.module.ModuleAwareAssetTypeManager.switchEnvironment(ModuleAwareAssetTypeManager.java:389) ~[gestalt-asset-core-4.1.2.jar:4.1.2]
	at org.terasology.engine.bootstrap.EnvironmentSwitchHandler.cheapAssetManagerUpdate(EnvironmentSwitchHandler.java:128) ~[classes/:na]
	at org.terasology.engine.bootstrap.EnvironmentSwitchHandler.handleSwitchToEmptyEnivronment(EnvironmentSwitchHandler.java:149) ~[classes/:na]
	at org.terasology.engine.modes.StateIngame.dispose(StateIngame.java:157) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.cleanup(TerasologyEngine.java:435) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:372) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:146) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
```

@immortius could this be a final bit of dust kicked up by the asset refactor? I can usually get it from just starting TTA then exiting the game. Game window stalls after the error and I have to kill the process.

**Comment by immortius** [comment]
This appears to be a different issue to the previous one I fixed.

In this case it happens because:
* The texture asset providing the icon is disposed as the module is no longer available.
* The subtexture asset using the texture providing the particular subregion is not disposed, because subtexture have not been processed yet.
* An attempt is made to reload the icon mesh, which is part of environment switch to determine whether the asset can carry across or not. It discovers the existing subtexture, but the subtexture's texture data is not available.

The immediate fix is to have subtextures subscribe to the disposal of their parent texture and dispose themselves when that occurs. A broader issue is that the asset environment switch process is a little open to issues like this - because it has to work through the asset types in some order, and it doesn't know which types depend on other types (which is open to extension anyway). I guess this can partially be addressed by ensuring asset types are worked through in reverse registration order, and consider adding subscription to reload/disposal events to all assets to ease chaining disposals.

**Comment by Cervator** [comment]
Thanks for the intel :-)

Think this might get covered by your recent initialization work?

**Comment by immortius** [comment]
No, this will need separate work to fix.

**Comment by Cervator** [comment]
Ping @immortius - this has been raised as an issue on Linux still even after the fix. Still works fine on my Win7 system. Could you skim the log and see if it looks like the same or maybe is a subtly different problem?

http://forum.terasology.org/threads/delta-too-great.1374/#post-12377
