### ISSUE TITLE
Benign (?) chunk generation error on shrinking view distance

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1856]
I've seen these errors from time to time without really being sure what causes them. They don't *seem* to cause trouble but I'm not sure. I figure what happens is a chunk gets interrupted mid-generation when the player moves out of range or changes the view distance, in this case I had just increased to "far" then set it back to "legally blind"

Could/should we handle this better by catching it with a more graceful log statement and/or doing something about it? I don't know if this could lead to problematic chunks or if the partially generated one just gets discarded and regenerated later.

It may also be killing a worker thread permanently? I seem to recall when we had an issue causing this more frequently you'd run out of chunk updaters and the world would stop updating.

In any case me see stacktrace me want fix stacktrace :-) Or make it a legit and understood logged warning.

```
18:07:19.324 [main] INFO  o.t.r.world.RenderableWorldImpl - New Viewing Distance: Far
18:07:19.996 [main] INFO  o.t.r.n.l.m.v.VideoSettingsScreen - Video Settings: {"pixelFormat":24,"windowPosX":223,"windowPosY":286,"windowWidth":1152,"windowHeight":720,"fullscreen":false,"viewDistance":"far","flickeringLight":true,"animateGrass":true,"animateWater":false,"fieldOfView":90.0,"cameraBobbing":true,"renderPlacingBox":true,"blurIntensity":2,"reflectiveWater":false,"vignette":true,"motionBlur":true,"ssao":false,"filmGrain":true,"outline":true,"lightShafts":true,"eyeAdaptation":true,"bloom":true,"dynamicShadows":true,"oculusVrSupport":false,"maxTextureAtlasResolution":4096,"maxChunksUsedForShadowMapping":1024,"shadowMapResolution":1024,"normalMapping":false,"parallaxMapping":false,"dynamicShadowsPcfFiltering":false,"cloudShadows":true,"renderNearest":true,"particleEffectLimit":10,"frameLimit":60,"meshLimit":400,"inscattering":true,"localReflections":false,"vSync":false,"clampLighting":false,"fboScale":100,"dumpShaders":false,"screenshotSize":"normal size","screenshotFormat":"jpg","cameraSettings":{"cameraSetting":"normal"},"debug":{"enabled":false,"stage":"opaque_color","firstPersonElementsHidden":false,"hudHidden":false,"wireframe":false,"renderChunkBoundingBoxes":false,"renderSkeletons":false}}
18:07:34.225 [main] INFO  o.t.r.world.RenderableWorldImpl - New Viewing Distance: Legally Blind
18:07:34.303 [Chunk-Updater-6] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Updater-6
java.lang.NullPointerException: null
	at org.terasology.world.chunks.internal.ChunkImpl.getSunlight(ChunkImpl.java:206) ~[classes/:na]
	at org.terasology.world.chunks.internal.ChunkImpl.getSunlight(ChunkImpl.java:201) ~[classes/:na]
	at org.terasology.world.internal.ChunkViewCoreImpl.getSunlight(ChunkViewCoreImpl.java:141) ~[classes/:na]
	at org.terasology.world.internal.ChunkViewCoreImpl.getSunlight(ChunkViewCoreImpl.java:116) ~[classes/:na]
	at org.terasology.rendering.primitives.ChunkTessellator.calcLightingValuesForVertexPos(ChunkTessellator.java:179) ~[classes/:na]
	at org.terasology.rendering.primitives.ChunkTessellator.generateOptimizedBuffers(ChunkTessellator.java:116) ~[classes/:na]
	at org.terasology.rendering.primitives.ChunkTessellator.generateMesh(ChunkTessellator.java:69) ~[classes/:na]
	at org.terasology.rendering.world.ChunkMeshUpdateManager$ChunkUpdateTask.run(ChunkMeshUpdateManager.java:169) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
18:07:34.351 [Chunk-Updater-3] ERROR o.t.u.concurrency.TaskProcessor - Error in thread Chunk-Updater-3
java.lang.NullPointerException: null
	at org.terasology.world.chunks.internal.ChunkImpl.getSunlight(ChunkImpl.java:206) ~[classes/:na]
	at org.terasology.world.chunks.internal.ChunkImpl.getSunlight(ChunkImpl.java:201) ~[classes/:na]
	at org.terasology.world.internal.ChunkViewCoreImpl.getSunlight(ChunkViewCoreImpl.java:141) ~[classes/:na]
	at org.terasology.world.internal.ChunkViewCoreImpl.getSunlight(ChunkViewCoreImpl.java:116) ~[classes/:na]
	at org.terasology.rendering.primitives.ChunkTessellator.calcLightingValuesForVertexPos(ChunkTessellator.java:179) ~[classes/:na]
	at org.terasology.rendering.primitives.ChunkTessellator.generateOptimizedBuffers(ChunkTessellator.java:116) ~[classes/:na]
	at org.terasology.rendering.primitives.ChunkTessellator.generateMesh(ChunkTessellator.java:69) ~[classes/:na]
	at org.terasology.rendering.world.ChunkMeshUpdateManager$ChunkUpdateTask.run(ChunkMeshUpdateManager.java:169) ~[classes/:na]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
18:07:34.656 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
18:07:34.658 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
18:07:34.879 [main] INFO  o.t.r.n.l.m.v.VideoSettingsScreen - Video Settings: {"pixelFormat":24,"windowPosX":223,"windowPosY":286,"windowWidth":1152,"windowHeight":720,"fullscreen":false,"viewDistance":"legally blind","flickeringLight":true,"animateGrass":true,"animateWater":false,"fieldOfView":90.0,"cameraBobbing":true,"renderPlacingBox":true,"blurIntensity":2,"reflectiveWater":false,"vignette":true,"motionBlur":true,"ssao":false,"filmGrain":true,"outline":true,"lightShafts":true,"eyeAdaptation":true,"bloom":true,"dynamicShadows":true,"oculusVrSupport":false,"maxTextureAtlasResolution":4096,"maxChunksUsedForShadowMapping":1024,"shadowMapResolution":1024,"normalMapping":false,"parallaxMapping":false,"dynamicShadowsPcfFiltering":false,"cloudShadows":true,"renderNearest":true,"particleEffectLimit":10,"frameLimit":60,"meshLimit":400,"inscattering":true,"localReflections":false,"vSync":false,"clampLighting":false,"fboScale":100,"dumpShaders":false,"screenshotSize":"normal size","screenshotFormat":"jpg","cameraSettings":{"cameraSetting":"normal"},"debug":{"enabled":false,"stage":"opaque_color","firstPersonElementsHidden":false,"hudHidden":false,"wireframe":false,"renderChunkBoundingBoxes":false,"renderSkeletons":false}}
18:07:36.112 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
```

**Comment by immortius** [comment]
Well, sunlight data is set to null during chunk disposal. Something is not checking for disposal or locking chunks correctly.
