### ISSUE TITLE
Game shows grey screen and becomes unresponsive after pressing play on Arch GNU/Linux

### ISSUE THREAD

**Issue by ingegnue** [MovingBlocks/Terasology#1897]
I am given the following error:
![2015-08-16-195251_1366x768_scrot](https://cloud.githubusercontent.com/assets/13824419/9296119/00e7cfce-4453-11e5-8320-d6017e2f5de7.png)
![2015-08-16-195256_1366x768_scrot](https://cloud.githubusercontent.com/assets/13824419/9296121/04b24e54-4453-11e5-9cfc-3ff887d56e85.png)

java.lang.IncompatibleClassChangeError: Found interface org.terasology.asset.AssetManager, but class was expected
        at org.terasology.farm.system.FarmCommonSystem.preBegin(FarmCommonSystem.java:31) ~[na:na]
        at org.terasology.engine.modes.loadProcesses.PreBeginSystems.step(PreBeginSystems.java:39) ~[engine-0.53.0.jar:53, master, 53, pre-alpha]
        at org.terasology.engine.modes.StateLoading.update(StateLoading.java:236) ~[engine-0.53.0.jar:53, master, 53, pre-alpha]
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:445) ~[engine-0.53.0.jar:53, origin/master, 53]
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:373) ~[engine-0.53.0.jar:53, origin/master, 53]
        at org.terasology.engine.Terasology.main(Terasology.java:152) [Terasology.jar:53, origin/master, 53]

**Comment by Cervator** [comment]
Hi @ingegnue - you appear to be using an outdated version of the game (engine level v0.53.0). Did you by chance get it out of a software repository? We don't maintain any of those so any game downloads there tend to go out of date (and are not official)

Try the Omega zip from https://github.com/MovingBlocks/Terasology/releases/tag/v0.54.0 and please let us know if that fixes the issue :-)

The error in question is likely an old build issue we've since fixed (module/engine stuff built out of order when some fundamental changes were done)

**Comment by ingegnue** [comment]
Yes, it came from my distro's repo. I'll try the new one and get back to
you, thanks!

On 08/17/15 00:00, Rasmus Praestholm wrote:
>
> Hi @ingegnue <https://github.com/ingegnue> - you appear to be using an
outdated version of the game (engine level v0.53.0). Did you by chance
get it out of a software repository? We don't maintain any of those so
any game downloads there tend to go out of date (and are not official)
>
> Try the Omega zip from
https://github.com/MovingBlocks/Terasology/releases/tag/v0.54.0 and
please let us know if that fixes the issue :-)
>
> The error in question is likely an old build issue we've since fixed
(module/engine stuff built out of order when some fundamental changes
were done)
>
> —
> Reply to this email directly or view it on GitHub
<https://github.com/MovingBlocks/Terasology/issues/1897#issuecomment-131674124>.
>
