### ISSUE TITLE
Poorly configured music asset can crash the game

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1955]
Reported in forum: http://forum.terasology.org/threads/need-help-tera-newbie-has-a-crashing-game-and-doesnt-know-why.1386/

Root cause is https://github.com/Terasology/LegacyMusic/blob/master/assets/prefabs/SpatialWinds.prefab (with a 't') vs. https://github.com/Terasology/LegacyMusic/blob/master/assets/music/SpacialWinds.ogg (with a 'c')

That's an easy fix - just configure the asset right. The more interesting bug is that this surely shouldn't crash the game - we need to harden something. Log:

```
01:08:41.624 [main] INFO  o.t.musicdirector.MusicDirectorImpl - Enqueued SpatialWinds
01:08:41.632 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[na:1.8.0_60]
	at org.terasology.musicdirector.MusicDirectorImpl.checkTriggers(MusicDirectorImpl.java:115) ~[na:na]
	at org.terasology.musicdirector.MusicDirectorImpl.enqueue(MusicDirectorImpl.java:82) ~[na:na]
	at org.terasology.musicdirector.TimedTriggerSystem.onTimeEvent(TimedTriggerSystem.java:87) ~[na:na]
	at org.terasology.musicdirector.TimedTriggerSystemMethodAccess.invoke(Unknown Source) ~[na:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[engine-0.54.2.jar:58, master, 58, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:270) ~[engine-0.54.2.jar:58, master, 58, pre-alpha]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:261) ~[engine-0.54.2.jar:58, master, 58, pre-alpha]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:144) ~[engine-0.54.2.jar:58, master, 58, pre-alpha]
	at org.terasology.world.time.WorldTimeImpl.update(WorldTimeImpl.java:87) ~[engine-0.54.2.jar:58, master, 58, pre-alpha]
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:178) ~[engine-0.54.2.jar:58, master, 58, pre-alpha]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414) ~[engine-0.54.2.jar:58, origin/master, 58]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369) ~[engine-0.54.2.jar:58, origin/master, 58]
	at org.terasology.engine.Terasology.main(Terasology.java:154) [Terasology.jar:58, origin/master, 58]
```

**Comment by msteiger** [comment]
This should be fixed since #1944, which is not yet part of the latest release (right?).

**Comment by Cervator** [comment]
Good point, I had in fact been testing with latest release instead of latest source. However I just tried that too and can still replicate.

Just run game with LegacyMusic enabled and wait for SpatialWinds to come up in the queue. Boom.

It isn't a receiveEvent, it looks like an asset loading failure instead:

`StreamingSound sound = Assets.getMusic(uri).get();`

The MusicDirector even checks if it gets a null sound back, and Assets.getMusic's doc suggests it'll return null if not found. But still boom.

**Comment by msteiger** [comment]
Sorry, I can't test it right now, because I have a fairly "custom" setup here.

The "boom" part makes sense, but `ByteCodeEventHandlerInfo.invoke()` should have caught the exception.

Is it possible that the stacktrace is different with the latest develop build? Maybe uses `ReceiverEventHandlerInfo` instead?

**Comment by Cervator** [comment]
No worries :-)

Nope, same stacktrace. Stepping through code in debug mode it looks like ContextManager.getCurrentContext() in gestalt-asset-core ends up with a null context. Somehow in this scenario it isn't getting a hold of a LegacyMusic module reference? Probably I just don't know that part well enough and it may not matter.

That then gets passed into AssetManager.getAsset (still in Gestalt) where it provides an empty ("") moduleContext to the resolve method. Seems to handle it OK.

Eventually we indeed get caught in a finally block under EventSystemImpl$ByteCodeEventHandlerInfo.invoke then pass through the exception handler

... and then the game doesn't crash. It just gracefully continues after throwing the stacktrace. Try again without debug mode leaving the game window inactive and it again didn't crash. Huh. Then try two more times, one leaving the window active while the crash happened and another while I had the window up with the menu active while working in another window and it still crashed.

Confusing.

Bigger copy paste with a full crash:

```
23:55:33.730 [main] INFO  o.t.musicdirector.MusicDirectorImpl - Enqueued SpatialWinds
23:55:47.966 [main] INFO  o.t.musicdirector.MusicDirectorImpl - Song 'Resurface' ended
23:55:47.987 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[na:1.8.0_45]
	at org.terasology.musicdirector.MusicDirectorImpl.checkTriggers(MusicDirectorImpl.java:115) ~[na:na]
	at org.terasology.musicdirector.MusicDirectorImpl.access$600(MusicDirectorImpl.java:44) ~[na:na]
	at org.terasology.musicdirector.MusicDirectorImpl$1.onAudioEnd(MusicDirectorImpl.java:135) ~[na:na]
	at org.terasology.audio.openAL.OpenALManager.update(OpenALManager.java:275) ~[classes/:na]
	at org.terasology.engine.subsystem.lwjgl.LwjglAudio.postUpdate(LwjglAudio.java:64) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:423) ~[classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369) ~[classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:154) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
23:55:47.988 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
23:55:48.004 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
23:55:48.005 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
23:55:48.008 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Cervator
23:55:48.015 [main] INFO  o.t.logic.console.ConsoleImpl - [NOTIFICATION] Player "Cervator" has left the game
23:55:48.017 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
23:55:48.179 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
23:55:48.179 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
23:55:50.943 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'emptyIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UIIconBar","id":"breathBar","icon":"engine:icons#bubble","family":"breathBar","emptyIcon":"engine:icons#burstBubble","halfIconMode":"shrink","spacing":2,"maxIcons":10,"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-left":{"target":"CENTER"},"position-right":{"target":"RIGHT","widget":"toolbar"},"position-bottom":{"target":"TOP","widget":"toolbar","offset":1}}}
23:55:50.943 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'crosshairIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UICrosshair","id":"crosshair","crosshairIcon":"engine:gui#crosshair","chargeStages":["engine:gui#crosshairCharge1","engine:gui#crosshairCharge2","engine:gui#crosshairCharge3","engine:gui#crosshairCharge4","engine:gui#crosshairCharge5","engine:gui#crosshairCharge6","engine:gui#crosshairCharge7","engine:gui#crosshairCharge8"],"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-horizontal-center":{},"position-vertical-center":{}}}
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.terasology.musicdirector.MusicDirectorImpl.checkTriggers(MusicDirectorImpl.java:115)
	at org.terasology.musicdirector.MusicDirectorImpl.access$600(MusicDirectorImpl.java:44)
	at org.terasology.musicdirector.MusicDirectorImpl$1.onAudioEnd(MusicDirectorImpl.java:135)
	at org.terasology.audio.openAL.OpenALManager.update(OpenALManager.java:275)
	at org.terasology.engine.subsystem.lwjgl.LwjglAudio.postUpdate(LwjglAudio.java:64)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:423)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
For more details, see the log files in C:\Dev\Terasology\Git\integrate\Terasology\logs\2015-10-05_23-52-38
```

Ran it through debug again but with an immediate resume after my breakpoint came up and it crashed again. Race condition of some sort maybe?

**Comment by Cervator** [comment]
Submitted the initial fix to the LegacyMusic repo so at least it won't trigger the crash. It'll still be sneakily awaiting more victims though.

Reference: https://github.com/Terasology/LegacyMusic/commit/8275c5836e1ade342bad0f45166100cb50c34ec5 - although it would probably be easier just to tweak the name in the prefab files to something that doesn't exist to provoke a crash
