### ISSUE TITLE
Crash with JoshariasSurvival when connected to minnesotags' server - sync between server/client?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1976]
I hit this myself earlier today but didn't think too much of it as I was running from my big messy mega-workspace with a data dir I've used for quite a while. But we just had a report on IRC from a guest who had connected to the server as well and crashed after about 5 minutes

Exact error is the same although I didn't capture any extra details from my log. Guest log:

```
12:02:05.541 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (2098), capping to 1000
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome MOUNTAINS with short id 0.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome SNOW with short id 1.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome DESERT with short id 2.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome FOREST with short id 3.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome OCEAN with short id 4.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome BEACH with short id 5.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome PLAINS with short id 6.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Registering biome org.terasology.world.biomes.UnknownBiome@80fafd with short id 0.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Restored biome Core:ocean with short id 4 from save game.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Restored biome Core:mountains with short id 1 from save game.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Restored biome Core:forest with short id 7 from save game.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Restored biome Core:beach with short id 2 from save game.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Restored biome Core:desert with short id 3 from save game.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Restored biome Core:snow with short id 5 from save game.
12:02:05.541 [main] INFO  o.t.world.biomes.BiomeManager - Restored biome Core:plains with short id 6 from save game.
12:02:05.758 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:05.809 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:05.954 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:05.966 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:05.982 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:06.003 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'groundFriction' onto 'engine:CharacterMovement'
12:02:06.003 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'maxGroundSpeed' onto 'engine:CharacterMovement'
12:02:06.003 [main] WARN  o.t.p.s.ComponentSerializer - Cannot deserialize unknown field 'distanceBetweenSwimStrokes' onto 'engine:CharacterMovement'
12:02:06.143 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'Breather'
12:02:06.181 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:06.217 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:06.242 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:06.247 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:06.248 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:06.287 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:06.352 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:06.371 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
12:02:08.012 [main] ERROR o.t.n.internal.NetworkSystemImpl - Server has unknown field 'depthRange' on 'OreGeneration:DepthPocketOreGen'
12:02:08.012 [main] ERROR o.t.n.internal.NetworkSystemImpl - Server has unknown field 'depth' on 'OreGeneration:DepthPocketOreGen'
12:02:08.075 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'emptyIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UIIconBar","id":"breathBar","icon":"engine:icons#bubble","family":"breathBar","emptyIcon":"engine:icons#burstBubble","halfIconMode":"shrink","spacing":2,"maxIcons":10,"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-left":{"target":"CENTER"},"position-right":{"target":"RIGHT","widget":"toolbar"},"position-bottom":{"target":"TOP","widget":"toolbar","offset":1}}}
12:02:08.075 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'crosshairIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UICrosshair","id":"crosshair","crosshairIcon":"engine:gui#crosshair","chargeStages":["engine:gui#crosshairCharge1","engine:gui#crosshairCharge2","engine:gui#crosshairCharge3","engine:gui#crosshairCharge4","engine:gui#crosshairCharge5","engine:gui#crosshairCharge6","engine:gui#crosshairCharge7","engine:gui#crosshairCharge8"],"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-horizontal-center":{},"position-vertical-center":{}}}
12:02:08.299 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 580, netId = 10621}
12:02:08.487 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 606, netId = 10648, prefab = 'JoshariasSurvival:Blueberry'}
12:02:08.487 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 607, netId = 10649, prefab = 'JoshariasSurvival:BlueberryBushFull'}
12:02:08.518 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 624, netId = 10677, prefab = 'JoshariasSurvival:BlueberryBushFull'}
12:02:08.518 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 623, netId = 10676, prefab = 'JoshariasSurvival:Blueberry'}
12:02:08.814 [main] ERROR o.t.w.p.i.BlockFamilyOutputComponent - Bad block: IRLCorp:IronFluidPipe
12:02:08.814 [main] WARN  o.t.w.s.DefaultWorkstationProcessFactory - Invalid Process: IRLCorp:AssembleIronFluidPipe. Could not create output items in BlockFamilyOutputComponent
12:02:09.136 [main] INFO  o.t.r.world.RenderableWorldImpl - New Viewing Distance: Near
12:02:11.064 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 630, netId = 10687, prefab = 'JoshariasSurvival:BlueberryBushFull'}
12:02:11.064 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 629, netId = 10686, prefab = 'JoshariasSurvival:Blueberry'}
12:02:11.256 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 636, netId = 10697, prefab = 'JoshariasSurvival:BlueberryBushFull'}
12:02:11.256 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 635, netId = 10696, prefab = 'JoshariasSurvival:Blueberry'}
12:02:22.225 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 582, netId = 10623, prefab = 'engine:iconItemPickup'}
12:02:27.223 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 596, netId = 10637, prefab = 'JoshariasSurvival:Blueberry'}
12:02:42.784 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 3588, netId = 10755, prefab = 'JoshariasSurvival:BlueberryBushFull'}
12:02:42.784 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 3587, netId = 10754, prefab = 'JoshariasSurvival:Blueberry'}
12:02:46.069 [main] ERROR o.t.network.internal.ServerImpl - Updating entity with no network component: EntityRef{id = 620}, expected netId 10673
12:02:46.280 [main] ERROR o.t.network.internal.ServerImpl - Updating entity with no network component: EntityRef{id = 620}, expected netId 10673
12:02:46.481 [main] ERROR o.t.network.internal.ServerImpl - Updating entity with no network component: EntityRef{id = 620}, expected netId 10673
12:02:46.720 [main] ERROR o.t.network.internal.ServerImpl - Updating entity with no network component: EntityRef{id = 620}, expected netId 10673
12:02:46.877 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.world.internal.EntityAwareWorldProvider.updateBlockEntityComponents(EntityAwareWorldProvider.java:237) ~[engine-0.54.3-SNAPSHOT.jar:1539, develop, 1539, pre-alpha]
	at org.terasology.world.internal.EntityAwareWorldProvider.updateBlockEntity(EntityAwareWorldProvider.java:153) ~[engine-0.54.3-SNAPSHOT.jar:1539, develop, 1539, pre-alpha]
	at org.terasology.world.internal.EntityAwareWorldProvider.setBlock(EntityAwareWorldProvider.java:124) ~[engine-0.54.3-SNAPSHOT.jar:1539, develop, 1539, pre-alpha]
	at org.terasology.world.internal.WorldProviderWrapper.setBlock(WorldProviderWrapper.java:52) ~[engine-0.54.3-SNAPSHOT.jar:1539, develop, 1539, pre-alpha]
	at org.terasology.network.internal.ServerImpl.processBlockChanges(ServerImpl.java:299) ~[engine-0.54.3-SNAPSHOT.jar:1539, develop, 1539, pre-alpha]
	at org.terasology.network.internal.ServerImpl.processMessages(ServerImpl.java:260) ~[engine-0.54.3-SNAPSHOT.jar:1539, develop, 1539, pre-alpha]
	at org.terasology.network.internal.ServerImpl.update(ServerImpl.java:176) ~[engine-0.54.3-SNAPSHOT.jar:1539, develop, 1539, pre-alpha]
	at org.terasology.network.internal.NetworkSystemImpl.update(NetworkSystemImpl.java:322) ~[engine-0.54.3-SNAPSHOT.jar:1539, develop, 1539, pre-alpha]
	at org.terasology.engine.subsystem.common.NetworkSubsystem.preUpdate(NetworkSubsystem.java:47) ~[engine-0.54.3-SNAPSHOT.jar:1539, develop, 1539, pre-alpha]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:407) ~[engine-0.54.3-SNAPSHOT.jar:1539, origin/develop, 1539]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369) ~[engine-0.54.3-SNAPSHOT.jar:1539, origin/develop, 1539]
	at org.terasology.engine.Terasology.main(Terasology.java:154) [Terasology.jar:1539, origin/develop, 1539]
12:02:46.878 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
12:02:46.884 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
12:02:46.900 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
12:02:47.576 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'emptyIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UIIconBar","id":"breathBar","icon":"engine:icons#bubble","family":"breathBar","emptyIcon":"engine:icons#burstBubble","halfIconMode":"shrink","spacing":2,"maxIcons":10,"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-left":{"target":"CENTER"},"position-right":{"target":"RIGHT","widget":"toolbar"},"position-bottom":{"target":"TOP","widget":"toolbar","offset":1}}}
12:02:47.577 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'crosshairIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UICrosshair","id":"crosshair","crosshairIcon":"engine:gui#crosshair","chargeStages":["engine:gui#crosshairCharge1","engine:gui#crosshairCharge2","engine:gui#crosshairCharge3","engine:gui#crosshairCharge4","engine:gui#crosshairCharge5","engine:gui#crosshairCharge6","engine:gui#crosshairCharge7","engine:gui#crosshairCharge8"],"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-horizontal-center":{},"position-vertical-center":{}}}
```

When it happened to me I had mined some coal and had picked up a few. On jumping into the last dropped block I crashed, almost as if it happened as the block was transformed from being in the world to being put in my inventory.

Both my local source workspace plus the guest's binary are a few versions ahead of @minnesotags' server at this point, mainly with some module tweaks by @Josharias. So that could possibly be the issue?

If it isn't something obvious or easy to reproduce we should probably upgrade the server to use the next release (out real soon) and see if it happens when using the exact same version server & client side.

Edit: I was alone on the server when it happened to me.

**Comment by Josharias** [comment]
Seems like there is some older stuff in that save game (or is it a server game?) Ironfluidpipe was replaced by fluidpipe a while ago.  Possibly we are dealing with just some version mismatch stuff?  

Yes, I definitely need to start doing versioning more right in my modules for this reason.

**Comment by Cervator** [comment]
@minnesotags just updated the server to latest develop and reset the world. Played around a little bit and no problem, we should hit the server some more and see if we can produce any issues :-)

I've hit the key_k issue being grabbed by another module now too (Tasks). I guess manually reassigning it in config.cfg should work. Or some grander reorientation to avoid hot key sprawl - we still need a character screen on `c` one day, that would probably be a good place for a simple section / button for skills :-)

@MarkDerosier (chessandgo) - ping! Sorry, requested a world reset. But in better news the ore distribution is fixed, I found iron one block from a sandy beach meeting a hill :D

If either of you can replicate the light merge issue we should get some better logging.

**Comment by Cervator** [comment]
Closing this as a likely non-issue. The lighting merge is covered in #1969
