### ISSUE TITLE
Crash error during world gen for Cities/Light & Shadow

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#1986]
Had a user report an issue in the forum: http://forum.terasology.org/threads/game-crashes-on-loading-of-new-world-2.1396/#post-12522

And just now on IRC with the same error: http://pastebin.com/YfdFQCkN

Both were with Light & Shadow active using City World, and the user on IRC, Dyrand, reported that it only happened with Cities and Light & Shadow (using City World), but not in configurations using Flat or Perlin worlds. @Josharias looked at the stacktrace and thought it might relate to entity interaction during world gen, which sounds plausible with Cities mixing in some new magic recently.

It also appears to only happen when launching from the binary build, not from source. Reflection caching issue? Easiest to just test using Cities from the recent Omega release 16:  http://jenkins.terasology.org/job/DistroOmegaRelease/16/artifact/distros/omega/build/distributions/TerasologyOmega.zip

@msteiger: maybe something for you?

Edit: Clarified world gen vs gameplay template. Issue appears triggered by City World. Added snippet:

```
18:43:50.285 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
        at org.terasology.reflection.metadata.ClassMetadata.copy(ClassMetadata.java:175) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.reflection.metadata.AbstractClassLibrary.copy(AbstractClassLibrary.java:124) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentChange(EntitySetDeltaRecorder.java:70) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentAdded(EntitySetDeltaRecorder.java:62) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.persistence.internal.ReadWriteStorageManager.onEntityComponentAdded(ReadWriteStorageManager.java:471) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.entitySystem.entity.internal.PojoEntityManager.notifyComponentAdded(PojoEntityManager.java:680) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.entitySystem.entity.internal.PojoEntityManager.addComponent(PojoEntityManager.java:596) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.entitySystem.entity.internal.BaseEntityRef.addComponent(BaseEntityRef.java:107) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.generateQueuedEntities(LocalChunkProvider.java:318) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.completeUpdate(LocalChunkProvider.java:264) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.engine.modes.loadProcesses.AwaitCharacterSpawn.step(AwaitCharacterSpawn.java:56) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.engine.modes.StateLoading.update(StateLoading.java:243) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414) ~[engine-0.54.3.jar:59, origin/master, 59]
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369) ~[engine-0.54.3.jar:59, origin/master, 59]
        at org.terasology.engine.Terasology.main(Terasology.java:154) [Terasology.jar:59, origin/master, 59]
18:43:50.286 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by msteiger** [comment]
Thanks @Josharias for the fix. Should we add a log warning / throw a exception that explains the missing constructor problem?

**Comment by Cervator** [comment]
That would be pretty nice, I did not expect that to be a constructor missing issue :-) Although if you start digging around it may be more clear (it is about copying things related to classes after all ..)

**Comment by Cervator** [comment]
Closing as fixed in latest develop build, hopefully released in a day or two
