### ISSUE TITLE
Failed launch - Pathfinder test world crashes

### ISSUE THREAD

**Issue by colindean** [MovingBlocks/Terasology#2003]
http://pastebin.com/EsgzaxLv

Pretty much default options...

**Comment by colindean** [comment]
This is on the latest release. Tried again, same failure after hitting I think `Play` after choosing map options.

**Comment by colindean** [comment]
I changed from the City map to another one and got a different error, this time about a seed not being set. The log shows the seed right before the crash.

http://pastebin.com/5j4wZZpH

**Comment by Cervator** [comment]
Hi @colindean and thanks for the report :-)

Your initial problem is #1986 which is fixed in the latest development build which you can get from the launcher or grab here: http://jenkins.terasology.org/job/DistroOmega/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip

However that dev build is unstable for other reasons and I'll be working on some tweaks before releasing a new stable build tomorrow. It'll run Cities / L&S well. The latest release should run everything else.

The second issue I can replicate if I pick the Pathfinder Testworld, which is a, well, test world, and not used very frequently. But yep it is broken and we need to fix that so I'll rename this issue to handle that, shouldn't be very hard. It also won't be very interesting though, that world is shaped funny just to test pathfinding :-)

Snippet for easy availability below, maybe @msteiger or @Josharias can fix real quick, or @synopia since it is his world, though mostly he's in AFK-land these days.

```
15:59:52.004 [main] INFO  o.t.e.m.l.InitialiseWorld - World seed: "TmTeu1b29bX49p6vfGawASzHrtvHE9uV"
15:59:52.023 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.IllegalStateException: Seed has not been set
        at org.terasology.world.generation.WorldBuilder.build(WorldBuilder.java:96) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.pathfinding.PathfinderTestWorldMapGenerator.setWorldSeed(PathfinderTestWorldMapGenerator.java:50) ~[na:na]
        at org.terasology.engine.modes.loadProcesses.InitialiseWorld.step(InitialiseWorld.java:108) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.engine.modes.StateLoading.update(StateLoading.java:243) ~[engine-0.54.3.jar:59, master, 59, pre-alpha]
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414) ~[engine-0.54.3.jar:59, origin/master, 59]
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369) ~[engine-0.54.3.jar:59, origin/master, 59]
        at org.terasology.engine.Terasology.main(Terasology.java:154) [Terasology.jar:59, origin/master, 59]
15:59:52.024 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by Cervator** [comment]
Fixed by https://github.com/Terasology/Pathfinding/pull/26 ! Closing.
