### ISSUE TITLE
Needs a .jar release for better portability

### ISSUE THREAD

**Issue by bradenbest** [MovingBlocks/Terasology#2021]
Being a Java program, I can't fathom why the pre-built release package would be in `PE32` Windows Executable format. The release should be cross-platform...

    ./run_linux.sh
    Exception in thread "main" java.lang.UnsupportedClassVersionError: org/terasology/engine/Terasology : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

...yet it somehow isn't. This is a colossal fuckup in my view.

**Comment by bradenbest** [comment]
Upon further inspection, it appears that the problem may be with my java runtime.

**Comment by Cervator** [comment]
Yep that just looks like a Java other than 8. Happens from time to time.

Current zip has executables for Windows, Linux, and Mac OS plus you can launch via .jar directly from command line.

I think the closest to Windows-specific stuff we do is try to fix line endings in some text files during the build so they'll look nicer on Windows (actually have newlines). I'm not sure if that can risk any issues on Linux. If you come across anything we could do better please let us know :-)
