### ISSUE TITLE
Odd crash in multiplayer

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2067]
I had joined @minnesotags' freshly updated server running pre-alpha release 61 then left my PC for a few minutes, came back to the CrashReporter showing a stacktrace. 

I was in a cave where I had earlier thrown some torches around, unsure what happened. Had also broken a few plants for plant matter (JoshariasSurvival is active there). Thought I'd put the stacktrace here in case it means something to somebody (@Josharias ?)

The crash occurred immediately after a few entities were destroyed (cleanup of some sort?)

Edit: When I logged back on the server I found myself back at spawn. Did my player object get garbage collected somehow? Heh.

Edit2: After making it back to the big cave area (I left a lit path there on the server) the torches I had earlier thrown on the ground were also gone. I was surprised when I logged back on after a long time (hours) that they were still there. After the crash they were gone.

```
23:19:30.528 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
23:19:31.345 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'emptyIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UIIconBar","id":"breathBar","icon":"engine:icons#bubble","family":"breathBar","emptyIcon":"engine:icons#burstBubble","halfIconMode":"shrink","spacing":2,"maxIcons":10,"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-left":{"target":"CENTER"},"position-right":{"target":"RIGHT","widget":"toolbar"},"position-bottom":{"target":"TOP","widget":"toolbar","offset":1}}}
23:19:31.346 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'crosshairIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UICrosshair","id":"crosshair","crosshairIcon":"engine:gui#crosshair","chargeStages":["engine:gui#crosshairCharge1","engine:gui#crosshairCharge2","engine:gui#crosshairCharge3","engine:gui#crosshairCharge4","engine:gui#crosshairCharge5","engine:gui#crosshairCharge6","engine:gui#crosshairCharge7","engine:gui#crosshairCharge8"],"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-horizontal-center":{},"position-vertical-center":{}}}
23:19:32.354 [main] INFO  o.t.r.world.RenderableWorldImpl - New Viewing Distance: Moderate
23:19:41.171 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 1094, netId = 1717}
23:19:48.652 [main] WARN  o.t.l.nameTags.NameTagClientSystem - Can't create player based name tag for character as owner has no client component
23:19:53.736 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 1271, netId = 1721, prefab = 'JoshariasSurvival:BlueberryBushFull'}
23:19:53.737 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 1270, netId = 1720, prefab = 'JoshariasSurvival:Blueberry'}
23:20:46.498 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 358}
23:20:46.498 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 357, netId = 1667, prefab = 'engine:blockItemBase'}
23:20:52.816 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 356, netId = 1666, prefab = 'engine:blockItemPickup'}
23:21:04.011 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 6343, netId = 1812}
23:21:04.378 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 6350, netId = 1818, prefab = 'engine:blockItemPickup'}
23:21:07.010 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 6364, netId = 1819}
23:21:08.442 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 6396, netId = 1824, prefab = 'engine:blockItemPickup'}
23:21:08.443 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 6395, netId = 1823, prefab = 'engine:blockItemBase'}
23:21:09.035 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 6412, netId = 1825}
23:21:09.035 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 6393, netId = 1822}
23:21:20.232 [main] ERROR o.t.network.internal.ServerImpl - Updating entity with no network component: EntityRef{id = 374}, expected netId 1686
23:21:20.233 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 374}
23:21:20.233 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 373, netId = 1685, prefab = 'engine:blockItemBase'}
23:21:26.501 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 372}
23:21:26.502 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 371, netId = 1683, prefab = 'engine:blockItemBase'}
23:21:31.187 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 7698, netId = 1833, prefab = 'engine:iconItemPickup'}
23:21:32.538 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 7819, netId = 1835}
23:21:43.344 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 370}
23:21:43.344 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 369, netId = 1681, prefab = 'engine:blockItemBase'}
23:21:59.696 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 368}
23:21:59.696 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 367, netId = 1679, prefab = 'engine:blockItemBase'}
23:22:28.652 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 7589}
23:22:28.652 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 7588, netId = 1829, prefab = 'ManualLabor:PlantMatter'}
23:22:48.852 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 1672, netId = 1731, prefab = 'engine:player'}
23:22:48.852 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 1671, netId = 1730, prefab = 'engine:blockItemBase'}
23:22:48.852 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 1670, netId = 1729, prefab = 'ManualLabor:PlantMatter'}
23:22:48.852 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 1669, netId = 1728, prefab = 'ManualLabor:TheHumanMachine'}
23:22:48.852 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 0}
23:22:48.853 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 1668, netId = 1726, prefab = 'engine:blockItemBase'}
23:29:39.250 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 7697, netId = 1832, prefab = 'ManualLabor:PlantMatter'}
23:29:39.251 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 355, netId = 1665, prefab = 'engine:blockItemBase'}
23:29:39.251 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 353, netId = 1664, prefab = 'engine:player'}
23:29:39.251 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 352, netId = 1663, prefab = 'ManualLabor:Stick'}
23:29:39.251 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 351, netId = 1662, prefab = 'ManualLabor:TheHumanMachine'}
23:29:39.251 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 350, netId = 1661, prefab = 'ManualLabor:PlantMatter'}
23:29:39.251 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 349, netId = 1660, prefab = 'engine:transferSlot'}
23:29:39.252 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 6349, netId = 1817, prefab = 'engine:blockItemBase'}
23:29:39.259 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.input.cameraTarget.PlayerTargetSystem.update(PlayerTargetSystem.java:67) ~[engine-0.54.5.jar:62, master, 62, pre-alpha]
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:176) ~[engine-0.54.5.jar:62, master, 62, pre-alpha]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414) ~[engine-0.54.5.jar:62, origin/master, 62]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369) ~[engine-0.54.5.jar:62, origin/master, 62]
	at org.terasology.engine.Terasology.main(Terasology.java:154) [Terasology.jar:62, origin/master, 62]
23:29:39.260 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
23:29:39.270 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
23:29:39.280 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
23:29:39.597 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'emptyIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UIIconBar","id":"breathBar","icon":"engine:icons#bubble","family":"breathBar","emptyIcon":"engine:icons#burstBubble","halfIconMode":"shrink","spacing":2,"maxIcons":10,"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-left":{"target":"CENTER"},"position-right":{"target":"RIGHT","widget":"toolbar"},"position-bottom":{"target":"TOP","widget":"toolbar","offset":1}}}
23:29:39.598 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'crosshairIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UICrosshair","id":"crosshair","crosshairIcon":"engine:gui#crosshair","chargeStages":["engine:gui#crosshairCharge1","engine:gui#crosshairCharge2","engine:gui#crosshairCharge3","engine:gui#crosshairCharge4","engine:gui#crosshairCharge5","engine:gui#crosshairCharge6","engine:gui#crosshairCharge7","engine:gui#crosshairCharge8"],"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-horizontal-center":{},"position-vertical-center":{}}}
```

**Comment by Cervator** [comment]
Closing this as likely obsolete (linked issue was closed as no longer reproducible)
