### ISSUE TITLE
Can I play Terasology without GL_ARB_framebuffer_object feature?

### ISSUE THREAD

**Issue by dpisarenko** [MovingBlocks/Terasology#2095]
When I try to launch Terasology, I'm getting the following error (full log below).

```
The following OpenGL versions/extensions are required but are not supported by your GPU driver:

    - GL_ARB_framebuffer_object
```

I'm wondering, if it's possible to play the game without that feature.

**Full log:**

```
21:50:59.803 [main] INFO  o.terasology.engine.TerasologyEngine - Initializing Terasology...
21:50:59.900 [main] INFO  o.terasology.engine.TerasologyEngine - [buildNumber=62, buildId=62, buildTag=jenkins-TerasologyStable-62, buildUrl=http://jenkins.terasology.org/job/TerasologyStable/62/, gitBranch=master, gitCommit=41c18376444be07fd75bca73dda04043076cade5, dateTime=2015-12-16T06:23:05Z, displayVersion=pre-alpha, engineVersion=0.54.5]
21:50:59.900 [main] INFO  o.terasology.engine.TerasologyEngine - Home path: C:\Users\DP118M\Saved Games\Terasology
21:50:59.903 [main] INFO  o.terasology.engine.TerasologyEngine - Install path: C:\Users\DP118M\Desktop\daily stuff\2015_12_30_terasology
21:50:59.905 [main] INFO  o.terasology.engine.TerasologyEngine - Java: 1.8.0_25 in C:\Program Files\Java\jre1.8.0_25
21:50:59.906 [main] INFO  o.terasology.engine.TerasologyEngine - Java VM: Java HotSpot(TM) Client VM, version: 25.25-b02
21:50:59.907 [main] INFO  o.terasology.engine.TerasologyEngine - OS: Windows 7, arch: x86, version: 6.1
21:50:59.907 [main] INFO  o.terasology.engine.TerasologyEngine - Max. Memory: 247 MiB
21:50:59.908 [main] INFO  o.terasology.engine.TerasologyEngine - Processors: 2
21:51:00.233 [main] INFO  o.t.e.s.c.ConfigurationSubsystem - Video Settings: {"pixelFormat":24,"windowPosX":378,"windowPosY":234,"windowWidth":1152,"windowHeight":720,"fullscreen":false,"viewDistance":"moderate","flickeringLight":true,"animateGrass":true,"animateWater":false,"fieldOfView":90.0,"cameraBobbing":true,"renderPlacingBox":true,"blurIntensity":2,"reflectiveWater":false,"vignette":true,"motionBlur":true,"ssao":false,"filmGrain":true,"outline":true,"lightShafts":true,"eyeAdaptation":true,"bloom":true,"dynamicShadows":true,"oculusVrSupport":false,"maxTextureAtlasResolution":4096,"maxChunksUsedForShadowMapping":1024,"shadowMapResolution":1024,"normalMapping":false,"parallaxMapping":false,"dynamicShadowsPcfFiltering":false,"cloudShadows":true,"renderNearest":true,"particleEffectLimit":10,"frameLimit":60,"meshLimit":400,"inscattering":true,"localReflections":false,"vSync":false,"clampLighting":false,"fboScale":100,"dumpShaders":false,"screenshotSize":"normal size","screenshotFormat":"jpg","cameraSettings":{"cameraSetting":"normal"},"debug":{"enabled":false,"stage":"opaque_color","firstPersonElementsHidden":false,"hudHidden":false,"wireframe":false,"renderChunkBoundingBoxes":false,"renderSkeletons":false}}
21:51:00.240 [main] WARN  org.terasology.utilities.LWJGLHelper - Could not load optional TeraOVR native libraries - Oculus support disabled
21:51:00.641 [main] INFO  o.t.module.ModulePathScanner - Discovered module: AlterationEffects-0.2.0-SNAPSHOT
21:51:00.644 [main] INFO  o.t.module.ModulePathScanner - Discovered module: AnotherWorld-0.2.0-SNAPSHOT
21:51:00.647 [main] INFO  o.t.module.ModulePathScanner - Discovered module: AnotherWorldPlants-0.1.1-SNAPSHOT
21:51:00.649 [main] INFO  o.t.module.ModulePathScanner - Discovered module: BlockNetwork-0.1.1-SNAPSHOT
21:51:00.652 [main] INFO  o.t.module.ModulePathScanner - Discovered module: BlockPicker-0.1.1-SNAPSHOT
21:51:00.655 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Breathing-0.1.1-SNAPSHOT
21:51:00.657 [main] INFO  o.t.module.ModulePathScanner - Discovered module: CakeLie-0.1.1-SNAPSHOT
21:51:00.660 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Caves-0.2.1-SNAPSHOT
21:51:00.663 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ChangingBlocks-0.1.1-SNAPSHOT
21:51:00.770 [main] INFO  o.t.module.ModulePathScanner - Discovered module: CheatsForAll-0.1.1-SNAPSHOT
21:51:00.773 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ChrisVolume1OST-0.2.1-SNAPSHOT
21:51:00.776 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ChrisVolume2OST-0.1.1-SNAPSHOT
21:51:00.783 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Cities-0.6.1-SNAPSHOT
21:51:00.786 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ClimateConditions-0.1.1-SNAPSHOT
21:51:00.788 [main] INFO  o.t.module.ModulePathScanner - Discovered module: CommonWorld-0.2.2-SNAPSHOT
21:51:00.792 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ComputerMonitors-0.1.1-SNAPSHOT
21:51:00.796 [main] INFO  o.t.module.ModulePathScanner - Discovered module: CopperAndBronze-0.1.1-SNAPSHOT
21:51:00.800 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Core-0.54.5
21:51:00.844 [main] INFO  o.t.module.ModulePathScanner - Discovered module: CoreSampleGameplay-0.54.5
21:51:00.846 [main] INFO  o.t.module.ModulePathScanner - Discovered module: CustomOreGen-0.1.1-SNAPSHOT
21:51:00.848 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Durability-0.1.1-SNAPSHOT
21:51:00.851 [main] INFO  o.t.module.ModulePathScanner - Discovered module: EventualSkills-0.1.0-SNAPSHOT
21:51:00.854 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Fences-0.1.1-SNAPSHOT
21:51:00.856 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Fluid-0.1.1-SNAPSHOT
21:51:00.859 [main] INFO  o.t.module.ModulePathScanner - Discovered module: FluidComputerIntegration-0.1.1-SNAPSHOT
21:51:00.862 [main] INFO  o.t.module.ModulePathScanner - Discovered module: FunnyBlocks-0.1.1-SNAPSHOT
21:51:00.864 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Genome-0.1.1-SNAPSHOT
21:51:00.867 [main] INFO  o.t.module.ModulePathScanner - Discovered module: GrowingFlora-0.1.1-SNAPSHOT
21:51:00.869 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Hunger-0.1.1-SNAPSHOT
21:51:00.873 [main] INFO  o.t.module.ModulePathScanner - Discovered module: InGameHelp-0.1.0-SNAPSHOT
21:51:00.877 [main] INFO  o.t.module.ModulePathScanner - Discovered module: IRLCorp-0.2.2-SNAPSHOT
21:51:00.884 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ItemRendering-0.1.2-SNAPSHOT
21:51:00.887 [main] INFO  o.t.module.ModulePathScanner - Discovered module: JoshariasSurvival-0.1.1-SNAPSHOT
21:51:00.890 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Journal-0.1.1-SNAPSHOT
21:51:00.894 [main] INFO  o.t.module.ModulePathScanner - Discovered module: LegacyMusic-0.1.1-SNAPSHOT
21:51:00.896 [main] INFO  o.t.module.ModulePathScanner - Discovered module: LightAndShadow-0.1.1-SNAPSHOT
21:51:00.899 [main] INFO  o.t.module.ModulePathScanner - Discovered module: LightAndShadowResources-0.2.0-SNAPSHOT
21:51:00.902 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Machines-0.1.2-SNAPSHOT
21:51:00.939 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Malicious-0.1.1-SNAPSHOT
21:51:00.942 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ManualLabor-0.1.1-SNAPSHOT
21:51:00.945 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ManualLaborEventualSkills-0.1.0-SNAPSHOT
21:51:00.948 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MarcinScIncubator-0.1.1-SNAPSHOT
21:51:00.950 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MarkovChains-1.5.1-SNAPSHOT
21:51:00.953 [main] INFO  o.t.module.ModulePathScanner - Discovered module: masteroforeon-0.1.1-SNAPSHOT
21:51:00.956 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Maze-0.1.1-SNAPSHOT
21:51:00.960 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Minerals-0.1.2-SNAPSHOT
21:51:00.965 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Miniion-0.2.1-SNAPSHOT
21:51:00.968 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Minimap-1.0.0-SNAPSHOT
21:51:00.971 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MobileBlocks-0.1.1-SNAPSHOT
21:51:00.974 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ModularComputers-0.1.1-SNAPSHOT
21:51:00.977 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MoreLights-0.1.1-SNAPSHOT
21:51:00.981 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MultiBlock-0.1.1-SNAPSHOT
21:51:00.984 [main] INFO  o.t.module.ModulePathScanner - Discovered module: MusicDirector-0.2.1-SNAPSHOT
21:51:00.987 [main] INFO  o.t.module.ModulePathScanner - Discovered module: NameGenerator-0.4.1-SNAPSHOT
21:51:00.990 [main] INFO  o.t.module.ModulePathScanner - Discovered module: OreGeneration-0.1.1-SNAPSHOT
21:51:00.998 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Oreons-0.2.1-SNAPSHOT
21:51:01.001 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Pathfinding-0.1.2-SNAPSHOT
21:51:01.004 [main] INFO  o.t.module.ModulePathScanner - Discovered module: PlantPack-0.1.1-SNAPSHOT
21:51:01.008 [main] INFO  o.t.module.ModulePathScanner - Discovered module: PolyWorld-0.7.1-SNAPSHOT
21:51:01.014 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Portals-0.1.1-SNAPSHOT
21:51:01.017 [main] INFO  o.t.module.ModulePathScanner - Discovered module: QuestExamples-0.2.0-SNAPSHOT
21:51:01.020 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Sample-0.1.1-SNAPSHOT
21:51:01.023 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Seasons-0.9.1-SNAPSHOT
21:51:01.026 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Signalling-0.1.1-SNAPSHOT
21:51:01.029 [main] INFO  o.t.module.ModulePathScanner - Discovered module: SimpleFarming-0.1.1-SNAPSHOT
21:51:01.031 [main] INFO  o.t.module.ModulePathScanner - Discovered module: SimpleLiquids-0.1.1-SNAPSHOT
21:51:01.034 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Soils-0.1.1-SNAPSHOT
21:51:01.038 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Spawning-0.1.1-SNAPSHOT
21:51:01.042 [main] INFO  o.t.module.ModulePathScanner - Discovered module: StructuralResources-0.2.1-SNAPSHOT
21:51:01.046 [main] INFO  o.t.module.ModulePathScanner - Discovered module: SubstanceMatters-0.1.1-SNAPSHOT
21:51:01.051 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Tasks-0.2.0-SNAPSHOT
21:51:01.054 [main] INFO  o.t.module.ModulePathScanner - Discovered module: ThroughoutTheAges-0.1.1-SNAPSHOT
21:51:01.058 [main] INFO  o.t.module.ModulePathScanner - Discovered module: TutorialWorldGeneration-0.1.1-SNAPSHOT
21:51:01.061 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Valentines-0.1.1-SNAPSHOT
21:51:01.065 [main] INFO  o.t.module.ModulePathScanner - Discovered module: WildAnimals-0.1.1-SNAPSHOT
21:51:01.069 [main] INFO  o.t.module.ModulePathScanner - Discovered module: WoodAndStone-0.1.1-SNAPSHOT
21:51:01.072 [main] INFO  o.t.module.ModulePathScanner - Discovered module: Workstation-0.1.1-SNAPSHOT
21:51:01.075 [main] INFO  o.t.module.ModulePathScanner - Discovered module: WorkstationInGameHelp-0.1.0-SNAPSHOT
21:51:01.079 [main] INFO  o.t.module.ModulePathScanner - Discovered module: WorldlyTooltip-0.1.1-SNAPSHOT
21:51:01.700 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:01.773 [main] INFO  o.t.audio.openAL.OpenALManager - Initializing OpenAL audio manager
21:51:01.833 [main] INFO  o.t.audio.openAL.OpenALManager - OpenAL 1.1 ALSOFT 1.15.1 initialized!
21:51:01.834 [main] INFO  o.t.audio.openAL.OpenALManager - Using OpenAL: OpenAL Soft by OpenAL Community
21:51:01.835 [main] INFO  o.t.audio.openAL.OpenALManager - Using device: OpenAL Soft
21:51:01.835 [main] INFO  o.t.audio.openAL.OpenALManager - Available AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
21:51:01.836 [main] INFO  o.t.audio.openAL.OpenALManager - Available ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
21:51:01.836 [main] INFO  o.t.audio.openAL.OpenALManager - Max mono sources: 255
21:51:01.836 [main] INFO  o.t.audio.openAL.OpenALManager - Max stereo sources: 1
21:51:01.837 [main] INFO  o.t.audio.openAL.OpenALManager - Mixer frequency: 44100
21:51:01.846 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Starting initialization of LWJGL
21:51:01.854 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Initial initialization complete
21:51:02.013 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.211 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.287 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.331 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.367 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.440 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.489 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.515 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.567 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.596 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.618 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.632 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.645 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.715 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.774 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.787 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.828 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.864 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.893 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.936 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:02.976 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.074 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.211 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.367 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.484 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.498 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.525 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.565 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.593 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.630 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.649 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.661 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.729 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.812 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.830 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.889 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.914 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.936 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.958 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:03.998 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.031 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.073 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.115 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.166 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.177 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.187 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.199 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.232 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.259 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.282 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.297 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.308 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.340 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.361 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.437 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.505 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.518 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.546 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.585 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.597 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.615 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.654 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.700 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.725 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.754 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.776 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.797 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.822 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.833 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.867 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.901 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.983 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:04.999 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:05.029 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:05.040 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:05.062 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:05.085 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:05.106 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:05.146 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:05.190 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
21:51:07.174 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Initializing display
21:51:07.513 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Initializing OpenGL
21:51:07.532 [main] ERROR o.terasology.engine.TerasologyEngine - Failed to initialise Terasology
java.lang.IllegalStateException: 

The following OpenGL versions/extensions are required but are not supported by your GPU driver:

    - GL_ARB_framebuffer_object

GPU Information:

    Vendor:  Intel
    Model:   Mobile Intel(R) 4 Series Express Chipset Family
    Driver:  2.1.0 - Build 8.15.10.1840

Try updating the driver to the latest version available.
If that fails you might need to use a different GPU (graphics card). Sorry!

	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.checkOpenGL(LwjglGraphics.java:305) ~[engine-0.54.5.jar:62, master, 62, pre-alpha]
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.initOpenGL(LwjglGraphics.java:266) ~[engine-0.54.5.jar:62, master, 62, pre-alpha]
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postInitialise(LwjglGraphics.java:170) ~[engine-0.54.5.jar:62, master, 62, pre-alpha]
	at org.terasology.engine.TerasologyEngine.postInitSubsystems(TerasologyEngine.java:261) [engine-0.54.5.jar:62, origin/master, 62]
	at org.terasology.engine.TerasologyEngine.initialize(TerasologyEngine.java:196) [engine-0.54.5.jar:62, origin/master, 62]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:362) [engine-0.54.5.jar:62, origin/master, 62]
	at org.terasology.engine.Terasology.main(Terasology.java:154) [Terasology.jar:62, origin/master, 62]
21:51:07.532 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by Cervator** [comment]
Hi @dpisarenko - I'm afraid that log statement is rather unambiguous :-)

Have you tried updating to the latest video card drivers?

It is possible that we'll extend compatibility to older cards in the future by splitting rendering into a basic version supporting older cards and a newer fancier version, but that's likely years off if it ever happens. It is a cool concept in theory but on an all-volunteer project there is a ton to do, few people to do it, and always something that's higher priority :-(

**Comment by emanuele3d** [comment]
Hi @dpisarenko, I'm the one who has been rummaging the most in the graphic engine code lately, including the code that triggers that error. 

Unfortunately Frame Buffer Objects are integral to Terasology's current graphics engine. You can think of them as Photoshop layers that are stacked together at runtime to generate the image you see on screen. Without them many modern graphical features Terasology has would be much harder if not impossible to achieve.

**Comment by dpisarenko** [comment]
Thanks, @Cervator and @emanuele3d for prompt feedback. I will close the issue as this features seems to be a vital requirement.

**Comment by Cervator** [comment]
You're welcome. Hope to see you back one day with some different hardware :-)
