### ISSUE TITLE
Modified blocks from a single player world cause trouble if reused in multiplayer

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2170]
Steps to reproduce:

1. Create a new world in single player
1. Modify some blocks - for instance break a few then place them in a new location (so they stand out)
1. Exit to main menu
1. Host a multiplayer game using the saved world from single player
1. Interact with the blocks previously modified, get NPE:

```
23:32:00.831 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.logic.players.LocalPlayerSystem.onTargetChanged(LocalPlayerSystem.java:261) ~[classes/:na]
	at org.terasology.logic.players.LocalPlayerSystemMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269) [classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260) [classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145) [classes/:na]
	at org.terasology.input.cameraTarget.PlayerTargetSystem.update(PlayerTargetSystem.java:72) [classes/:na]
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:176) [classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414) [classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369) [classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:154) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
23:32:42.085 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
```

This probably broke at some point in the past without us realizing it since it isn't a very common use-case. Probably the updated blocks are missing something that the multiplayer setup expects.

**Comment by Cervator** [comment]
Retested this as part of #2254 but while the stacktrace has disappeared in either case the quirks persist. On a reloaded single player world in multiplayer the second joining player didn't get a block breaking overlay on a block messed with in single player, despite it working fine for other blocks of the same type that were undisturbed.
