### ISSUE TITLE
Out of memory Error on a long running host game

### ISSUE THREAD

**Issue by Josharias** [MovingBlocks/Terasology#2191]
After running a local game as host using the latest stable exe,  I left it open for a few hours and came back to an out of memory error which actually caused a bunch of other stuff on my machine to also crash.  I was not around to see it happen,  or to know how much memory was actually being used.  Here is the log.

[Terasology-Game_3.log.txt](https://github.com/MovingBlocks/Terasology/files/150175/Terasology-Game_3.log.txt)

**Comment by Cervator** [comment]
Interesting note on the other stuff that crashed, which should mean it was a memory leak outside the JVM. We know @minnesotags has managed to keep a headless server online for days on Linux, even running a large module set like JS. Maybe something related to native code involving the Windows file system, like the auto-save system? I don't know if we've ever had any really long running servers on Windows.

Pinging @flo for reference

Snippet:

```
18:56:49.160 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
18:56:50.516 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
18:57:30.253 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (37909), capping to 1000
18:57:49.001 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1103), capping to 1000
18:57:49.217 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
18:57:49.218 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
18:57:49.399 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.OutOfMemoryError: null
	at java.util.zip.Deflater.init(Native Method) ~[na:1.8.0_71]
	at java.util.zip.Deflater.<init>(Unknown Source) ~[na:1.8.0_71]
	at java.util.zip.GZIPOutputStream.<init>(Unknown Source) ~[na:1.8.0_71]
	at java.util.zip.GZIPOutputStream.<init>(Unknown Source) ~[na:1.8.0_71]
	at org.terasology.persistence.internal.CompressedChunkBuilder.compressChunkStore(CompressedChunkBuilder.java:93) ~[engine-1.0.0-SNAPSHOT.jar:1641, develop, 1641, alpha]
	at org.terasology.persistence.internal.CompressedChunkBuilder.buildEncodedChunk(CompressedChunkBuilder.java:86) ~[engine-1.0.0-SNAPSHOT.jar:1641, develop, 1641, alpha]
	at org.terasology.persistence.internal.SaveTransaction.writeChunkStores(SaveTransaction.java:368) ~[engine-1.0.0-SNAPSHOT.jar:1641, develop, 1641, alpha]
	at org.terasology.persistence.internal.SaveTransaction.run(SaveTransaction.java:135) ~[engine-1.0.0-SNAPSHOT.jar:1641, develop, 1641, alpha]
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50) ~[engine-1.0.0-SNAPSHOT.jar:1641, develop, 1641, alpha]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_71]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_71]
18:57:49.400 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
18:57:49.444 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
18:57:49.445 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
```

**Comment by flo** [comment]
The auto save allocates temporarly extra memory. Thus if there is to less memory it will crash during the autosave. 

The log files are useless. What could be inspected is a memory dump. Java can automatically create one for you in an out of memory situation if you start it with the HeapDumpOnOutOfMemoryError option (https://docs.oracle.com/javase/7/docs/webnotes/tsg/TSG-VM/html/clopts.html)
