### ISSUE TITLE
Div by zero on min-length scrollbar (UI test screen)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2283]
Discovered while testing UI changes via `showScreen migTestScreen` 

If you click the "min" size UIScrollbar (or click-drag it) you get the following Exception - probably either easy to guard against or don't allow an entirely minimal scrollbar? Might be a unlikely use case in the first place (like other recent creative misuses of UI elements) but nothing crashes, you just get a quiet stacktrace.

```java
00:48:36.188 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.ArithmeticException: / by zero
	at org.terasology.rendering.nui.widgets.UIScrollbar$2.onMouseClick(UIScrollbar.java:94) ~[classes/:na]
	at org.terasology.rendering.nui.internal.CanvasImpl.processMouseClick(CanvasImpl.java:224) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:474) ~[classes/:na]
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source) ~[reflectasm-1.11.0.jar:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506) ~[classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279) [classes/:na]
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258) [classes/:na]
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145) [classes/:na]
	at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:503) [classes/:na]
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:324) [classes/:na]
	at org.terasology.input.InputSystem.update(InputSystem.java:271) [classes/:na]
	at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:138) [classes/:na]
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:54) [classes/:na]
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:423) [classes/:na]
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369) [classes/:na]
	at org.terasology.engine.Terasology.main(Terasology.java:150) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
```

**Comment by Cervator** [comment]
Closing as fixed by #2287!
