### ISSUE TITLE
Crash in multiplayer - character prediction issue?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2358]
We were testing DynamicCities with a few people online, also learned that for some reason in multiplayer the multijump functionality ends up enabled for infinite jumps. So it may somehow have to do with spamming multi-jump messing with the prediction?

Log snippet from server:

```
16:56:11.137 [main] WARN  o.t.l.c.ServerCharacterPredictionSystem - Received too much input from EntityRef{id = 89329, netId = 1955, prefab = 'engine:player'}, dropping input.
16:56:11.157 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
        at org.terasology.logic.characters.ServerCharacterPredictionSystem.update(ServerCharacterPredictionSystem.java:161)
        at org.terasology.engine.modes.StateIngame.update(StateIngame.java:176)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369)
        at org.terasology.engine.Terasology.main(Terasology.java:139)
16:56:11.158 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
16:56:14.667 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
16:56:14.670 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
16:56:14.684 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
16:56:14.721 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Xt
16:56:14.724 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: rzats
16:56:14.724 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: rzats
16:56:14.724 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: tdgunes
16:56:14.725 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Cervator
16:56:14.725 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: manu
16:56:14.727 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
16:56:19.714 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
16:56:19.986 [main] WARN  o.t.rendering.nui.skin.UISkinFormat - Failed to resolve UIWidget class UIInputBindButton, skipping style information
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
        at org.terasology.logic.characters.ServerCharacterPredictionSystem.update(ServerCharacterPredictionSystem.java:161)
        at org.terasology.engine.modes.StateIngame.update(StateIngame.java:176)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:414)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369)
        at org.terasology.engine.Terasology.main(Terasology.java:139)
For more details, see the log files in /opt/terasology/logs/2016-06-18_16-25-23
```

Edit: Immortius suggested the area simply hasn't been prepared well enough for thread-safety, which would make this a pretty likely outcome.
##

**Comment by Cervator** [comment]
Crash also happened during today's test. Coincidentally also while testing DynamicCities - but that's *probably* not related.

**Comment by xrtariq2594** [comment]
Hmmm, I wasn't there. But, I think it may be something to do with thread safety. It doesn't have to do with multijumping, as I fixed that issue.

**Comment by Cervator** [comment]
Yep it just seems to happen from time to time with enough player movement. That area just needs work :-)

**Comment by Cervator** [comment]
Closing this as likely obsolete
