### ISSUE TITLE
Previewing an unsupported world breaks world preview for remainder of game session

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2429]
Or at least the menu session. To reproduce:
- Verify that with default config (Core + Perlin) you can click the Details... button on Create Game and look at a world preview.
- Go back and pick HeightMap world instead, click the button again, get exception (pasted below)
- Select Perlin again which worked fine before - clicking the Details... button now causes the same exception
- Can also be done with other worlds like Island World from the PolyWorld module

Exception:

```
21:22:13.129 [main] ERROR o.t.r.n.l.mainMenu.CreateGameScreen - Unable to load world for a 2D preview
java.lang.NullPointerException: null
    at org.terasology.rendering.nui.layers.mainMenu.PreviewWorldScreen.setEnvironment(PreviewWorldScreen.java:117)
    at org.terasology.rendering.nui.layers.mainMenu.CreateGameScreen.lambda$initialise$152(CreateGameScreen.java:280)
    at org.terasology.rendering.nui.layers.mainMenu.CreateGameScreen$$Lambda$132/1613332278.onActivated(Unknown Source)
    at org.terasology.rendering.nui.widgets.UIButton.activate(UIButton.java:133)
    at org.terasology.rendering.nui.widgets.UIButton.access$100(UIButton.java:40)
    at org.terasology.rendering.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:77)
    at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:247)
    at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:569)
    at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
    at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
    at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279)
    at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258)
    at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
    at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:503)
    at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:324)
    at org.terasology.input.InputSystem.update(InputSystem.java:271)
    at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:143)
    at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:54)
    at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:422)
    at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
    at org.terasology.engine.Terasology.main(Terasology.java:150)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
21:22:17.083 [main] ERROR o.t.r.n.l.mainMenu.CreateGameScreen - Unable to load world for a 2D preview
java.lang.NullPointerException: null
    at org.terasology.rendering.nui.layers.mainMenu.PreviewWorldScreen.setEnvironment(PreviewWorldScreen.java:117)
...
```

(second exception is from the second try)

Maybe interesting to @msteiger and probably relates to the loaded context/environment. Not resetting correctly?
##

**Comment by 0shine0** [comment]
The problem was that all the variables of PreviewWorldScreen that had an @In above them were set to null because the screen was created every Details button was clicked.
It does not tackle issue #2509
Maybe you can test it for all test cases.
Gonna post a pr. Will link to it here
