### ISSUE TITLE
Aplication crashed when trying to load an old saved single player game

### ISSUE THREAD

**Issue by free2geo83** [MovingBlocks/Terasology#2459]
Description: Aplication crashed after trying to load an old saved single player game from a previous application version. In to the latest application's version. Note that after I save the single player game, I joined in to the multiplayer game mode from the same version,. then I quit the application and after the application's updates I was unable to load the old single player saved game

### How to reproduce:

Repro steps
 1 Start the application in the single player mode
 2 While in the single player mode save the current game
 3 Quit the application and relog
 4 Join a multiplayer game from a random server
5 Log out from the multiplayer game and close the application
6. Wait foar a new version of the application
6 Sstart the application in the Single Player mode
7. Load the old saved single player game

### Log details and game version
Game version: 66-alpha
Log file attached
[terasology_2016-08-27_20-23-45.153.txt](https://github.com/MovingBlocks/Terasology/files/440776/terasology_2016-08-27_20-23-45.153.txt)

### Computer details
Dxdiag attached
[DxDiag.txt](https://github.com/MovingBlocks/Terasology/files/440775/DxDiag.txt)

**Comment by Cervator** [comment]
Hi @free2geo83 and thanks for the detailed report :-)

Couple questions:

* Do you recall which older release you had saved the world in? If not exactly then maybe a rough time frame from when last you played - a month or more like a year?
* Can you confirm a world works fine if you do the listed steps *without* updating to a new version?

The odd thing is that the log indicates an error trying to apply some shader parameters which is more about graphics config than the saved world. Although I'm not sure if those may also save to the world in some way. I don't *think* so and am curious if the issue could be provoked without a change in version.

```
20:21:05.228 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.rendering.shader.ShaderParametersBase.applyParameters(ShaderParametersBase.java:44)
	at org.terasology.rendering.shader.ShaderParametersSSAO.applyParameters(ShaderParametersSSAO.java:92)
	at org.terasology.rendering.opengl.GLSLMaterial.enable(GLSLMaterial.java:108)
	at org.terasology.rendering.opengl.GLSLMaterial.restoreStateAfterUniformsSet(GLSLMaterial.java:617)
	at org.terasology.rendering.opengl.GLSLMaterial.setFloat3(GLSLMaterial.java:408)
	at org.terasology.rendering.assets.material.BaseMaterial.setFloat3(BaseMaterial.java:150)
	at org.terasology.rendering.shader.ShaderParametersSSAO.initialParameters(ShaderParametersSSAO.java:87)
	at org.terasology.rendering.opengl.GLSLMaterial.setShaderParameters(GLSLMaterial.java:93)
	at org.terasology.rendering.ShaderManagerLwjgl.prepareAndStoreShaderProgramInstance(ShaderManagerLwjgl.java:177)
	at org.terasology.rendering.ShaderManagerLwjgl.initShaders(ShaderManagerLwjgl.java:114)
	at org.terasology.rendering.world.WorldRendererImpl.initRenderingSupport(WorldRendererImpl.java:188)
	at org.terasology.rendering.world.WorldRendererImpl.<init>(WorldRendererImpl.java:175)
	at org.terasology.engine.subsystem.lwjgl.LwjglRenderingSubsystemFactory.createWorldRenderer(LwjglRenderingSubsystemFactory.java:33)
	at org.terasology.engine.modes.loadProcesses.InitialiseWorld.step(InitialiseWorld.java:153)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:150)
20:21:05.229 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by emanuele3d** [comment]
Preliminary finding, it appears the offending line is:

`program.setFloat("viewingDistance", CoreRegistry.get(Config.class).getRendering().getViewDistance().getChunkDistance().x * 8.0f, true);`

Lots of things could be null in there...

The good news is that ShaderParameters are slated for an overhaul. The bad news is that it might take a while. :disappointed:

**Comment by free2geo83** [comment]
It seems that it works. Today I tried again to re-load the old saved game from the single player mode and it works without encountering any issue.
So ... this is wired, because I don't know wat's the cause.
Yesterday after finishing the update for the latest version it crashes, and today it works without any issue.
Regardless the previous question "A time frame from when last you played":
I save the single player game about a month ago.

**Comment by Cervator** [comment]
@free2geo83: we could be looking at two issues mixed together. There were a couple changes to how view distance is configured lately, including one that affected `config.cfg` requiring a reset of that config file before the game would behave again. That's independent of a *world* save (`config.cfg` is global) though. But maybe something you did corrected the config file and that helped the older save work again?

@emanuele3d: I wonder if we should try to harden the reading of config values to give it a fallback if the retrieval from CoreRegistry fails (and log a warning). That could be a good practice in general and independent of a ShaderParameters overhaul. In this specific case my IDE is highlighting the `getRendering()` as possibly resulting in an NPE for some reason.

**Comment by skaldarnar** [comment]
Related to https://github.com/MovingBlocks/Terasology/issues/4628
