### ISSUE TITLE
Crash when Characters die from fall damage during server prediction

### ISSUE THREAD

**Issue by kaen** [MovingBlocks/Terasology#2469]
### What you were trying to do

Move a deer with high movement speed off a cliff

### What actually happened

Server crashes with ConcurrentModificationException, similar to (but distinct from) #2468 since it's a different collection and the event is dispatch from the `update` method of a component system rather than a BT Node.

### How to reproduce

Kill a (non-player) character with fall damage (via CharacterMoveInputEvent).

### Log details and game version
```
"main@1" prio=10 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.terasology.logic.characters.ServerCharacterPredictionSystem.onDestroy(ServerCharacterPredictionSystem.java:97)
	  at org.terasology.logic.characters.ServerCharacterPredictionSystemMethodAccess.invoke(Unknown Source:-1)
	  at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	  at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	  at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	  at org.terasology.entitySystem.entity.internal.PojoEntityManager.destroy(PojoEntityManager.java:538)
	  at org.terasology.entitySystem.entity.internal.BaseEntityRef.destroy(BaseEntityRef.java:138)
	  at org.terasology.logic.health.EntityDestructionAuthoritySystem.onDestroy(EntityDestructionAuthoritySystem.java:32)
	  at org.terasology.logic.health.EntityDestructionAuthoritySystemMethodAccess.invoke(Unknown Source:-1)
	  at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	  at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	  at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	  at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	  at org.terasology.logic.health.HealthAuthoritySystem.doDamage(HealthAuthoritySystem.java:185)
	  at org.terasology.logic.health.HealthAuthoritySystem.checkDamage(HealthAuthoritySystem.java:200)
	  at org.terasology.logic.health.HealthAuthoritySystem.onLand(HealthAuthoritySystem.java:241)
	  at org.terasology.logic.health.HealthAuthoritySystemMethodAccess.invoke(Unknown Source:-1)
	  at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	  at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	  at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	  at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	  at org.terasology.logic.characters.KinematicCharacterMover.walk(KinematicCharacterMover.java:647)
	  at org.terasology.logic.characters.KinematicCharacterMover.updatePosition(KinematicCharacterMover.java:559)
	  at org.terasology.logic.characters.KinematicCharacterMover.step(KinematicCharacterMover.java:103)
	  at org.terasology.logic.characters.ServerCharacterPredictionSystem.stepState(ServerCharacterPredictionSystem.java:168)
	  at org.terasology.logic.characters.ServerCharacterPredictionSystem.onPlayerInput(ServerCharacterPredictionSystem.java:126)
	  at org.terasology.logic.characters.ServerCharacterPredictionSystemMethodAccess.invoke(Unknown Source:-1)
	  at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	  at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	  at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	  at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	  at org.terasology.flexiblemovement.FlexibleMovementSystem.update(FlexibleMovementSystem.java:37)
	  at org.terasology.engine.modes.StateIngame.update(StateIngame.java:176)
	  at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	  at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	  - locked <0x1906> (a org.terasology.engine.TerasologyEngine)
	  at org.terasology.engine.Terasology.main(Terasology.java:152)
```

**Comment by Elyahu41** [comment]
I looked into this issue and from what I can tell the "ConcurrentModificationException" is being thrown because the deer and the player are in the same hash map called "characterStates", which is in the "ServerCharacterPredictionSystem" class. One thread is using the hash map for the player while the other is deleting the deer.

Possible fixes:

1. Put a synchronized block in the update method in the "ServerCharacterPredictionSystem" class.
Not Recommended, but confirmed to be a working solution through my testing.

2. Change the "characterStates" hash map to a concurrentMap which is thread safe.
Also tested to be a confirmed fix through my testing. Not sure about the performance difference, but it shouldn't be much.
I'm still trying to write a test to see the performance difference.

3. @Cervator mentioned that we could perhaps wait a tick to delete the deer. I'm not sure about this because I think the class iterates through the hash map 60 times every second. It might also cause issues with some other code relying on the player being somewhere.
That's my 2 cents, but let me know if I am mistaken.

Out of all 3 choices, I would say that number 2 would be the best option, but I need guidance to know for sure. Any help is appreciated.

**Comment by Cervator** [comment]
So I ran this in debug mode and successfully caught the exception with a break point. For anybody curious for an easy way to replicate: I spotted a tall tree near spawn, flew up there, `spawnPrefab deer`, then started chopping leaf blocks below the deer till it fell off. Poor deer.

@Elyahu41 apologies if I'm about to write up the exact thing you already did, unsure 😅 I'm also not 100% sure this is correct since I rarely get to actually delve deeper in the code these days.

As often is the case with `ConcurrentModificationException` it is actually _not_ a threading issue at all.

If you look at `ServerCharacterPredictionSystem.update` then we iterate through `characterStates` in a loop which is handled by the main game thread. For each entity you replay their last input. In the case of the deer that then caused its death, meaning as part of that input event handling the main thread ends up in `onDestroy` _also_ inside `ServerCharacterPredictionSystem` where the destroy method removes an entry from `characterStates` _concurrently_ with the loop going through the same Map - Collections don't like that.

Synchronizing or using a concurrent map gets around the issue, but at a cost (synchronization is generally considered expensive, plus opens the risk of deadlocks). There are other options as this is a pretty common issue. See https://www.baeldung.com/java-concurrentmodificationexception for some more on the topic and several solutions.

I like the `3.2` option, which is what I had in mind by waiting to remove entities (by "next tick" I just meant literally next game frame, not a full second or anything). A quick conceptual way to do that would be "For each entity removed during the processing of the for loop put it into a different Collection, then continue iterating, and after the loop finishes go remove all those entities". Another typical fix is `3.1` which also uses a different collection, but instead of one aiming for thread safety (expensive) it just iterates and removes in a more safe fashion - _but_ that assumes the removal happens directly inside that loop, which it doesn't (it calls out to event handling which comes in through a side door indirectly and later hits the active collection)

So! That brings me to two thoughts:

1) Should server prediction even _predict removals_ in the first place? I really don't know, but I remember from other games that lag prediction at least sometimes did not actually cover removal of things. If you did actually lag then a creature would just kinda keep sliding in some direction till the server caught up and broadcast the death. I guess this might be done for :reasons: perhaps this exact problem? A predicted death could "leak" to a player what might happen next - loot drops? It actually wasn't its final form and it just grows stronger? You could conceivably lag yourself on purpose to see what prediction would reveal.

2) In `onDestroy` rather than remove the entity should it be added to a class level collection, that at the end of the loop in `update` we then go ahead and all remove at the same time? Trouble here is stuff like: is that method ever executed _not_ from the event stream that comes out of the `update` method there? Or is there an impact later in the loop if a dead deer isn't removed? 🤔 

My concern with option 1 (seeing past a removal) is probably just me being silly, I dunno. It might be worth trying to fix it via option 2 while leaving in place a TODO considering whether or not removal should truly be part of prediction. We could try to discuss that elsewhere but the prediction system has been untouched for years so I'm not sure anybody would be able to participate 🤷
