### ISSUE TITLE
Certain kinds of explosive/railgun spam can cause math errors (and need a cooldown anyway)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2597]
At first I thought this might be a consequence of #2582 but it *may* just have changed the cooldown mechanics slightly to make it easier to replicate. Or it didn't at all and probabilities just made it appear as such. I was able to replicate with a binary Omega 583 (two days old) after several rounds of effort.

I can cause this issue with either the explode tool or the railgun, but the exact conditions elude me. It has something to do with causing rapid chunk changes like exploding your surroundings at maximum speed with the lack of a sensible cooldown on either item that makes things go boom. Or reappearing after dying far away.

Most reliably I can railgun myself directly into the ground for 10-20 seconds or longer (which itself is amazing - if you eventually die as the railgun fails to keep up you can wait on the death screen and just see the continuing rain of blocks catch up) then on dying and respawning the error can occur, maybe after I attempt to move, but before anything actually renders (you may need to have dug a shaft deep enough to where you've fallen out of range of spawn so its chunk unloads)

Alternatively using the explodeTool with the right mouse held down while connected to a headless server also triggered it somewhat reliably.

Interestingly @Feralmouse reported an error with the exact (or nearly exact) stacktrace just a day or two ago. In his case I'm not entirely sure how it was triggered, but it was the exact same "input is infinite or NaN" coming from an `OpaqueObjectsNode` stack. Maybe he can provide more details or attempt to replicate again.

Maybe interesting to @Josharias or @emanuele3d. Not sure if it counts more as world/architecture or 3d wizardry. May not actually be a reasonable bug (should the player really be able to railgun a tunnel to the core of the earth with no effective cooldown, falling at terminal velocity the whole time?) but perhaps we can harden the engine to where if math stops making sense ... well, maybe try to recover somehow?

Finally: After figuring out a solution to this we *really* should add a more sensible cooldown to the boom sticks. Great for debugging obscure errors, perhaps, but even a *small* cooldown beyond the current may be advisable ... :-) I'm not entirely sure if the 200ms `cooldownTime` in `ItemComponent` is actually respected or if the explodey manages to escape it somehow.

## Logs

First provoked while connected to a headless server by holding down right mouse with the explodeTool (no cooldown? too short?). No death or respawn connected, just blocks went poof then game went poof.

```
00:43:31.760 [main] INFO  o.t.r.dag.RenderTaskListGenerator - Task list generated in 6.602 ms
00:43:31.760 [main] INFO  o.t.r.dag.RenderTaskListGenerator - 30 nodes, 28 enabled - 93 tasks (excluding marker tasks) out of 124 potential tasks.
00:43:31.760 [main] INFO  o.t.r.dag.RenderTaskListGenerator - ----------------------------------------------------------
00:43:32.101 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'emptyIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UIIconBar","id":"breathBar","icon":"engine:icons#bubble","family":"breathBar","emptyIcon":"engine:icons#burstBubble","halfIconMode":"shrink","spacing":2,"maxIcons":10,"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-left":{"target":"CENTER"},"position-right":{"target":"RIGHT","widget":"healthBar"},"position-bottom":{"target":"TOP","widget":"healthBar","offset":1}}}
00:43:32.102 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'crosshairIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UICrosshair","id":"crosshair","crosshairIcon":"engine:gui#crosshair","layoutInfo":{"use-content-width":true,"use-content-height":true,"position-horizontal-center":{},"position-vertical-center":{}}}
00:43:32.160 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'crosshairIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UICrosshair","id":"crosshair","crosshairIcon":"engine:gui#crosshair","chargeStages":["engine:gui#crosshairCharge1","engine:gui#crosshairCharge2","engine:gui#crosshairCharge3","engine:gui#crosshairCharge4","engine:gui#crosshairCharge5","engine:gui#crosshairCharge6","engine:gui#crosshairCharge7","engine:gui#crosshairCharge8"],"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-horizontal-center":{},"position-vertical-center":{}}}
00:43:32.421 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 398, netId = 398, prefab = 'engine:blockItemBase'}
00:43:32.455 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 383, netId = 383, prefab = 'engine:blockItemBase'}
00:43:32.470 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 362, netId = 362, prefab = 'engine:blockItemBase'}
00:43:32.477 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 349, netId = 349, prefab = 'engine:blockItemBase'}
00:43:32.480 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 334, netId = 334, prefab = 'engine:blockItemBase'}
00:43:32.485 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 317, netId = 317, prefab = 'engine:blockItemBase'}
00:43:32.500 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 296, netId = 296, prefab = 'engine:blockItemBase'}
00:43:32.505 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 281, netId = 281, prefab = 'engine:blockItemBase'}
00:43:32.512 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 260, netId = 260, prefab = 'engine:blockItemBase'}
00:43:32.516 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 251, netId = 251, prefab = 'engine:blockItemBase'}
00:43:32.531 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 212, netId = 212, prefab = 'engine:blockItemBase'}
00:43:32.537 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 205, netId = 205, prefab = 'engine:blockItemBase'}
00:43:32.549 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 180, netId = 180, prefab = 'engine:blockItemBase'}
00:43:32.553 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 167, netId = 167, prefab = 'engine:blockItemBase'}
00:43:32.558 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 146, netId = 146, prefab = 'engine:blockItemBase'}
00:43:33.229 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 131, netId = 131, prefab = 'engine:blockItemBase'}
00:43:33.234 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 110, netId = 110, prefab = 'engine:blockItemBase'}
00:43:33.239 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 97, netId = 97, prefab = 'engine:blockItemBase'}
00:43:33.241 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 84, netId = 84, prefab = 'engine:blockItemBase'}
00:43:33.244 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 59, netId = 59, prefab = 'engine:blockItemBase'}
00:43:33.350 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1155), capping to 1000
00:43:42.874 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 579, netId = 449}
00:43:43.210 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 592, netId = 452}
00:43:45.538 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 614, netId = 464}
00:43:46.278 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 658, netId = 481}
00:43:46.684 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 640, netId = 476}
00:43:47.140 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 628, netId = 469}
00:43:49.377 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 724, netId = 515}
00:43:50.181 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 688, netId = 497}
00:43:50.370 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 710, netId = 508}
00:43:51.480 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 772, netId = 538}
00:43:52.622 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 752, netId = 529}
00:43:55.626 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 978, netId = 540, prefab = 'engine:blockItemBase'}
00:43:58.894 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 1355, netId = 558}
00:43:58.895 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 1342, netId = 555}
00:43:58.895 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 1320, netId = 552}
00:43:59.132 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.ArithmeticException: input is infinite or NaN
	at com.google.common.math.DoubleMath.roundIntermediate(DoubleMath.java:59)
	at com.google.common.math.DoubleMath.roundToInt(DoubleMath.java:132)
	at org.terasology.math.geom.Vector3i.<init>(Vector3i.java:87)
	at org.terasology.world.internal.WorldProviderWrapper.isBlockRelevant(WorldProviderWrapper.java:47)
	at org.terasology.rendering.logic.MeshRenderer.isRelevant(MeshRenderer.java:257)
	at org.terasology.rendering.logic.MeshRenderer.renderEntitiesByMaterial(MeshRenderer.java:194)
	at org.terasology.rendering.logic.MeshRenderer.renderEntities(MeshRenderer.java:166)
	at org.terasology.rendering.logic.MeshRenderer.renderAlphaBlend(MeshRenderer.java:144)
	at org.terasology.rendering.dag.nodes.SimpleBlendMaterialsNode.process(SimpleBlendMaterialsNode.java:78)
	at org.terasology.rendering.dag.NodeTask.execute(NodeTask.java:30)
	at org.terasology.rendering.world.WorldRendererImpl$$Lambda$230/1457157255.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.terasology.rendering.world.WorldRendererImpl.render(WorldRendererImpl.java:444)
	at org.terasology.engine.modes.StateIngame.render(StateIngame.java:209)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:190)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:422)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
00:43:59.133 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
00:43:59.180 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
00:44:04.862 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'emptyIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UIIconBar","id":"breathBar","icon":"engine:icons#bubble","family":"breathBar","emptyIcon":"engine:icons#burstBubble","halfIconMode":"shrink","spacing":2,"maxIcons":10,"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-left":{"target":"CENTER"},"position-right":{"target":"RIGHT","widget":"healthBar"},"position-bottom":{"target":"TOP","widget":"healthBar","offset":1}}}
00:44:04.863 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'crosshairIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UICrosshair","id":"crosshair","crosshairIcon":"engine:gui#crosshair","layoutInfo":{"use-content-width":true,"use-content-height":true,"position-horizontal-center":{},"position-vertical-center":{}}}
00:44:05.027 [main] WARN  o.t.rendering.nui.skin.UISkinFormat - Failed to resolve UIWidget class UIInputBindButton, skipping style information
java.lang.ArithmeticException: input is infinite or NaN
	at com.google.common.math.DoubleMath.roundIntermediate(DoubleMath.java:59)
	at com.google.common.math.DoubleMath.roundToInt(DoubleMath.java:132)
	at org.terasology.math.geom.Vector3i.<init>(Vector3i.java:87)
	at org.terasology.world.internal.WorldProviderWrapper.isBlockRelevant(WorldProviderWrapper.java:47)
	at org.terasology.rendering.logic.MeshRenderer.isRelevant(MeshRenderer.java:257)
	at org.terasology.rendering.logic.MeshRenderer.renderEntitiesByMaterial(MeshRenderer.java:194)
	at org.terasology.rendering.logic.MeshRenderer.renderEntities(MeshRenderer.java:166)
	at org.terasology.rendering.logic.MeshRenderer.renderAlphaBlend(MeshRenderer.java:144)
	at org.terasology.rendering.dag.nodes.SimpleBlendMaterialsNode.process(SimpleBlendMaterialsNode.java:78)
	at org.terasology.rendering.dag.NodeTask.execute(NodeTask.java:30)
	at org.terasology.rendering.world.WorldRendererImpl$$Lambda$230/1457157255.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.terasology.rendering.world.WorldRendererImpl.render(WorldRendererImpl.java:444)
	at org.terasology.engine.modes.StateIngame.render(StateIngame.java:209)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:190)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:422)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
For more details, see the log files in J:\Dev\Terasology\Git\integrate\Terasology\logs\2016-11-07_00-42-39
```

Same thing in single player, although it took a lot of spamming railgun while falling right down to provoke it (possibly after respawning?)

```
00:48:41.861 [Chunk-Generator-0] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:RedLeaf with id 56
00:49:22.792 [Timer-0] WARN  o.t.r.logic.NearestSortingList - Entities destroyed during sorting process. Sorting is skipped this round.
00:49:22.849 [Timer-0] WARN  o.t.r.logic.NearestSortingList - Entities destroyed during sorting process. Sorting is skipped this round.
00:49:22.892 [Timer-0] WARN  o.t.r.logic.NearestSortingList - Entities destroyed during sorting process. Sorting is skipped this round.
00:49:22.942 [Timer-0] WARN  o.t.r.logic.NearestSortingList - Entities destroyed during sorting process. Sorting is skipped this round.
00:49:22.992 [Timer-0] WARN  o.t.r.logic.NearestSortingList - The commands list was not emptied properly!
00:49:23.382 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.ArithmeticException: input is infinite or NaN
	at com.google.common.math.DoubleMath.roundIntermediate(DoubleMath.java:59)
	at com.google.common.math.DoubleMath.roundToInt(DoubleMath.java:132)
	at org.terasology.math.geom.Vector3i.<init>(Vector3i.java:87)
	at org.terasology.world.internal.WorldProviderWrapper.isBlockRelevant(WorldProviderWrapper.java:47)
	at org.terasology.rendering.logic.MeshRenderer.isRelevant(MeshRenderer.java:257)
	at org.terasology.rendering.logic.MeshRenderer.renderEntitiesByMaterial(MeshRenderer.java:194)
	at org.terasology.rendering.logic.MeshRenderer.renderEntities(MeshRenderer.java:166)
	at org.terasology.rendering.logic.MeshRenderer.renderOpaque(MeshRenderer.java:152)
	at org.terasology.rendering.dag.nodes.OpaqueObjectsNode.process(OpaqueObjectsNode.java:68)
	at org.terasology.rendering.dag.NodeTask.execute(NodeTask.java:30)
	at org.terasology.rendering.world.WorldRendererImpl$$Lambda$253/159651486.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.terasology.rendering.world.WorldRendererImpl.render(WorldRendererImpl.java:444)
	at org.terasology.engine.modes.StateIngame.render(StateIngame.java:209)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:190)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:422)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
00:49:23.389 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
00:49:23.541 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
00:49:23.565 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
00:49:23.588 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Cervator
00:49:23.602 [main] INFO  o.t.logic.console.ConsoleImpl - [NOTIFICATION] Player "Cervator" has left the game
00:49:23.605 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
00:49:24.458 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
00:49:29.602 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'emptyIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UIIconBar","id":"breathBar","icon":"engine:icons#bubble","family":"breathBar","emptyIcon":"engine:icons#burstBubble","halfIconMode":"shrink","spacing":2,"maxIcons":10,"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-left":{"target":"CENTER"},"position-right":{"target":"RIGHT","widget":"healthBar"},"position-bottom":{"target":"TOP","widget":"healthBar","offset":1}}}
00:49:29.605 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'crosshairIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UICrosshair","id":"crosshair","crosshairIcon":"engine:gui#crosshair","layoutInfo":{"use-content-width":true,"use-content-height":true,"position-horizontal-center":{},"position-vertical-center":{}}}
00:49:29.773 [main] WARN  o.t.rendering.nui.skin.UISkinFormat - Failed to resolve UIWidget class UIInputBindButton, skipping style information
java.lang.ArithmeticException: input is infinite or NaN
	at com.google.common.math.DoubleMath.roundIntermediate(DoubleMath.java:59)
	at com.google.common.math.DoubleMath.roundToInt(DoubleMath.java:132)
	at org.terasology.math.geom.Vector3i.<init>(Vector3i.java:87)
	at org.terasology.world.internal.WorldProviderWrapper.isBlockRelevant(WorldProviderWrapper.java:47)
	at org.terasology.rendering.logic.MeshRenderer.isRelevant(MeshRenderer.java:257)
	at org.terasology.rendering.logic.MeshRenderer.renderEntitiesByMaterial(MeshRenderer.java:194)
	at org.terasology.rendering.logic.MeshRenderer.renderEntities(MeshRenderer.java:166)
	at org.terasology.rendering.logic.MeshRenderer.renderOpaque(MeshRenderer.java:152)
	at org.terasology.rendering.dag.nodes.OpaqueObjectsNode.process(OpaqueObjectsNode.java:68)
	at org.terasology.rendering.dag.NodeTask.execute(NodeTask.java:30)
	at org.terasology.rendering.world.WorldRendererImpl$$Lambda$253/159651486.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.terasology.rendering.world.WorldRendererImpl.render(WorldRendererImpl.java:444)
	at org.terasology.engine.modes.StateIngame.render(StateIngame.java:209)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:190)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:422)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
For more details, see the log files in J:\Dev\Terasology\Git\integrate\Terasology\logs\2016-11-07_00-47-49
```

**Comment by Cervator** [comment]
Found another way to provoke this, not sure if easier or harder to reproduce. Joined the unstable Docker server (which seems to get sort of server-side laggy so actions take a bit longer) and simply started jumping up at a tree while bashing leaf blocks. After several jumps and maybe ten blocks broken boom:

```
00:43:06.231 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 5510, netId = 3890, prefab = 'ManualLabor:Stick'}
00:43:06.601 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.ArithmeticException: input is infinite or NaN
	at com.google.common.math.DoubleMath.roundIntermediate(DoubleMath.java:59)
	at com.google.common.math.DoubleMath.roundToInt(DoubleMath.java:132)
	at org.terasology.math.geom.Vector3i.<init>(Vector3i.java:87)
	at org.terasology.world.internal.WorldProviderWrapper.isBlockRelevant(WorldProviderWrapper.java:47)
	at org.terasology.rendering.logic.MeshRenderer.isRelevant(MeshRenderer.java:257)
	at org.terasology.rendering.logic.MeshRenderer.renderEntitiesByMaterial(MeshRenderer.java:194)
	at org.terasology.rendering.logic.MeshRenderer.renderEntities(MeshRenderer.java:166)
	at org.terasology.rendering.logic.MeshRenderer.renderOpaque(MeshRenderer.java:152)
	at org.terasology.rendering.dag.nodes.OpaqueObjectsNode.process(OpaqueObjectsNode.java:68)
	at org.terasology.rendering.dag.NodeTask.execute(NodeTask.java:30)
	at org.terasology.rendering.world.WorldRendererImpl$$Lambda$242/2058228080.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.terasology.rendering.world.WorldRendererImpl.render(WorldRendererImpl.java:444)
	at org.terasology.engine.modes.StateIngame.render(StateIngame.java:209)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:190)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:422)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
00:43:06.601 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by pollend** [comment]
That happens when you save nan to a location component.

**Comment by Cervator** [comment]
Still a live issue - just happened during play test. Was digging around a mine field but there were also multiple carts rushing around rail tracks and such.

```
17:12:02.839 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 739830, netId = 9931, prefab = 'engine:blockItemBase'}
17:12:03.189 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 739930, netId = 9933, prefab = 'engine:blockItemBase'}
17:12:03.739 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 750628, netId = 10102}
17:12:05.051 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.ArithmeticException: input is infinite or NaN
	at com.google.common.math.DoubleMath.roundIntermediate(DoubleMath.java:59)
	at com.google.common.math.DoubleMath.roundToInt(DoubleMath.java:132)
	at org.terasology.math.geom.Vector3i.<init>(Vector3i.java:87)
	at org.terasology.world.internal.WorldProviderWrapper.isBlockRelevant(WorldProviderWrapper.java:47)
	at org.terasology.rendering.logic.MeshRenderer.isRelevant(MeshRenderer.java:257)
	at org.terasology.rendering.logic.MeshRenderer.renderEntitiesByMaterial(MeshRenderer.java:194)
	at org.terasology.rendering.logic.MeshRenderer.renderEntities(MeshRenderer.java:166)
	at org.terasology.rendering.logic.MeshRenderer.renderOpaque(MeshRenderer.java:152)
	at org.terasology.rendering.dag.nodes.OpaqueObjectsNode.process(OpaqueObjectsNode.java:83)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.terasology.rendering.world.WorldRendererImpl.render(WorldRendererImpl.java:597)
	at org.terasology.engine.modes.StateIngame.render(StateIngame.java:210)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:189)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:446)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:400)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:376)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
17:12:05.052 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by skaldarnar** [comment]
We switched to JOML in the meantime, so I think most of these old math-related issues are outdated by now.
