### ISSUE TITLE
Starting game with wireframe mode left enabled causes a crash

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2608]
Didn't notice this while testing #2595 but exited the game with wireframe still active (`F3` then `F9`) then the next time I tried to load the game / start a new world I crashed. That's a pretty rare scenario to encounter anyway - those alternative modes rarely get used and even more rarely are left active when leaving the game then restarting.

One for @emanuele3d to look at I expect :-) I don't know if it is specific to wireframe or other modes left enabled might cause weird node states or something.

Easy enough to just delete `config.cfg` if the mode is enabled (so you can't get in-game and disable it again)

Crash log:

```
01:52:54.532 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.rendering.dag.AbstractNode.refreshTaskList(AbstractNode.java:83)
	at org.terasology.rendering.dag.nodes.BackdropNode.enableWireframe(BackdropNode.java:96)
	at org.terasology.rendering.dag.WireframeTrigger.<init>(WireframeTrigger.java:46)
	at org.terasology.rendering.dag.nodes.BackdropNode.initialise(BackdropNode.java:75)
	at org.terasology.rendering.dag.NodeFactory.createInstance(NodeFactory.java:44)
	at org.terasology.rendering.dag.NodeFactory.createInstance(NodeFactory.java:35)
	at org.terasology.rendering.world.WorldRendererImpl.initRenderGraph(WorldRendererImpl.java:257)
	at org.terasology.rendering.world.WorldRendererImpl.initRenderingSupport(WorldRendererImpl.java:209)
	at org.terasology.rendering.world.WorldRendererImpl.<init>(WorldRendererImpl.java:188)
	at org.terasology.engine.subsystem.lwjgl.LwjglRenderingSubsystemFactory.createWorldRenderer(LwjglRenderingSubsystemFactory.java:33)
	at org.terasology.engine.modes.loadProcesses.InitialiseWorld.step(InitialiseWorld.java:153)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
01:52:54.532 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by emanuele3d** [comment]
Was able to reproduce. Hopefully fixed in #2609.
