### ISSUE TITLE
NPE crashing client on attempting to join headless server running MedievalCities

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2628]
While setting up a test server to check out MedievalCities I found that upon attempting to join the seemingly working server I would crash with a failure to get a working `delayManager` in `BlockBufferSystem` from `DynamicCities`

Wondering if this was due to #2336 I tried to switch it around to where I attempted to get the `delayManager` from the `CoreRegistry` instead but no luck, still just got null back.

Logs:

```
16:32:34.894 [main] WARN  o.t.rendering.nui.asset.UIFormat - Field 'crosshairIcon' not recognized for interface org.terasology.rendering.nui.UIWidget in {"type":"UICrosshair","id":"crosshair","crosshairIcon":"engine:gui#crosshair","chargeStages":["engine:gui#crosshairCharge1","engine:gui#crosshairCharge2","engine:gui#crosshairCharge3","engine:gui#crosshairCharge4","engine:gui#crosshairCharge5","engine:gui#crosshairCharge6","engine:gui#crosshairCharge7","engine:gui#crosshairCharge8"],"layoutInfo":{"use-content-width":true,"use-content-height":true,"position-horizontal-center":{},"position-vertical-center":{}}}
16:32:35.147 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.dynamicCities.construction.BlockBufferSystem.postBegin(BlockBufferSystem.java:81)
	at org.terasology.engine.modes.loadProcesses.PostBeginSystems.step(PostBeginSystems.java:44)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
16:32:35.148 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

Game did not dispose and in fact didn't seem to lose its connection with the server (?!?). On killing the game the server reported:

```
16:35:03.087 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
16:35:04.642 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
16:35:14.767 [main] INFO  o.t.d.construction.BlockBufferSystem - Buffer before: 245, Placed: 245, Removed: 245, Buffer after: 0
16:35:16.767 [main] INFO  o.t.d.construction.BlockBufferSystem - Buffer before: 565, Placed: 565, Removed: 565, Buffer after: 0
16:35:37.772 [main] INFO  o.t.d.construction.BlockBufferSystem - Buffer before: 565, Placed: 565, Removed: 565, Buffer after: 0
16:35:41.773 [main] INFO  o.t.d.construction.BlockBufferSystem - Buffer before: 565, Placed: 565, Removed: 565, Buffer after: 0
16:35:56.378 [New I/O worker #2] WARN  o.t.network.internal.ServerHandler - Unexpected exception from client
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
16:35:56.382 [New I/O worker #2] WARN  o.t.network.internal.ServerHandler - Unexpected exception from client
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
```

So that's also a sort of interesting disposal issue.

Related snippet of code with extra logging and the `CoreRegistry` hack attempted:

```java
        logger.info("In postBegin, delay manager is {} and blockBufferEntity {}", delayManager, blockBufferEntity);
        delayManager = CoreRegistry.get(DelayManager.class);
        logger.info("In postBegin, now delay manager is {} and blockBufferEntity {}", delayManager, blockBufferEntity);
        delayManager.addPeriodicAction(blockBufferEntity, PLACE_BLOCKS_ACTION_ID, 1000, 1000); // Boom, NPE on delayManager
```

**Comment by Cervator** [comment]
I managed to fix this, huzzah! 

https://github.com/Terasology/DynamicCities/commit/7fcd9a9d8faa16753919aa692ad16901c8ae7dad

Pinging @skaldarnar and @CptCrispyCrunchy for reference.
