### ISSUE TITLE
An error occurred while executing command 'showScreen': java.lang.NullPointerException

### ISSUE THREAD

**Issue by gkaretka** [MovingBlocks/Terasology#2643]
### What you were trying to do
I was trying to create new `NUI` module for GCI.

### What actually happened

New UI screen wasn't shown.

### How to reproduce

1. When I fetch `TutorialNui` (`gradlew fetchModuleTutorialNui`)
2. start game (`gradlew game`)
3. In menu select single player, create new Game enabling `TutorialNui` module
4. Open console (`F1`) and type `showScreen EnvironmentInfoScreen`

Then output is : `An error occurred while executing command 'showScreen': java.lang.NullPointerException`

### Log details and game version
Built from latest source

`10:51:11.988 [main] ERROR o.t.rendering.nui.asset.UIFormat - Unknown UIWidget type EnvironmentInfoScreen
10:51:11.989 [main] ERROR o.t.logic.console.ConsoleImpl - An error occurred while executing a command
org.terasology.logic.console.commandSystem.exceptions.CommandExecutionException: java.lang.NullPointerException
        at org.terasology.logic.console.commandSystem.AbstractCommand.execute(AbstractCommand.java:242)
        at org.terasology.logic.console.ConsoleImpl.execute(ConsoleImpl.java:232)
        at org.terasology.logic.console.ConsoleImpl.execute(ConsoleImpl.java:196)
        at org.terasology.logic.console.ui.ConsoleScreen.lambda$initialise$0(ConsoleScreen.java:79)
        at org.terasology.rendering.nui.widgets.UIText.onKeyEvent(UIText.java:322)
        at org.terasology.logic.console.ui.UICommandEntry.onKeyEvent(UICommandEntry.java:83)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.keyEvent(NUIManagerInternal.java:604)
        at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
        at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258)
        at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
        at org.terasology.input.InputSystem.sendKeyEvent(InputSystem.java:475)
        at org.terasology.input.InputSystem.processKeyboardInput(InputSystem.java:425)
        at org.terasology.input.InputSystem.update(InputSystem.java:272)
        at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:179)
        at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:54)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:422)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
        at org.terasology.engine.Terasology.main(Terasology.java:152)
Caused by: java.lang.NullPointerException: null
        at org.terasology.rendering.nui.internal.NUIManernal.createScreen(NUIManagerInternal.java:273)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.createScreen(NUIManagerInternal.java:249)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:301)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:296)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:70)
        at org.terasology.logic.console.commands.CoreCommands.showScreen(CoreCommands.java:231)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.terasology.logic.console.commandSystem.AbstractCommand.execute(AbstractCommand.java:237)
        ... 19 common frames omitted
10:51:11.990 [main] INFO  o.t.logic.console.ConsoleImpl - [ERROR] An error occurred while executing command 'showScreen': java.lang.NullPointerException`

### Computer details
- Windows 10
- gpu: integrated
- `java -version` output:
`java version "1.8.0_111"                                                                                                Java(TM) SE Runtime` `Environment (build 1.8.0_111-b14)                                                                   Java HotSpot(TM) 64-Bit
Server VM (build 25.111-b14, mixed mode)`

**Comment by Cervator** [comment]
I double checked on this since it was listed as a Blocker, but believe it was likely a case of the module not having compiled fully - that will mean the asset wasn't available. I tried it just now and it worked fine :-)

Trying to ask for a non-existing screen resulted in graceful error return to the console rather than an NPE. I'm not sure if this is something we hardened since this issue was submitted, or if the conditions to replicate it are more quirky than expected (could a partial build make a screen asset available but a required class not?)

Not sure if there is any additional hardening we can apply, outside of just gradually improving the code base in general to better handle such issues. That's probably outside the scope of this issue though, and something we might raise again in the future when/if it becomes more relevant.

Going to close this for now - @gkaretka I hope you're doing well and still out there somewhere, if you see this and try it again with the same behavior let us know :-)
