### ISSUE TITLE
Non-fatal exception logged when dropping a blueberry as a multiplayer client

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2690]
Noticed this by chance while working on some unrelated testing. I would start up a host player running JoshariasSurvival and join in a pure client player 2. With the client I'd pick a blueberry and try to drop it with `q` - as far as I could tell everything worked and I could pick it up again, but the following got logged:

```java
23:08:07.845 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.IllegalArgumentException: Can only create a new rigid body for entities with a LocationComponent, RigidBodyComponent and ShapeComponent, this entity misses at least one: EntityRef{id = 393, netId = 963, prefab = 'JoshariasSurvival:Blueberry'}
	at org.terasology.physics.bullet.BulletPhysics.newRigidBody(BulletPhysics.java:537)
	at org.terasology.physics.bullet.BulletPhysics.getRigidBody(BulletPhysics.java:345)
	at org.terasology.physics.engine.PhysicsSystem.onImpulse(PhysicsSystem.java:107)
	at org.terasology.physics.engine.PhysicsSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.network.internal.ServerImpl.processEvent(ServerImpl.java:244)
	at org.terasology.network.internal.ServerImpl.processMessages(ServerImpl.java:276)
	at org.terasology.network.internal.ServerImpl.update(ServerImpl.java:187)
	at org.terasology.network.internal.NetworkSystemImpl.update(NetworkSystemImpl.java:317)
	at org.terasology.engine.subsystem.common.NetworkSubsystem.preUpdate(NetworkSubsystem.java:46)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:406)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
23:08:37.581 [main] INFO  o.t.network.internal.ServerImpl - Destroying entity: EntityRef{id = 393, netId = 963, prefab = 'JoshariasSurvival:Blueberry'}
```

This might be related to some of the recent quirks we've slowly been noticing in multiplayer, where not everything is synchronizing just right. So maybe a relation to #2629

I'm not worried about the impact of this, since there doesn't really appear to be one, but I find it an interesting clue. Maybe we can dig around and find out if the error occurs because some Component doesn't survive the multiplayer sync. It is a nice and easy scenario to replicate.

**Comment by skaldarnar** [comment]
Haven't seen this one for a while, closing as likely fixed.
