### ISSUE TITLE
Unusually severe crash from simply missing a comma in a prefab array declaration

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2693]
While testing a Cooking PR an item prefab had a missing comma between two array elements. Caused a full game crash that even failed to dispose the process - that seems kinda dramatic! Other JSON errors get caught and logged gracefully and just don't work.

To replicate just find some sort of prefab with an array in it, remove a comma between elements inside the `[ ... , ...]`

Error:

```
01:48:50.670 [main] ERROR org.terasology.assets.AssetType - Failed to load asset 'Cooking:Tongs'
java.io.IOException: Failed to load prefab
	at org.terasology.persistence.serializers.EntityDataJSONFormat.readPrefab(EntityDataJSONFormat.java:83)
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:51)
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:36)
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292)
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180)
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228)
	at org.terasology.assets.AssetType.lambda$reload$1(AssetType.java:356)
	at org.terasology.assets.AssetType$$Lambda$72/616207929.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.terasology.assets.AssetType.reload(AssetType.java:354)
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:383)
	at org.terasology.assets.AssetType.getAsset(AssetType.java:262)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:223)
	at org.terasology.utilities.Assets.get(Assets.java:75)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem.lambda$postBegin$1(WorkstationItemsInGameHelpCommonSystem.java:72)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem$$Lambda$230/1251686742.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem.postBegin(WorkstationItemsInGameHelpCommonSystem.java:74)
	at org.terasology.engine.modes.loadProcesses.PostBeginSystems.step(PostBeginSystems.java:44)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 14 column 12 path $.ItemHelp.paragraphText[1]
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at org.terasology.persistence.serializers.EntityDataJSONFormat.readPrefab(EntityDataJSONFormat.java:81)
	... 35 common frames omitted
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 14 column 12 path $.ItemHelp.paragraphText[1]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:418)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:734)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 39 common frames omitted
01:48:50.671 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem.lambda$postBegin$1(WorkstationItemsInGameHelpCommonSystem.java:72)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem$$Lambda$230/1251686742.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem.postBegin(WorkstationItemsInGameHelpCommonSystem.java:74)
	at org.terasology.engine.modes.loadProcesses.PostBeginSystems.step(PostBeginSystems.java:44)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
01:48:50.671 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem.lambda$postBegin$1(WorkstationItemsInGameHelpCommonSystem.java:72)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem$$Lambda$230/1251686742.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem.postBegin(WorkstationItemsInGameHelpCommonSystem.java:74)
	at org.terasology.engine.modes.loadProcesses.PostBeginSystems.step(PostBeginSystems.java:44)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
For more details, see the log files in C:\Dev\Terasology\Git\integrate\Terasology\logs\2016-12-22_01-47-45
```

**Comment by eviltak** [comment]
Removing a comma in the `sounds` array of the `Core:railgunTool` prefab does cause the first exception, but does not crash the game. The uncaught `NoSuchElementException` (the source of the crash) is not raised.

**Comment by Cervator** [comment]
Good catch :-)

On the other hand I just got a similar crash with a simple *extra* comma at the end of a prefab component definition.

Prefab:

```json
{
    "parent" : "engine:iconItem",
    "DisplayName" : {
        "name" : "Stainless Cleaver",
        "description" : "Use to cut through meat or bones."
    },
    "Item" : {
        "icon" : "Cooking:Cleaver",
        "stackId" : "cooking:Cleaver",
    },
    "Durability" : {
        "durability" : 300,
        "maxDurability" : 300
    },
    "CraftingStationTool" : {
        "type" : ["Cleaver"]
    },
    "ItemHelp" : {
        "category" : "Cooking",
        "paragraphText" : [
            "The cleaver uses its weight to cut through tough food with a chopping motion."
        ]
    }
}
```

Log snippet:

```
23:25:25.922 [main] ERROR org.terasology.assets.AssetType - Failed to load asset 'Cooking:Cleaver'
java.io.IOException: Failed to load prefab
	at org.terasology.persistence.serializers.EntityDataJSONFormat.readPrefab(EntityDataJSONFormat.java:83)
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:51)
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:36)
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292)
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180)
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228)
	at org.terasology.assets.AssetType.lambda$reload$1(AssetType.java:356)
	at org.terasology.assets.AssetType$$Lambda$73/1511909371.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.terasology.assets.AssetType.reload(AssetType.java:354)
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:383)
	at org.terasology.assets.AssetType.getAsset(AssetType.java:262)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:223)
	at org.terasology.utilities.Assets.get(Assets.java:75)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem.lambda$postBegin$1(WorkstationItemsInGameHelpCommonSystem.java:72)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem$$Lambda$258/1968340534.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem.postBegin(WorkstationItemsInGameHelpCommonSystem.java:74)
	at org.terasology.engine.modes.loadProcesses.PostBeginSystems.step(PostBeginSystems.java:44)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 10 column 6 path $.Item.stackId
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at org.terasology.persistence.serializers.EntityDataJSONFormat.readPrefab(EntityDataJSONFormat.java:81)
	... 35 common frames omitted
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 10 column 6 path $.Item.stackId
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:509)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:418)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:742)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:743)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 39 common frames omitted
23:25:25.923 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem.lambda$postBegin$1(WorkstationItemsInGameHelpCommonSystem.java:72)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem$$Lambda$258/1968340534.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.terasology.workstationInGameHelp.systems.WorkstationItemsInGameHelpCommonSystem.postBegin(WorkstationItemsInGameHelpCommonSystem.java:74)
	at org.terasology.engine.modes.loadProcesses.PostBeginSystems.step(PostBeginSystems.java:44)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
23:25:25.923 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by Cervator** [comment]
Closing as completed by #2825
