### ISSUE TITLE
java.lang.RuntimeException: Can not initialize graphics device

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/Terasology#2802]
Report from IRC (koolestest). This is similar to the crashes on Intel HD 4000 and other older hardware, but apparently the user uses a GTX 760 with proprietary Nvidia drivers which should be able to run the game just fine - plus the crash isn't silent, with the log pointing to an internal LWJGL error.

http://pastebin.com/FTkk9BH4

Relevant snippets:
```
13:27:09.823 [main] ERROR o.terasology.engine.TerasologyEngine - Failed to initialise Terasology
java.lang.RuntimeException: Can not initialize graphics device.
    at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.initDisplay(LwjglGraphics.java:266)
```
...
```
Caused by: org.lwjgl.LWJGLException: X Error - disp: 0x7f1884a79880 serial: 87 error: BadValue (integer parameter out of range for operation) request_code: 154 minor_code: 24
    at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
    at org.lwjgl.opengl.LinuxContextImplementation.nCreate(Native Method)
```

@Cervator @emanuele3d ping!

**Comment by skaldarnar** [comment]
A quick search reveals several reports with that error (some related to running Minecraft):

* http://stackoverflow.com/questions/28867285/lwjgl-reports-that-opengl-is-not-supported-on-a-modern-nvidia-card
* http://askubuntu.com/questions/663486/nvidia-drivers-cause-minecraft-to-crash
* http://www.minecraftforum.net/forums/support/unmodified-minecraft-client/2607982-launcher-crash-report-trying-to-run-in-lubuntu-14

**Comment by emanuele3d** [comment]
Interesting. The only two lines in LWJGLGraphics that can generate that error in the log are

`Display.setTitle("Terasology" + " | " + "Alpha");`

and

`Display.setVSyncEnabled(config.isVSync());`

Any other issue arising between those lines would have generated additional warnings in the log. Either ways, it seems out of our hands: the Display class is provided by LWJGL and the LWJGLexception being thrown seems to confirm this is an issue deeper than Terasology.

Hopefully skaldarnar's link provide a way out for the user.

**Comment by Malanius** [comment]
Might be related to #2790  I had same error caused by nVidia drivers. After the last update, everything is fine.

**Comment by Cervator** [comment]
> Might be related to #2790 I had same error caused by nVidia drivers. After the last update, everything is fine.

Last update of the *driver* or *Terasology* ? :-)

Just to be sure. Yeah there was a "bad" recent nvidia driver package (#2790)

**Comment by taisph** [comment]
I had a similar issue on Linux. There's a bug handling multiple display outputs in lwjgl versions after 2.9.0 or 2.9.1. It is fixed in their 2.x master branch (PR: https://github.com/LWJGL/lwjgl/pull/116). I compiled lwjgl manually and replaced the lwjgl libraries in the latest Terasology release. After that the game runs perfectly.

**Comment by njbbaer** [comment]
I am currently having this issue on Linux. Can @taisph go into greater detail about how to replace the replace the lwjgl libraries?

**Comment by taisph** [comment]
@njbbaer Ugh. Basically you'd have to pull the master branch from https://github.com/LWJGL/lwjgl, follow their guide and build the binaries. Then you have to find the correct files in the resulting build and replace their counterparts in Terasology; in `libs` and `natives/linux` if I remember correctly. I am sorry I cannot be more specific than this but it's been awhile.

TBT, the Terasology team should consider upgrading the bundled lwjgl-2.9.x files to a working nightly or just build them manually. @skaldarnar?

**Comment by Cervator** [comment]
Sorry for missing your earlier comment there @taisph - thanks for linking that issue :-)

I think we briefly looked at a later LWJGL quite a while back, although I think it was for some unrelated bug fix for applet support that has now been discontinued anyway. So we just put all that off to a future consideration of going LWJGL 3 or LibGDX.

But if there's a fix that tasty in the latest LWJGL nightly then we might indeed need to retry that. I wish they'd just release a 2.9.4 formally already :-)

**Comment by ivarec** [comment]
Unfortunately this affects me as well and I can't play the game on Linux.

NVIDIA driver: 390.25 (GTX 960m)
Terasology build: http://jenkins.terasology.org/job/TerasologyStable/74/
