### ISSUE TITLE
Can't unbind multiple keys

### ISSUE THREAD

**Issue by Vizaxo** [MovingBlocks/Terasology#2831]
### What you were trying to do

Unbind multiple keys in one game session.

The first unbind works, but subsequent ones don't.

### What actually happened

The dialog box hangs (the "ok" button stays pressed down, but the dialog box stays open and doesn't do anything. It can be closed, but the button will not be unbound).

### How to reproduce

* Open up settings->input
* Click on a key to unbind
* Click remove
* Click OK
* This first one should unbind successfully
* Repeat the process
* The second and subsequent unbinds will not work
* Pressing "Restore Defaults" or restarting the game will allow you to unbind one more, but will break again on subsequent unbinds

### Log details and game version
Game version: tested both on the latest source tree (commit 7e3ba2c), and the Omega 691 binaries from http://forum.terasology.org/threads/play-test-session-sunday-march-19th-1-pm-us-eastern-time.1814/.

Relevant log:

18:33:51.967 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event java.lang.NullPointerException: null
        at org.terasology.rendering.nui.layers.mainMenu.inputSettings.ChangeBindingPopup.lambda$initialise$232(ChangeBindingPopup.java:70)
        at org.terasology.rendering.nui.widgets.UIButton.activate(UIButton.java:203)
        at org.terasology.rendering.nui.widgets.UIButton.access$100(UIButton.java:41)
        at org.terasology.rendering.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:99)
        at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:247)
        at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:577)
        at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
        at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:279)
        at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:258)
        at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
        at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:545)
        at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:332)
        at org.terasology.input.InputSystem.update(InputSystem.java:279)
        at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:179)
        at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:54)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:422)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
        at org.terasology.engine.Terasology.main(Terasology.java:152)

### Computer details
GNU/Linux Ubuntu 16.10

**Comment by Cervator** [comment]
Thanks for putting these together with so much detail! :-)

**Comment by arthurdeschamps** [comment]
Same issue on MacOS.
I'll try to fix this (first contribution for the record, I hope this one is not too tricky).

**Comment by Malanius** [comment]
I can confirm on Windows too. 
Also, if you try to unbind the second one, the OK buttons seems to be pressed, leave with Cancel and try to edit another key binding, the OK button in still pressed and remains like this until used to confirm any other binding screen.

**Comment by arthurdeschamps** [comment]
So, I've modified the method `isBound(Input newInput)` to return `false` when `newInput` is `null`, because it was returning `true`, and thus in a condition a method on `newInput` was called, causing the `nullPointerException`.

I think the problem is solved, at least I tried to unbind and bind multiple keys (for example moving forward and backward) and it worked.

What should I do now?

**Comment by iojw** [comment]
@arthurdeschamps Hey there. If you look above you'll see that PR #2840 has already been submitted to fix this issue. It contains the fix you mention and does appear to fix the issue, just waiting for a merge.

Maybe you would like to take a look at one of the other issues? If there has already been a PR submitted for an issue, it might be better to suggest changes rather than opening a new one.

**Comment by arthurdeschamps** [comment]
@iojw oops my bad I did not realise it was a fix. Well, I'll try to find something else, thank you.
