### ISSUE TITLE
Improve null handling / logging in ItemPickupAuthoritySystem

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3158]
Noticed this issue on startup with the new module BasicCrafting enabled. It isn't caused by BC but that module exercises stuff on initialization that triggers it. Some block somewhere isn't fully configured right and that's tripping up that bit of code - it doesn't seem to lead to any issues, but it would be good to be able to log more cleanly what is going on.

```
21:40:17.348 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block core:RedShroom with id 31
21:40:17.374 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.logic.inventory.ItemPickupAuthoritySystem.updateExtentsOnBlockItemBoxShape(ItemPickupAuthoritySystem.java:92)
	at org.terasology.logic.inventory.ItemPickupAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.create(PojoEntityManager.java:166)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.create(PojoEntityManager.java:274)
	at org.terasology.crafting.systems.IconManagerImpl.loadItems(IconManagerImpl.java:144)
	at org.terasology.crafting.systems.IconManagerImpl.postBegin(IconManagerImpl.java:69)
	at org.terasology.engine.modes.loadProcesses.PostBeginSystems.step(PostBeginSystems.java:53)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:437)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:400)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:376)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
21:40:17.439 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[Core:Cotton4]
21:40:17.439 [main] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block Core:Cotton4 with id 32
```

Goal: Catch and handle the null more gracefully in `ItemPickupAuthoritySystem.updateExtentsOnBlockItemBoxShape` - try to see what other information is available and log the details at WARN level then continue normally instead of throwing the stacktrace.

Running with Core + BC enabled and checking the startup logs shows this issue repeatedly so it shouldn't be hard to trigger the condition.

Good bite-sized issue and we can create a GCI task for it if somebody is interested.

**Comment by eviltak** [comment]
This problem occurs only for the `engine:blockItemBase` prefab and can easily be solved by a null check. I'd love to take this up as a GCI task.

**Comment by jellysnake** [comment]
@eviltak If you're still up for doing this I can make it a GCI task for you.

**Comment by eviltak** [comment]
@jellysnake I'd love that, thank you. 

I think that this issue warrants some discussion. I haven't extensively researched it, but the problem seems to only occur when a prefab has an empty `BlockItem` component (or more appropriately, the component doesn't have a `blockFamily` property), as is the case with `engine:blockItemBase`. If that prefab is the _only_ place where we encounter such a situation, the `null` check should do just fine. But if this problem can make itself apparent elsewhere, logging a warning would be a better idea.

**Comment by jellysnake** [comment]
I think that it would be better to have a null catch and to provide some form of logging. Whilst there is only one block that causes this at the moment there may be more broken blocks in the future. Either deliberate or accidental
