### ISSUE TITLE
Failure to fully create some StructureTemplates for dwarf halls in GooeysQuests

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3390]
### What you were trying to do

Test out dwarf halls in GooeysQuests. Regular dungeon StructureTemplates (STs) are OK, as is the initial entrance to a dwarf hall. OKish I guess, the stair blocks themselves are still somewhat off.

### What actually happened

After I asked Gooey for a dwarf hall a pile of errors got printed to the log. Oddly I didn't notice that when I manually placed a dwarf hall via entrance prefab retrieved from the game console.

I believe this used to work fine before the big block family changes (#3343) but am not 100% sure. It might also be that my attempted fix for the ST repo to restore compatibility wasn't good enough. There is an interesting comment right by the main fix at https://github.com/Terasology/StructureTemplates/commit/0c6e6a9f96cdffd4a8cdde165646d9be04d0811d#diff-962dc32fe9ccb5b1c3d0338e5915f63aR81 that stuck out but I have no idea what it means - maybe @flo remembers? Or maybe @pollend could investigate sometime.

This might be an engine fix related to block families or a fix to the https://github.com/Terasology/StructureTemplates repo - unsure

On a related note after merging #3389 stair blocks can be placed in a given direction again, but they don't appear to be rotating correctly when part of a ST depending on the direction it spawns in. One dwarf hall (north facing?) showed a normal staircase shaft (including stairs in every possible direction) with the underground halls semi-intact while another dwarf hall spawn rotated 90 degrees to the left still *did* show shaircase rotation, but not correctly placed, making me think this issue does relate to a rotation-transformation of STs themselves (which in turn can have individual block family members with different rotations inside them)

### How to reproduce

* Start the game with GooeysQuests
* Ask Gooey for a dwarf hall (can be a little tricky - you might get stuck with dungeon offers a few times)
* Behold the game log. The amount of log spam depends on how big the dwarf hall grows.

### Log details and game version

Tested via mega-workspace as final prep for Alpha 10. You can see from a screenshot where I've ghosted into the ground how inconsistent the dwarf halls have built out. Yet for some reason the staircase shaft generates mostly fine, as do (most?) the regular dungeon STs.

![2018-06-10 22_15_21-terasology _ alpha](https://user-images.githubusercontent.com/1063833/41209882-3371f526-6cfc-11e8-932c-4d984bb58893.png)

```
22:02:14.613 [main] INFO  o.t.logic.console.ConsoleImpl - [CHAT] Gooey: Hi, up for some dwarf hall exploration?
22:02:18.303 [main] INFO  o.t.logic.console.ConsoleImpl - [CHAT] Gooey: Ha ha, that will be fun!
22:02:18.346 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.world.chunks.internal.ChunkImpl.setBlock(ChunkImpl.java:161)
	at org.terasology.world.chunks.internal.ChunkImpl.setBlock(ChunkImpl.java:172)
	at org.terasology.world.internal.WorldProviderCoreImpl.setBlocks(WorldProviderCoreImpl.java:237)
	at org.terasology.world.internal.AbstractWorldProviderDecorator.setBlocks(AbstractWorldProviderDecorator.java:102)
	at org.terasology.world.internal.AbstractWorldProviderDecorator.setBlocks(AbstractWorldProviderDecorator.java:102)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.spawnBlocks(StructureSpawnServerSystem.java:103)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.onSpawnStructureEventWithBlocksPriority(StructureSpawnServerSystem.java:88)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.structureTemplates.internal.systems.ScheduledStructureSpawnSystem.update(ScheduledStructureSpawnSystem.java:167)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:181)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:446)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:409)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:385)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
22:02:18.362 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.world.chunks.internal.ChunkImpl.setBlock(ChunkImpl.java:161)
	at org.terasology.world.chunks.internal.ChunkImpl.setBlock(ChunkImpl.java:172)
	at org.terasology.world.internal.WorldProviderCoreImpl.setBlocks(WorldProviderCoreImpl.java:237)
	at org.terasology.world.internal.AbstractWorldProviderDecorator.setBlocks(AbstractWorldProviderDecorator.java:102)
	at org.terasology.world.internal.AbstractWorldProviderDecorator.setBlocks(AbstractWorldProviderDecorator.java:102)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.spawnBlocks(StructureSpawnServerSystem.java:103)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.onSpawnStructureEventWithBlocksPriority(StructureSpawnServerSystem.java:88)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.structureTemplates.internal.systems.ScheduledStructureSpawnSystem.update(ScheduledStructureSpawnSystem.java:167)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:181)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:446)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:409)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:385)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
22:02:18.382 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.world.chunks.internal.ChunkImpl.setBlock(ChunkImpl.java:161)
	at org.terasology.world.chunks.internal.ChunkImpl.setBlock(ChunkImpl.java:172)
	at org.terasology.world.internal.WorldProviderCoreImpl.setBlocks(WorldProviderCoreImpl.java:237)
	at org.terasology.world.internal.AbstractWorldProviderDecorator.setBlocks(AbstractWorldProviderDecorator.java:102)
	at org.terasology.world.internal.AbstractWorldProviderDecorator.setBlocks(AbstractWorldProviderDecorator.java:102)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.spawnBlocks(StructureSpawnServerSystem.java:103)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.onSpawnStructureEventWithBlocksPriority(StructureSpawnServerSystem.java:88)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.structureTemplates.internal.systems.ScheduledStructureSpawnSystem.update(ScheduledStructureSpawnSystem.java:167)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:181)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:446)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:409)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:385)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
22:02:18.434 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.world.chunks.internal.ChunkImpl.setBlock(ChunkImpl.java:161)
	at org.terasology.world.chunks.internal.ChunkImpl.setBlock(ChunkImpl.java:172)
	at org.terasology.world.internal.WorldProviderCoreImpl.setBlocks(WorldProviderCoreImpl.java:237)
	at org.terasology.world.internal.AbstractWorldProviderDecorator.setBlocks(AbstractWorldProviderDecorator.java:102)
	at org.terasology.world.internal.AbstractWorldProviderDecorator.setBlocks(AbstractWorldProviderDecorator.java:102)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.spawnBlocks(StructureSpawnServerSystem.java:103)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.onSpawnStructureEventWithBlocksPriority(StructureSpawnServerSystem.java:88)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.structureTemplates.internal.systems.ScheduledStructureSpawnSystem.update(ScheduledStructureSpawnSystem.java:167)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:181)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:446)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:409)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:385)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
22:02:18.439 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.logic.inventory.InventoryUtils.putItemIntoSlot(InventoryUtils.java:392)
	at org.terasology.logic.inventory.InventoryAuthoritySystem.giveItemToSlots(InventoryAuthoritySystem.java:213)
	at org.terasology.logic.inventory.InventoryAuthoritySystem.giveItem(InventoryAuthoritySystem.java:321)
	at org.terasology.logic.inventory.InventoryAuthoritySystem.giveItem(InventoryAuthoritySystem.java:303)
	at org.terasology.structureTemplates.internal.systems.AddItemsToChestSystem.addItemToChest(AddItemsToChestSystem.java:106)
	at org.terasology.structureTemplates.internal.systems.AddItemsToChestSystem.addItemsToChest(AddItemsToChestSystem.java:90)
	at org.terasology.structureTemplates.internal.systems.AddItemsToChestSystem.onSpawnStructureEvent(AddItemsToChestSystem.java:73)
	at org.terasology.structureTemplates.internal.systems.AddItemsToChestSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.onSpawnStructureEventWithLowestPriority(StructureSpawnServerSystem.java:94)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.structureTemplates.internal.systems.ScheduledStructureSpawnSystem.update(ScheduledStructureSpawnSystem.java:167)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:181)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:446)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:409)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:385)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
22:02:18.453 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.world.chunks.internal.ChunkImpl.setBlock(ChunkImpl.java:161)
	at org.terasology.world.chunks.internal.ChunkImpl.setBlock(ChunkImpl.java:172)
	at org.terasology.world.internal.WorldProviderCoreImpl.setBlocks(WorldProviderCoreImpl.java:237)
	at org.terasology.world.internal.AbstractWorldProviderDecorator.setBlocks(AbstractWorldProviderDecorator.java:102)
	at org.terasology.world.internal.AbstractWorldProviderDecorator.setBlocks(AbstractWorldProviderDecorator.java:102)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.spawnBlocks(StructureSpawnServerSystem.java:103)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.onSpawnStructureEventWithBlocksPriority(StructureSpawnServerSystem.java:88)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.structureTemplates.internal.systems.ScheduledStructureSpawnSystem.update(ScheduledStructureSpawnSystem.java:167)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:181)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:446)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:409)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:385)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
22:02:18.470 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.world.chunks.internal.ChunkImpl.setBlock(ChunkImpl.java:161)
	at org.terasology.world.chunks.internal.ChunkImpl.setBlock(ChunkImpl.java:172)
	at org.terasology.world.internal.WorldProviderCoreImpl.setBlocks(WorldProviderCoreImpl.java:237)
	at org.terasology.world.internal.AbstractWorldProviderDecorator.setBlocks(AbstractWorldProviderDecorator.java:102)
	at org.terasology.world.internal.AbstractWorldProviderDecorator.setBlocks(AbstractWorldProviderDecorator.java:102)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.spawnBlocks(StructureSpawnServerSystem.java:103)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.onSpawnStructureEventWithBlocksPriority(StructureSpawnServerSystem.java:88)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.structureTemplates.internal.systems.ScheduledStructureSpawnSystem.update(ScheduledStructureSpawnSystem.java:167)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:181)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:446)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:409)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:385)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
22:02:18.483 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
22:02:18.494 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
22:02:18.506 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
22:02:18.570 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
22:02:18.587 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
22:02:18.587 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.logic.inventory.InventoryUtils.putItemIntoSlot(InventoryUtils.java:392)
	at org.terasology.logic.inventory.InventoryAuthoritySystem.giveItemToSlots(InventoryAuthoritySystem.java:213)
	at org.terasology.logic.inventory.InventoryAuthoritySystem.giveItem(InventoryAuthoritySystem.java:321)
	at org.terasology.logic.inventory.InventoryAuthoritySystem.giveItem(InventoryAuthoritySystem.java:303)
	at org.terasology.structureTemplates.internal.systems.AddItemsToChestSystem.addItemToChest(AddItemsToChestSystem.java:106)
	at org.terasology.structureTemplates.internal.systems.AddItemsToChestSystem.addItemsToChest(AddItemsToChestSystem.java:90)
	at org.terasology.structureTemplates.internal.systems.AddItemsToChestSystem.onSpawnStructureEvent(AddItemsToChestSystem.java:73)
	at org.terasology.structureTemplates.internal.systems.AddItemsToChestSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.onSpawnStructureEventWithLowestPriority(StructureSpawnServerSystem.java:94)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.structureTemplates.internal.systems.ScheduledStructureSpawnSystem.update(ScheduledStructureSpawnSystem.java:167)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:181)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:446)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:409)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:385)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
22:02:18.608 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
22:02:18.621 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
22:02:18.621 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.logic.inventory.InventoryUtils.putItemIntoSlot(InventoryUtils.java:392)
	at org.terasology.logic.inventory.InventoryAuthoritySystem.giveItemToSlots(InventoryAuthoritySystem.java:213)
	at org.terasology.logic.inventory.InventoryAuthoritySystem.giveItem(InventoryAuthoritySystem.java:321)
	at org.terasology.logic.inventory.InventoryAuthoritySystem.giveItem(InventoryAuthoritySystem.java:303)
	at org.terasology.structureTemplates.internal.systems.AddItemsToChestSystem.addItemToChest(AddItemsToChestSystem.java:106)
	at org.terasology.structureTemplates.internal.systems.AddItemsToChestSystem.addItemsToChest(AddItemsToChestSystem.java:90)
	at org.terasology.structureTemplates.internal.systems.AddItemsToChestSystem.onSpawnStructureEvent(AddItemsToChestSystem.java:73)
	at org.terasology.structureTemplates.internal.systems.AddItemsToChestSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystem.onSpawnStructureEventWithLowestPriority(StructureSpawnServerSystem.java:94)
	at org.terasology.structureTemplates.internal.systems.StructureSpawnServerSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:516)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:279)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:270)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.structureTemplates.internal.systems.ScheduledStructureSpawnSystem.update(ScheduledStructureSpawnSystem.java:167)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:181)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:446)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:409)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:385)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
22:02:18.637 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
```

**Comment by Cervator** [comment]
Reopening as this isn't *quite* fully fixed, but mostly! The stair blocks are still not turned the right way in some orientations, which may be an easy fix.

While testing https://github.com/Terasology/GooeysQuests/pull/23 I also got some really weird results with templates not lining up. That may be entirely due to the size of the new dwarf arena, however.

I think @Naman-sopho has also encountered some remaining quirks with some structures, would be good to get some more details and confirm that GQ issue as specific to just a chamber type being too large.

**Comment by Cervator** [comment]
Closing this as completed via several rounds of related fixes, woohoo! :-)
