### ISSUE TITLE
Better isolate involvement of OpenVR regarding FirstPersonHeldItemMountPointComponent

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3415]
This in a way is a follow-up to #2611 which has far more todo items. But an issue that has come up lately is that if the game is run in an unusual context (environment-based unit tests in Jenkins, the server facade, etc) initialization of natives can be problematic and in some cases nonsensical such as supporting VR while running a headless testing client.

Specifically `FirstPersonHeldItemMountPointComponent` has references to `VRControllerState_t` which comes from inside the `engine/libs/jopenvr.jar` (moving that to a jar hosted by Artifactory is another todo) - however it is not necessarily present on the classpath in some cases. It works fine when running the game normally via PC facade.

Goal for this issue is to better isolate that somehow so the game can initialize everything in a headless context.

Our normal approach is to pick headless style subsystems instead of headed ones, see for instance `Terasology.populateSubsystems` - in this case `OpenVRInput` is only initialized if not headless. However, the `FirstPersonHeldItemMountPointComponent` usage is escaping that as it is linked to some of the general controller setup as well.

It might be possible to reverse how some of the callback stuff works so it is the OpenVR side that initiates its listener stuff without having to pass in OpenVR specific classes. Then unless that stuff is actively loaded and enabled (this happens regardless of whether VR is enabled in-game, which is another issue) the call never happens and `VRControllerState_t` is not needed on the classpath

Maybe of interest to @dave2s or perhaps @indianajohn if still around :-)

When fixed this should ease @Inei1's troubles when trying to bundle the server facade with the Omega zip while also allowing us to have fully functional environment-based unit tests for the first time in ages.

Resulting error (from starting server facade or running unit tests like the ones in the ModuleTestingEnvironment in Jenkins):

```
ERROR o.t.e.metadata.ComponentLibrary - Class not found, FirstPersonHeldItemMountPointComponent
java.lang.NoClassDefFoundError: jopenvr/VRControllerState_t
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at org.terasology.utilities.ReflectionUtil.findMethod(ReflectionUtil.java:109)
        at org.terasology.utilities.ReflectionUtil.findGetter(ReflectionUtil.java:81)
        at org.terasology.reflection.metadata.FieldMetadata.determineType(FieldMetadata.java:70)
        at org.terasology.reflection.metadata.FieldMetadata.<init>(FieldMetadata.java:57)
        at org.terasology.entitySystem.metadata.ReplicatedFieldMetadata.<init>(ReplicatedFieldMetadata.java:39)
        at org.terasology.entitySystem.metadata.ComponentFieldMetadata.<init>(ComponentFieldMetadata.java:42)
        at org.terasology.entitySystem.metadata.ComponentMetadata.createField(ComponentMetadata.java:84)
        at org.terasology.entitySystem.metadata.ComponentMetadata.createField(ComponentMetadata.java:40)
        at org.terasology.reflection.metadata.ClassMetadata.addFields(ClassMetadata.java:106)
        at org.terasology.reflection.metadata.ClassMetadata.<init>(ClassMetadata.java:85)
        at org.terasology.entitySystem.metadata.ComponentMetadata.<init>(ComponentMetadata.java:58)
        at org.terasology.entitySystem.metadata.ComponentLibrary.createMetadata(ComponentLibrary.java:59)
        at org.terasology.reflection.metadata.AbstractClassLibrary.register(AbstractClassLibrary.java:91)
        at org.terasology.entitySystem.metadata.ComponentLibrary.register(ComponentLibrary.java:114)
        at org.terasology.engine.bootstrap.EnvironmentSwitchHandler.registerComponents(EnvironmentSwitchHandler.java:196)
        at org.terasology.engine.bootstrap.EnvironmentSwitchHandler.handleSwitchToGameEnvironment(EnvironmentSwitchHandler.java:98)
        at org.terasology.engine.TerasologyEngine.initialize(TerasologyEngine.java:207)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:378)
        at org.terasology.web.EngineRunner.runEngine(EngineRunner.java:63)
        at org.terasology.web.ServerMain.main(ServerMain.java:118)
Caused by: java.lang.ClassNotFoundException: jopenvr.VRControllerState_t
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 25 common frames omitted
```

Edit: Some code was commented out to work around this for the time being, see #3897 and https://github.com/Terasology/CoreRendering/pull/8

**Comment by Cervator** [comment]
Note: as of https://github.com/MovingBlocks/Terasology/issues/3877 a tiny bit of stuff related to this got checked out to break the dependency in a less ideal but also lower effort method.

**Comment by jdrueckert** [comment]
VR support was removed in #5112 so I'm closing this issue.
If VR support is re-introduced this issue is now linked to the PR that removed it, so it can be reopened or directly considered during the re-introduction
