### ISSUE TITLE
PathManager quirk: Game cannot be started from any directory

### ISSUE THREAD

**Issue by qwc** [MovingBlocks/Terasology#3423]
### What you were trying to do
Starting terasology in my docker image from another directory than the binaries.

### What actually happened
```
Attaching to terasology-unstable_terasology_1
terasology_1  | Recognized argument: -headless
terasology_1  | Recognized argument: -homedir=/terasology/server
terasology_1  | PathManager being initialized. Initial code location is /terasology/libs/engine-2.0.1-SNAPSHOT.jar
terasology_1  | Switched it to expected working dir: /
terasology_1  | installPath was null, running from IDE or headless server? Setting to: /
terasology_1  | Exception in thread "main" java.lang.NullPointerException
terasology_1  |         at org.terasology.engine.paths.PathManager.findNativesHome(PathManager.java:125)
terasology_1  |         at org.terasology.engine.paths.PathManager.<init>(PathManager.java:98)
terasology_1  |         at org.terasology.engine.paths.PathManager.getInstance(PathManager.java:142)
terasology_1  |         at org.terasology.engine.Terasology.handleLaunchArguments(Terasology.java:354)
terasology_1  |         at org.terasology.engine.Terasology.main(Terasology.java:121)
```

### How to reproduce

* Start terasology with:
```
cd /
java -jar /<where_terasology_is_installed>/libs/Terasology.jar [-headless -homedir=/terasology/server]
# thats my commandline inside docker
```

### Log details and game version
All lastest 2.x
### Temporary fix
Go into the directory and start terasology with `./libs/Terasology.jar [etc.etc.]`

### What should happen
The game should start just fine, maybe with a warning that it has no homedir or whatever, but it should start. Especially when the `-homedir` parameter is given it should start without any complaints.

**Comment by Cervator** [comment]
Thanks :-)

Potentially related: #3371

Seemingly before that change the _pathless_ approach in Docker *did* function for some reason, but other cases like environment-based unit tests in Jenkins would end up with a working dir set inside the Gradle cache. To my knowledge other pathless approaches have failed both before and after that change, you *must* launch the game from within the install dir whether or not you change the homedir. But that sucks.

That part of the PathManager has been quirky for ages, possibly in part because it is one of the few places containing code I've written ;-)

There are a bunch of alternative ways to get at Java's working directory, some noted in https://stackoverflow.com/questions/4871051/getting-the-current-working-directory-in-java - in the past I've just gone with whatever I got to work first but there are plenty I haven't tried like the "user.dir" thing or using `"."` instead of `""` to initialize a `Path` or `File`

One difficulty is that `PathManager` is a singleton initialized on first use without any sort of parameters, so there isn't an explicit way to pass in an install path. But I'm sure that can be redone - I just haven't had the time to dig quite that deep before.

To experiment with this issue vary the working directory calculations and see how different ways of launching the game or running tests work out: running from source via IDE, Gradle, build a binary and launch that way, with or without `-homedir` or `-headless` or other things. The Server Facade also hit the issue when built standalone. Also try running the unit tests specifically those using a game environment like those in the ModuleTestEnvironment or the NameGenerator. Example failure before the associated PR:

http://jenkins.terasology.org/view/Modules/job/NameGenerator/53/console

After the PR the next error is about OpenVR which is a different issue, see #3415

Note that in the case of a module failing environment tests this only happens with *standalone* module builds (a module building in an engine workspace just uses the engine as source and avoids the Gradle cache). To replicate that locally copy a module to its own workspace then drop in the `gradle`, `config` + `natives` dirs, the `build.gradle` from Core, and the `gradlew` script suitable for your OS. Run `gradlew check` to provoke.
