### ISSUE TITLE
Audio Scroll is Sticky

### ISSUE THREAD

**Issue by pollend** [MovingBlocks/Terasology#3433]
### What you were trying to do
Adjusting the audio in the settings menu
### What actually happened

The audio scroll handle is sticky and throws a lot of internal errors from the engine. Not sure why its calling code for WorldPreGeneration. I don't think tweaking the audio should affect this.

### Log details and game version
```
11:27:54.962 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.rendering.nui.layers.mainMenu.WorldPreGenerationScreen.updatePreview(WorldPreGenerationScreen.java:224)
	at org.terasology.rendering.nui.layers.mainMenu.WorldPreGenerationScreen.onSliderValueChanged(WorldPreGenerationScreen.java:271)
	at org.terasology.rendering.nui.widgets.UISlider$1.onMouseRelease(UISlider.java:62)
	at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:247)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:576)
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:528)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:298)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:277)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.input.InputSystem.send(InputSystem.java:367)
	at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:354)
	at org.terasology.input.InputSystem.processMouseButtonInput(InputSystem.java:184)
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:169)
	at org.terasology.input.InputSystem.update(InputSystem.java:129)
	at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:195)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:55)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:459)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:389)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
11:27:55.994 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.rendering.nui.layers.mainMenu.WorldPreGenerationScreen.updatePreview(WorldPreGenerationScreen.java:224)
	at org.terasology.rendering.nui.layers.mainMenu.WorldPreGenerationScreen.onSliderValueChanged(WorldPreGenerationScreen.java:271)
	at org.terasology.rendering.nui.widgets.UISlider$1.onMouseRelease(UISlider.java:62)
	at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:247)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:576)
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:528)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:298)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:277)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.input.InputSystem.send(InputSystem.java:367)
	at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:354)
	at org.terasology.input.InputSystem.processMouseButtonInput(InputSystem.java:184)
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:169)
	at org.terasology.input.InputSystem.update(InputSystem.java:129)
	at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:195)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:55)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:459)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:389)
	at org.terasology.engine.Terasology.main(Terasology.java:154)


```

**Comment by Cervator** [comment]
Closing as fixed by #3434
