### ISSUE TITLE
Crash when loading prefabs for many modules.

### ISSUE THREAD

**Issue by wispoffates** [MovingBlocks/Terasology#3483]
### What you were trying to do
Create Single player world with Josharias Survival and dependencies enabled.

### What actually happened
Crashed.
### How to reproduce

Enable modes Josharias Survival.
Click Play.

### Log details and game version
Version: latest development branch.

```
java.lang.IllegalStateException: Data is not an array: bytes: ""

        at org.terasology.persistence.typeHandling.protobuf.ProtobufPersistedData.getAsValueArray(ProtobufPersistedData.java:394)
        at org.terasology.persistence.typeHandling.protobuf.ProtobufPersistedData.iterator(ProtobufPersistedData.java:401)
        at org.terasology.persistence.typeHandling.coreTypes.CollectionTypeHandler.deserialize(CollectionTypeHandler.java:52)
        at org.terasology.persistence.typeHandling.coreTypes.CollectionTypeHandler.deserialize(CollectionTypeHandler.java:28)
        at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:97)
        at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:155)
        at org.terasology.persistence.serializers.ComponentSerializer.deserializeOnto(ComponentSerializer.java:202)
        at org.terasology.persistence.serializers.ComponentSerializer.deserialize(ComponentSerializer.java:118)
        at org.terasology.persistence.serializers.PrefabSerializer.applyComponentChanges(PrefabSerializer.java:164)
        at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:136)
        at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:116)
        at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:55)
        at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:36)
        at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292)
        at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180)
        at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228)
        at org.terasology.assets.AssetType.lambda$reload$2(AssetType.java:359)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.terasology.assets.AssetType.reload(AssetType.java:357)
        at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:386)
        at org.terasology.assets.AssetType.getAsset(AssetType.java:262)
        at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:223)
        at org.terasology.engine.modes.loadProcesses.LoadPrefabs.step(LoadPrefabs.java:42)
        at org.terasology.engine.modes.StateLoading.update(StateLoading.java:238)
        at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:458)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
        at org.terasology.engine.Terasology.main(Terasology.java:154)
```

### Computer details
Gentoo Linux - Ryzen 7 1800 - Amd 580RX

It appears to affect to loading of Prefabs in a large number of modules.

troy@eos ~/git/Terasology $ git bisect good
6a1c7be97da25f0525b1eda0eab3de5b01de6fd3 is the first bad commit
commit 6a1c7be97da25f0525b1eda0eab3de5b01de6fd3
Author: Arav Singhal <singhal.arav@gmail.com>
Date:   Tue Jul 24 22:15:23 2018 +0530

    Make CollectionTypeHandler manually serialize collection

:040000 040000 f614308c0439c6e82eb85586a4d2e89cc34c11ad 3fc0a57cd5673124a6d149ed0cf3a65a72011d3a M      engine

**Comment by Cervator** [comment]
This fix for this is now in place - closing as completed by #3489
