### ISSUE TITLE
Module details button fails when no module is selected

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3507]
### What you were trying to do

Click the "Module Details" button on the advanced game setup screen _before_ actually having a module selected. More or less by random chance, really.

### What actually happened

UI broke without a module selected to get details on. Button probably just needs a check that there's a valid value and if not then return early. Easy!

### How to reproduce

* Run the game and go through the create game, proceeding to the advanced game setup
* Make sure you haven't selected a module (will be the case on first launch of a game)
* Click the "Module Details" button - boom!

I'd be curious if something similar might also happen if you look at a save game's details, as there's also a way to get at module details in there too.

<img width="649" alt="2018-10-20 22_42_20-terasology - c__dev_terasology_git_minimergyworkspace_terasology - masterofor" src="https://user-images.githubusercontent.com/1063833/47262568-f3419580-d4b9-11e8-84eb-cb9ba865e08e.png">

### Log details and game version

Latest `develop` branch as of the time of writing this issue

```
22:42:10.794 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.rendering.nui.layers.mainMenu.advancedGameSetupScreen.AdvancedGameSetupScreen.lambda$null$13(AdvancedGameSetupScreen.java:493)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.terasology.rendering.nui.layers.mainMenu.advancedGameSetupScreen.AdvancedGameSetupScreen.lambda$initialise$14(AdvancedGameSetupScreen.java:494)
	at org.terasology.rendering.nui.widgets.UIButton.activate(UIButton.java:208)
	at org.terasology.rendering.nui.widgets.UIButton.access$100(UIButton.java:41)
	at org.terasology.rendering.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:99)
	at org.terasology.rendering.nui.internal.CanvasImpl.processMouseRelease(CanvasImpl.java:247)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:576)
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:531)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:301)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:280)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:204)
	at org.terasology.input.InputSystem.send(InputSystem.java:367)
	at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:354)
	at org.terasology.input.InputSystem.processMouseButtonInput(InputSystem.java:184)
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:169)
	at org.terasology.input.InputSystem.update(InputSystem.java:129)
	at org.terasology.engine.modes.StateMainMenu.handleInput(StateMainMenu.java:196)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:55)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:467)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
	at org.terasology.engine.Terasology.main(Terasology.java:155)
```

**Comment by Edvinas01** [comment]
I'd like to try - create a PR! Taking a look at Saved game details screen there seems to already be a check in place which should prevent this NPE:
https://github.com/MovingBlocks/Terasology/blob/405d90d93e2ad714bc5f3a8b1a454e8fffe9357f/engine/src/main/java/org/terasology/rendering/nui/layers/mainMenu/gameDetailsScreen/GameDetailsScreen.java#L551-L556
