### ISSUE TITLE
lwjgl NullPointerException when finding display due to xrandr config problem

### ISSUE THREAD

**Issue by cheongsiuhong** [MovingBlocks/Terasology#3649]
_Admin Edit: This issue documents a problem we can't do anything about beyond upgrading to LWJGL and is here for troubleshooting issues in case anybody else hits it. We'll upgrade eventually then this will no longer be an issue :-)_

### What you were trying to do

Just trying to run the game on Ubuntu 18.04.

### What actually happened

The Terasology Engine's calls to lwjgl's XRandr class - find primary display function throws a null pointer exception, causing a crash.

### How to reproduce

Set up a custom resolution with xrandr commands.
If the custom mode's name does not match the format "3000x2000", the game will crash on launch.
i.e. a custom resolution named "3000x2000_60.00" will cause the game to crash.

### Log details and game version

```
java.lang.ExceptionInInitializerError
    at org.terasology.engine.subsystem.lwjgl.LwjglDisplayDevice.setDisplayModeSetting(LwjglDisplayDevice.java:106)
    at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.initDisplay(LwjglGraphics.java:193)
    at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postInitialise(LwjglGraphics.java:146)
    at org.terasology.engine.TerasologyEngine.postInitSubsystems(TerasologyEngine.java:290)
    at org.terasology.engine.TerasologyEngine.initialize(TerasologyEngine.java:222)
    at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:390)
    at org.terasology.engine.Terasology.main(Terasology.java:156)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at org.lwjgl.opengl.XRandR.findPrimary(XRandR.java:326)
    at org.lwjgl.opengl.XRandR.ScreentoDisplayMode(XRandR.java:315)
    at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:746)
    at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:743)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:743)
    at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
    ... 7 more
```

### How to Fix

Change the custom resolution's name in xrandr to match the stated format.

**Comment by TheHxn** [comment]
Sorry but how to reproduce again?

**Comment by Cervator** [comment]
Responded on Discord earlier: in short this is an issue just to document the problem, there's nothing else to really troubleshoot or fix, we need to close this out when we manage to upgrade to LWJGL 3 which is supposed to resolve this :-)

Thanks again @cheongsiuhong for hunting down the details! It is also noted in the wiki at https://github.com/MovingBlocks/Terasology/wiki/Common-Issues#linux

**Comment by Cervator** [comment]
Noticed this still open by chance. We've actually upgraded to LWJGL 3 now! In theory this should be fixed, so I'll close this. If you happen to notice this @cheongsiuhong and want to validate please grab one of our recent builds - the LWJGL 3 upgrade has been live for a little while now 👍
