### ISSUE TITLE
Cannot start headless server on FReeBSD

### ISSUE THREAD

**Issue by desempare** [MovingBlocks/Terasology#3656]
### What you were trying to do
I'm try to run headless dedicated server on FreeBSD, use OpenJDK 1.8 64 bit.
### What actually happened
Server running, listen network, run client, add my server, got his info, latency, etc.. connect...fail. Server failing, shutdown. That it.
### How to reproduce
pkg install openkdk8
wget terasology.zip
unzip
run 
java -jar libs/Terasology.jar -headless
from another pc run terasology as client, adding server to favorites, connect
### Log details and game version
12:42:49.204 [main] INFO  o.t.logic.console.ConsoleImpl - [NOTIFICATION] Identity storage service: No configuration data is present, staying logged out.
12:43:13.185 [New I/O worker #1] INFO  o.t.n.i.ServerHandshakeHandler - Sending Server Hello
12:43:13.192 [New I/O worker #2] INFO  o.t.n.i.ServerHandshakeHandler - Sending Server Hello
12:43:13.214 [New I/O worker #1] WARN  o.t.network.internal.ServerHandler - Unexpected exception from client
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
12:43:13.215 [New I/O worker #1] WARN  o.t.network.internal.ServerHandler - Unexpected exception from client
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$UnpooledSendBuffer.transferTo(SocketSendBufferPool.java:203)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:201)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:146)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
        at org.terasology.network.internal.MetricRecordingHandler.writeRequested(MetricRecordingHandler.java:53)
        at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.jboss.netty.channel.Channels.write(Channels.java:725)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.jboss.netty.channel.Channels.write(Channels.java:725)
        at org.jboss.netty.channel.Channels.write(Channels.java:686)
        at org.jboss.netty.handler.codec.compression.ZlibEncoder.finishEncode(ZlibEncoder.java:390)
        at org.jboss.netty.handler.codec.compression.ZlibEncoder.handleDownstream(ZlibEncoder.java:326)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
        at org.jboss.netty.channel.Channels.close(Channels.java:812)
        at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:206)
        at org.terasology.network.internal.ServerHandler.exceptionCaught(ServerHandler.java:69)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.exceptionCaught(SimpleChannelUpstreamHandler.java:153)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.exceptionCaught(SimpleChannelUpstreamHandler.java:153)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:60)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.exceptionCaught(FrameDecoder.java:377)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelHandler.exceptionCaught(SimpleChannelHandler.java:156)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:130)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:525)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:74)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
12:43:13.305 [New I/O worker #2] INFO  o.t.n.i.ServerHandshakeHandler - Received client certificate
12:43:13.309 [New I/O worker #2] INFO  o.t.n.i.ServerHandshakeHandler - Sending server verification
12:43:14.340 [New I/O worker #3] INFO  o.t.n.i.ServerHandshakeHandler - Sending Server Hello
12:43:14.340 [New I/O worker #4] INFO  o.t.n.i.ServerHandshakeHandler - Sending Server Hello
12:43:14.366 [New I/O worker #3] INFO  o.t.n.i.ServerHandshakeHandler - Received client certificate
12:43:14.367 [New I/O worker #3] INFO  o.t.n.i.ServerHandshakeHandler - Sending server verification
12:43:14.532 [New I/O worker #5] INFO  o.t.n.i.ServerHandshakeHandler - Sending Server Hello
12:43:14.546 [New I/O worker #5] INFO  o.t.n.i.ServerHandshakeHandler - Received client certificate
12:43:14.547 [New I/O worker #5] INFO  o.t.n.i.ServerHandshakeHandler - Sending server verification
12:43:14.581 [New I/O worker #5] INFO  o.t.n.i.ServerConnectionHandler - Received Start Join
12:43:14.646 [main] INFO  o.t.n.internal.NetworkSystemImpl - New client entity: EntityRef{id = 445, netId = 92, prefab = 'engine:client'}
12:43:15.962 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (1031), capping to 1000
12:43:16.055 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.network.NetworkComponent added to EntityRef{id = 336, netId = 94, prefab = 'Core:transferSlot'}
12:43:16.056 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.entitySystem.entity.internal.EntityInfoComponent added to EntityRef{id = 336, netId = 94, prefab = 'Core:transferSlot'}
12:43:16.056 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.inventory.InventoryComponent added to EntityRef{id = 336, netId = 94, prefab = 'Core:transferSlot'}
12:43:16.058 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.network.NetworkComponent added to EntityRef{id = 449, netId = 95, prefab = 'Core:transferSlot'}
12:43:16.059 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.entitySystem.entity.internal.EntityInfoComponent added to EntityRef{id = 449, netId = 95, prefab = 'Core:transferSlot'}
12:43:16.059 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.inventory.InventoryComponent added to EntityRef{id = 449, netId = 95, prefab = 'Core:transferSlot'}
12:43:16.062 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.network.NetworkComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.064 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.characters.CharacterComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.064 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.physics.components.TriggerComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.064 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.characters.CharacterHeldItemComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.064 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.characters.GazeMountPointComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.065 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.physics.components.shapes.BoxShapeComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.065 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.health.HealthComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.065 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.location.LocationComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.065 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.characters.CharacterMovementComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.065 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.characters.VisualCharacterComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.065 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.inventory.SelectedInventorySlotComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.065 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.characters.AliveCharacterComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.065 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.entitySystem.entity.internal.EntityInfoComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.065 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.inventory.InventoryComponent added to EntityRef{id = 63, netId = 96, prefab = 'engine:player'}
12:43:16.069 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.ArithmeticException: input is infinite or NaN
        at com.google.common.math.DoubleMath.roundIntermediate(DoubleMath.java:57)
        at com.google.common.math.DoubleMath.roundToInt(DoubleMath.java:132)
        at org.terasology.math.geom.Vector3i.<init>(Vector3i.java:87)
        at org.terasology.math.ChunkMath.calcChunkPos(ChunkMath.java:79)
        at org.terasology.world.chunks.internal.ChunkRelevanceRegion.calculateCenter(ChunkRelevanceRegion.java:132)
        at org.terasology.world.chunks.internal.ChunkRelevanceRegion.update(ChunkRelevanceRegion.java:110)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.updateRelevance(LocalChunkProvider.java:487)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.beginUpdate(LocalChunkProvider.java:349)
        at org.terasology.engine.subsystem.headless.renderer.HeadlessWorldRenderer.update(HeadlessWorldRenderer.java:109)
        at org.terasology.engine.modes.StateIngame.update(StateIngame.java:176)
        at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:458)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
        at org.terasology.engine.Terasology.main(Terasology.java:145)
12:43:16.069 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
12:43:16.084 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
12:43:16.089 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
12:43:16.151 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Stryker
12:43:16.165 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
12:43:16.204 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
java.lang.ArithmeticException: input is infinite or NaN
        at com.google.common.math.DoubleMath.roundIntermediate(DoubleMath.java:57)
        at com.google.common.math.DoubleMath.roundToInt(DoubleMath.java:132)
        at org.terasology.math.geom.Vector3i.<init>(Vector3i.java:87)
        at org.terasology.math.ChunkMath.calcChunkPos(ChunkMath.java:79)
        at org.terasology.world.chunks.internal.ChunkRelevanceRegion.calculateCenter(ChunkRelevanceRegion.java:132)
        at org.terasology.world.chunks.internal.ChunkRelevanceRegion.update(ChunkRelevanceRegion.java:110)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.updateRelevance(LocalChunkProvider.java:487)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.beginUpdate(LocalChunkProvider.java:349)
        at org.terasology.engine.subsystem.headless.renderer.HeadlessWorldRenderer.update(HeadlessWorldRenderer.java:109)
        at org.terasology.engine.modes.StateIngame.update(StateIngame.java:176)
        at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:458)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
        at org.terasology.engine.Terasology.main(Terasology.java:145)
For more details, see the log files in /root/.local/share/terasology/logs/2019-04-05_12-42-30_2.2.0_78
### Computer details
FreeBSD 12
 openjdk version "1.8.0_202" (from ports)

**Comment by desempare** [comment]
I'm really really  sorry, run server with parameter -homedir and all works.
Thank you !!!

**Comment by Cervator** [comment]
Thanks for the report! I added a bit of formatting to your post in case others might find it handy in the future :-)
