### ISSUE TITLE
LWJGLException: Could not init GLX

### ISSUE THREAD

**Issue by SuperRoboWizard** [MovingBlocks/Terasology#3657]
### What you were trying to do
Start the game

### What actually happened
Game crashed while loading

### How to reproduce

* Start the game

### Log details and game version
https://pastebin.com/3Sq2W5AT
1:2.2.0alpha12-1, installed from AUR

### Computer details
Surface Pro 4, i7-6650U, Manjaro Linux

**Comment by Cervator** [comment]
Thanks for the report + figuring it out! I'm going to inline a snippet from your pastebin here in case searching for something similar might help out other users at a later date :-)

```
13:39:33.724 [main] INFO  o.t.e.subsystem.lwjgl.LwjglGraphics - Initializing display (if last line in log then likely the game crashed from an issue with your video card)
13:39:33.724 [Thread-4] INFO  o.t.i.s.StorageServiceWorker - Completed action InitializeFromTokenAction
13:39:33.775 [main] ERROR o.terasology.engine.TerasologyEngine - Failed to initialise Terasology
java.lang.RuntimeException: Can not initialize graphics device.
    at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.initDisplay(LwjglGraphics.java:239)
    at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postInitialise(LwjglGraphics.java:146)
    at org.terasology.engine.TerasologyEngine.postInitSubsystems(TerasologyEngine.java:290)
    at org.terasology.engine.TerasologyEngine.initialize(TerasologyEngine.java:222)
    at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:390)
    at org.terasology.engine.Terasology.main(Terasology.java:156)
Caused by: org.lwjgl.LWJGLException: Could not init GLX
    at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method)
    at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61)
    at org.lwjgl.opengl.LinuxDisplay.createPeerInfo(LinuxDisplay.java:828)
    at org.lwjgl.opengl.DrawableGL.setPixelFormat(DrawableGL.java:61)
    at org.lwjgl.opengl.Display.create(Display.java:846)
    at org.lwjgl.opengl.Display.create(Display.java:757)
    at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.initDisplay(LwjglGraphics.java:234)
    ... 5 common frames omitted
13:39:33.776 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```
