### ISSUE TITLE
Biome Loading Error

### ISSUE THREAD

**Issue by pollend** [MovingBlocks/Terasology#3714]
Just loading up the game on a defaul work sometimes will crash. The game can't find the biome world which was moved to a separate module under BiomeAPI. I think this might be a loading step problem where Biome's are loaded too early with the game booting up. @jellysnake 

```
09:51:17.629 [main] INFO  o.t.p.ParticleSystemManagerImpl - Registering GeneratorFunction for Component class class org.terasology.particles.components.generators.EnergyRangeGeneratorComponent
09:51:17.629 [main] INFO  o.t.p.ParticleSystemManagerImpl - Registering GeneratorFunction for Component class class org.terasology.particles.components.generators.VelocityRangeGeneratorComponent
09:51:17.629 [main] INFO  o.t.p.ParticleSystemManagerImpl - Registering GeneratorFunction for Component class class org.terasology.particles.components.generators.ColorRangeGeneratorComponent
09:51:17.630 [main] INFO  o.t.p.ParticleSystemManagerImpl - Registering GeneratorFunction for Component class class org.terasology.particles.components.generators.PositionRangeGeneratorComponent
09:51:17.630 [main] INFO  o.t.p.ParticleSystemManagerImpl - Registering GeneratorFunction for Component class class org.terasology.particles.components.generators.ScaleRangeGeneratorComponent
09:51:17.630 [main] INFO  o.t.p.ParticleSystemManagerImpl - Registering GeneratorFunction for Component class class org.terasology.particles.components.generators.TextureOffsetGeneratorComponent
09:51:17.630 [main] INFO  o.t.p.ParticleSystemManagerImpl - Registering AffectorFunction for Component class class org.terasology.particles.components.affectors.VelocityAffectorComponent
09:51:17.630 [main] INFO  o.t.p.ParticleSystemManagerImpl - Registering AffectorFunction for Component class class org.terasology.particles.components.affectors.AccelerationAffectorComponent
09:51:17.634 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type UIWidget: not a supported type or MappedContainer
09:51:17.634 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type RelativeLayoutHint: not a supported type or MappedContainer
09:51:17.634 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type HorizontalInfo: not a supported type or MappedContainer
09:51:17.634 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type VerticalInfo: not a supported type or MappedContainer
09:51:17.644 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type UIWidget: not a supported type or MappedContainer
09:51:17.657 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type RelativeLayoutHint: not a supported type or MappedContainer
09:51:17.658 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type HorizontalInfo: not a supported type or MappedContainer
09:51:17.658 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type VerticalInfo: not a supported type or MappedContainer
09:51:17.664 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type UIWidget: not a supported type or MappedContainer
09:51:17.673 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type UIWidget: not a supported type or MappedContainer
09:51:17.673 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type RelativeLayoutHint: not a supported type or MappedContainer
09:51:17.674 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type HorizontalInfo: not a supported type or MappedContainer
09:51:17.674 [main] ERROR o.t.p.t.TypeSerializationLibrary - Unable to register field of type VerticalInfo: not a supported type or MappedContainer
09:51:17.685 [main] INFO  o.t.p.c.PathfinderSystem - PathfinderSystem started
09:51:17.687 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NoClassDefFoundError: org/terasology/world/biomes/Biome
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.reflections.ReflectionUtils.getMethods(ReflectionUtils.java:84)
	at org.reflections.ReflectionUtils.getAllMethods(ReflectionUtils.java:77)
	at org.terasology.logic.console.commandSystem.MethodCommand.registerAvailable(MethodCommand.java:88)
	at org.terasology.engine.ComponentSystemManager.initialiseSystem(ComponentSystemManager.java:156)
	at org.terasology.engine.ComponentSystemManager.initialise(ComponentSystemManager.java:144)
	at org.terasology.engine.modes.loadProcesses.InitialiseSystems.step(InitialiseSystems.java:50)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:252)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:458)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
	at org.terasology.engine.Terasology.main(Terasology.java:156)
Caused by: java.lang.ClassNotFoundException: Failed to find or load class org.terasology.world.biomes.Biome
	at org.terasology.module.sandbox.ModuleClassLoader.findClass(ModuleClassLoader.java:158)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.terasology.module.sandbox.ModuleClassLoader.loadClass(ModuleClassLoader.java:121)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 common frames omitted
Caused by: javassist.NotFoundException: org.terasology.world.biomes.Biome
	at javassist.ClassPool.get(ClassPool.java:452)
	at org.terasology.module.sandbox.ModuleClassLoader$1.run(ModuleClassLoader.java:145)
	at org.terasology.module.sandbox.ModuleClassLoader$1.run(ModuleClassLoader.java:142)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.terasology.module.sandbox.ModuleClassLoader.findClass(ModuleClassLoader.java:142)
	... 17 common frames omitted
09:51:17.687 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
09:51:17.687 [main] DEBUG c.j.d.entities.pipe.UnixPipe - Closing IPC pipe...
java.lang.NoClassDefFoundError: org/terasology/world/biomes/Biome
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.reflections.ReflectionUtils.getMethods(ReflectionUtils.java:84)
	at org.reflections.ReflectionUtils.getAllMethods(ReflectionUtils.java:77)
	at org.terasology.logic.console.commandSystem.MethodCommand.registerAvailable(MethodCommand.java:88)
	at org.terasology.engine.ComponentSystemManager.initialiseSystem(ComponentSystemManager.java:156)
	at org.terasology.engine.ComponentSystemManager.initialise(ComponentSystemManager.java:144)
	at org.terasology.engine.modes.loadProcesses.InitialiseSystems.step(InitialiseSystems.java:50)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:252)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:458)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
	at org.terasology.engine.Terasology.main(Terasology.java:156)
Caused by: java.lang.ClassNotFoundException: Failed to find or load class org.terasology.world.biomes.Biome
	at org.terasology.module.sandbox.ModuleClassLoader.findClass(ModuleClassLoader.java:158)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.terasology.module.sandbox.ModuleClassLoader.loadClass(ModuleClassLoader.java:121)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Caused by: javassist.NotFoundException: org.terasology.world.biomes.Biome
	at javassist.ClassPool.get(ClassPool.java:452)
	at org.terasology.module.sandbox.ModuleClassLoader$1.run(ModuleClassLoader.java:145)
	at org.terasology.module.sandbox.ModuleClassLoader$1.run(ModuleClassLoader.java:142)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.terasology.module.sandbox.ModuleClassLoader.findClass(ModuleClassLoader.java:142)
	... 17 more
```

**Comment by skaldarnar** [comment]
I was finally able to solve this with the following steps:

- do a full `git clean -fdx` to remove all untracked files, directories, and build products. I think this also includes save games and configs...
- remove all additional modules (I luckily just had a few). I tried to just update my modules to latest commits on `master`/`develop`, but that apparently did not help
- run the _magic build command_ to fix everything: `gradlew cleanIdea clean idea jar game`

Anyways, would be nice to figure out the root cause for this to prevent future errors.
