### ISSUE TITLE
StackOverflow on certain combination of modules - Shattered Planes & Serialization involved?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#3739]
### What you were trying to do

Put together a complex set of modules for play testing. With testing eventually cut it down to the following list to still trigger

* CoreSampleGameplay
* CombatSystem
* ShatteredPlanes

### What actually happened

Crashed during initial world loading

### How to reproduce

* Retrieve the above set of modules
* Start a new game with said list of modules. 
* Be sure to select the Shattered Planes world

### Log details and game version

Latest develop with all modules at latest as of writing this

Note the first set of lines repeat quite a few times, and the stacktrace of course also keeps going for a while before the crash.

```
09:53:39.187 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab ShatteredPlanes:easterEgg with inputs [/ShatteredPlanes/assets/prefabs/easterEgg.prefab]
09:53:39.200 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab ShatteredPlanes:easterEgg with inputs [/ShatteredPlanes/assets/prefabs/easterEgg.prefab]
09:53:39.213 [main] INFO  o.t.e.prefab.internal.PrefabFormat - Attempting to deserialize prefab ShatteredPlanes:easterEgg with inputs [/ShatteredPlanes/assets/prefabs/easterEgg.prefab]
09:53:39.220 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.StackOverflowError: null
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.write(Unknown Source)
	at java.io.PrintStream.write(Unknown Source)
	at java.io.FilterOutputStream.write(Unknown Source)
	at ch.qos.logback.core.joran.spi.ConsoleTarget$1.write(ConsoleTarget.java:37)
	at ch.qos.logback.core.OutputStreamAppender.writeBytes(OutputStreamAppender.java:199)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:231)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
	at ch.qos.logback.classic.Logger.info(Logger.java:587)
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:53)
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:36)
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292)
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180)
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228)
	at org.terasology.assets.AssetType.lambda$reload$2(AssetType.java:359)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.terasology.assets.AssetType.reload(AssetType.java:357)
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:386)
	at org.terasology.assets.AssetType.getAsset(AssetType.java:262)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:223)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:203)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:187)
	at org.terasology.utilities.Assets.get(Assets.java:80)
	at org.terasology.utilities.Assets.getPrefab(Assets.java:274)
	at org.terasology.persistence.typeHandling.extensionTypes.PrefabTypeHandler.getFromString(PrefabTypeHandler.java:43)
	at org.terasology.persistence.typeHandling.extensionTypes.PrefabTypeHandler.getFromString(PrefabTypeHandler.java:25)
	at org.terasology.persistence.typeHandling.StringRepresentationTypeHandler.deserialize(StringRepresentationTypeHandler.java:37)
	at org.terasology.persistence.typeHandling.TypeHandler.deserializeOrNull(TypeHandler.java:68)
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:96)
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:153)
	at org.terasology.persistence.serializers.ComponentSerializer.deserializeOnto(ComponentSerializer.java:197)
	at org.terasology.persistence.serializers.ComponentSerializer.deserialize(ComponentSerializer.java:114)
	at org.terasology.persistence.serializers.PrefabSerializer.applyComponentChanges(PrefabSerializer.java:164)
	at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:136)
	at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:116)
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:55)
	at org.terasology.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:36)
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292)
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180)
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228)
	at org.terasology.assets.AssetType.lambda$reload$2(AssetType.java:359)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.terasology.assets.AssetType.reload(AssetType.java:357)
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:386)
	at org.terasology.assets.AssetType.getAsset(AssetType.java:262)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:223)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:203)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:187)
	at org.terasology.utilities.Assets.get(Assets.java:80)
	at org.terasology.utilities.Assets.getPrefab(Assets.java:274)
	at org.terasology.persistence.typeHandling.extensionTypes.PrefabTypeHandler.getFromString(PrefabTypeHandler.java:43)
	at org.terasology.persistence.typeHandling.extensionTypes.PrefabTypeHandler.getFromString(PrefabTypeHandler.java:25)
	at org.terasology.persistence.typeHandling.StringRepresentationTypeHandler.deserialize(StringRepresentationTypeHandler.java:37)
	at org.terasology.persistence.typeHandling.TypeHandler.deserializeOrNull(TypeHandler.java:68)
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:96)
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:153)
	at org.terasology.persistence.serializers.ComponentSerializer.deserializeOnto(ComponentSerializer.java:197)
	at org.terasology.persistence.serializers.ComponentSerializer.deserialize(ComponentSerializer.java:114)
	at org.terasology.persistence.serializers.PrefabSerializer.applyComponentChanges(PrefabSerializer.java:164)
	at org.terasology.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:136)

```

**Comment by eviltak** [comment]
Looks like a recursive Asset/Prefab dependency (A component in prefab A refers to prefab B, and a component in prefab B refers to prefab A, or a longer loop). We could either modify the asset to remove the recursion, or we could add lazy or late loading of prefabs where we resolve the prefab using an `Asset.get` call only after all prefabs have been loaded.

**Comment by Cervator** [comment]
Hit it by chance again and reminded myself that the affected asset seems pretty clear even based on the log snippet above: `easterEgg.prefab` in ShatteredPlanes refers to itself as a StructureTemplate, which is kinda weird as it doesn't actually depend on the ST module. I think that the error only happens if the ST module is *also* enabled, as otherwise that part of the prefab just gets ignored (as the game doesn't know what an ST is if its module isn't enabled)

It would be nice to find a way to harden the engine to simply log a warning for a circular reference rather than crash. Although at least it crashes on startup not at some arbitrary point later in a game session.

To replicate: Define an asset that ends up referring to itself. Example `easterEgg.prefab` in ShatteredPlanes (adjust naming as needed for a different example):

```json
{
  "StructureTemplate": {
    "type": "ShatteredPlanes:easterEgg"
  }
}
```
