### ISSUE TITLE
Game crash when adding certain widgets using the NUI Screen Editor

### ISSUE THREAD

**Issue by BenjaminAmos** [MovingBlocks/Terasology#3826]
### What you were trying to do
I was attempting to use the NUI Screen Editor to edit a screen.

### What actually happened
The game crashed when certain widgets were added.

### How to reproduce
 - Open Terasology and start a new game.
 - Open the NUI Screen editor through the `In-Game Menu->Extras->Developer Tools->NUI Screen Editor` option.
 - Try adding one of the following widgets to a UI Screen (right-click on a "contents" button and select "Add Widget"):
    - `engine:DebugProperties`
    - `engine:UIRadialSection`
    - `engine:UIRadialRing`
    - `engine:HudToolbar`
    - `engine:BehaviorEditor`
 - There may be more widgets that cause these crashes, although most of the affected ones inherit from `CoreHudWidget`/`CoreScreenLayer`.
 - If a `UIRadialSection` was added, then the NUI editor may crash when re-opened after re-opening the game. You will need to delete the file `nuiEditorAutosave.json` in order to stop the crashes.
##### `CoreScreenLayer` Exception
```
java.lang.NullPointerException
	at org.terasology.rendering.nui.CoreScreenLayer.iterateThrough(CoreScreenLayer.java:132)
	at org.terasology.rendering.nui.CoreScreenLayer.iterateThrough(CoreScreenLayer.java:133)
	at org.terasology.rendering.nui.CoreScreenLayer.iterateThrough(CoreScreenLayer.java:133)
	at org.terasology.rendering.nui.CoreScreenLayer.iterateThrough(CoreScreenLayer.java:133)
	at org.terasology.rendering.nui.CoreScreenLayer.iterateThrough(CoreScreenLayer.java:133)
	at org.terasology.rendering.nui.CoreScreenLayer.update(CoreScreenLayer.java:223)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.update(NUIManagerInternal.java:524)
	at org.terasology.engine.modes.StateIngame.updateUserInterface(StateIngame.java:236)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:183)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:462)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:425)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:401)
	at org.terasology.engine.Terasology.main(Terasology.java:156)
```
##### `UIRadialRing` Exception
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.terasology.rendering.nui.widgets.UIRadialRing$1.onMouseOver(UIRadialRing.java:60)
	at org.terasology.rendering.nui.internal.CanvasImpl.processMousePosition(CanvasImpl.java:192)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.update(NUIManagerInternal.java:519)
	at org.terasology.engine.modes.StateIngame.updateUserInterface(StateIngame.java:236)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:183)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:462)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:425)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:401)
	at org.terasology.engine.Terasology.main(Terasology.java:156)
```
##### `UIRadialSection` Exception:
```
java.lang.NullPointerException
	at org.terasology.rendering.nui.internal.Line.relativeToAbsolute(Line.java:319)
	at org.terasology.rendering.nui.internal.CanvasImpl.relativeToAbsolute(CanvasImpl.java:758)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawTextureRaw(CanvasImpl.java:618)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawTextureRaw(CanvasImpl.java:613)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawTextureRaw(CanvasImpl.java:596)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawTexture(CanvasImpl.java:470)
	at org.terasology.rendering.nui.widgets.UIRadialSection.onDraw(UIRadialSection.java:88)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:425)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:411)
	at org.terasology.rendering.nui.layouts.relative.RelativeLayout.onDraw(RelativeLayout.java:85)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:425)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:411)
	at org.terasology.rendering.nui.CoreScreenLayer.onDraw(CoreScreenLayer.java:211)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:425)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:411)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:387)
	at org.terasology.rendering.nui.widgets.UIBox.onDraw(UIBox.java:41)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:425)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:411)
	at org.terasology.rendering.nui.layouts.miglayout.MigLayout.onDraw(MigLayout.java:128)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:425)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:411)
	at org.terasology.rendering.nui.CoreScreenLayer.onDraw(CoreScreenLayer.java:211)
	at org.terasology.rendering.nui.editor.layers.AbstractEditorScreen.onDraw(AbstractEditorScreen.java:160)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:425)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:411)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.render(NUIManagerInternal.java:509)
	at org.terasology.engine.modes.StateIngame.renderUserInterface(StateIngame.java:231)
	at org.terasology.engine.modes.StateIngame.render(StateIngame.java:215)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:166)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:471)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:425)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:401)
	at org.terasology.engine.Terasology.main(Terasology.java:156)
```
This has been reproduced on the commit https://github.com/MovingBlocks/Terasology/commit/4e95d495f21d5a687a48d1edb0f389fb66d7e1cc.

**Comment by casals** [comment]
I was able to replicate the scenario using both newly created games and pre-existing games. However, I observed that the error only started presenting itself when I tried to add the `engine:HudToolbar` widget. 

Before that, I was able to add `engine:UIRadialSection` and `engine:BehaviorEditor` to both newly created and pre-existing games without any errors whatsoever. This promped me to start testing all the components on @BenjaminAmos's list. After getting the error for the first time (with `engine:HudToolbar`), however, I started getting the same error again with all the widgets on the reported list (even when running the previous scenarios that hadn't presented any errors before - the ones using `engine:UIRadialSection` and `engine:BehaviorEditor`). 

I observed that even with the game crashing, the new component was still present in the interface as I loaded it through the NUI editor (all the widgets I tried to add were there - so I could observe multiple references to the same widget within the same button component). So I created a second workspace and verified that the conditions for the error were consistent: everything went well until I added `engine:HudToolbar`. I verified that removing this widget from the UI prevents the error to being triggeres, which leads me to suspect there's where the problem lies. I used the `Inventory:containerScreen` NUI during these tests.
