### ISSUE TITLE
Harden against "Cannot set a changed component with a null component variable"

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#4135]
### What you were trying to do

Various things - this is a somewhat common error

One replication routine: while testing #4131 I would fly up in the air with WildAnimals enabled and place a deer (`spawnPrefab deer`) perilously close to an edge of some sort, be it a handy tree or a constructed plank, then undermine said support so the poor deer falls to its demise. This would crash a server without #4131 merged. With that fix in place I'd just expect a nice calm and absolutely humane and painless deer death.

### What actually happened

Get an angry stacktrace probably as an involved entity, event, or scheduled regen tick tries to do something past a point where they probably aren't relevant anymore

My closest suspicion would be that some sort of entity cleanup isn't fully happening. But as noted we've seen this regularly in different cases so it is hard to say if some hardened code or improved cleanup would resolve it. But at least there's an easy replicate scenario. Well, easy, unless your heart breaks at the thought of mercilessly sending a deer to the great beyond.

### How to reproduce

* Run game with a Perlin world and WildAnimals active (may have to be hosting multiplayer? But no second client needed)
* Put a deer on an edge high above the ground somehow (find/make a good spot then point right above it and `spawnPrefab deer`)
* Dig out blocks the peaceful innocent little deer is standing on, you monster!
* Watch the log for errors and heartbreak

### Log details and game version

I didn't notice at first that this may have spanned an auto-save trigger? Maybe that's involved somehow?

```
2:39:22.712 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Creating game snapshot
22:39:22.725 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
22:39:22.870 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.RuntimeException: Cannot set a changed component with a null component variable
	at org.terasology.persistence.internal.EntityDelta.setChangedComponent(EntityDelta.java:34)
	at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentChange(EntitySetDeltaRecorder.java:70)
	at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentAdded(EntitySetDeltaRecorder.java:61)
	at org.terasology.persistence.internal.ReadWriteStorageManager.onEntityComponentAdded(ReadWriteStorageManager.java:514)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.notifyComponentAdded(PojoEntityManager.java:723)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.addComponent(PojoEntityManager.java:566)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.addComponent(BaseEntityRef.java:168)
	at org.terasology.logic.health.RegenAuthoritySystem.onRegenAddedWithoutComponent(RegenAuthoritySystem.java:177)
	at org.terasology.logic.health.RegenAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:531)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:291)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:282)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.logic.health.DamageAuthoritySystem.doDamage(DamageAuthoritySystem.java:106)
	at org.terasology.logic.health.DamageAuthoritySystem.checkDamage(DamageAuthoritySystem.java:135)
	at org.terasology.logic.health.DamageAuthoritySystem.highSpeedDamage(DamageAuthoritySystem.java:208)
	at org.terasology.logic.health.DamageAuthoritySystem.onLand(DamageAuthoritySystem.java:186)
	at org.terasology.logic.health.DamageAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:531)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:291)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:282)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.logic.characters.KinematicCharacterMover.walk(KinematicCharacterMover.java:663)
	at org.terasology.logic.characters.KinematicCharacterMover.updatePosition(KinematicCharacterMover.java:570)
	at org.terasology.logic.characters.KinematicCharacterMover.step(KinematicCharacterMover.java:104)
	at org.terasology.logic.characters.ServerCharacterPredictionSystem.stepState(ServerCharacterPredictionSystem.java:191)
	at org.terasology.logic.characters.ServerCharacterPredictionSystem.onPlayerInput(ServerCharacterPredictionSystem.java:143)
	at org.terasology.logic.characters.ServerCharacterPredictionSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:531)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:291)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:282)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.minion.move.MoveToAction.processDirect(MoveToAction.java:94)
	at org.terasology.minion.move.MoveToAction.modify(MoveToAction.java:56)
	at org.terasology.logic.behavior.core.ActionNode.execute(ActionNode.java:78)
	at org.terasology.logic.behavior.core.SequenceNode.execute(SequenceNode.java:56)
	at org.terasology.logic.behavior.actions.LookupAction.modify(LookupAction.java:53)
	at org.terasology.logic.behavior.core.ActionNode.execute(ActionNode.java:78)
	at org.terasology.logic.behavior.core.SequenceNode.execute(SequenceNode.java:56)
	at org.terasology.logic.behavior.actions.LookupAction.modify(LookupAction.java:53)
	at org.terasology.logic.behavior.core.ActionNode.execute(ActionNode.java:78)
	at org.terasology.logic.behavior.core.DelegateNode.execute(DelegateNode.java:91)
	at org.terasology.logic.behavior.DefaultBehaviorTreeRunner$1.execute(DefaultBehaviorTreeRunner.java:64)
	at org.terasology.logic.behavior.core.DynamicSelectorNode.execute(DynamicSelectorNode.java:54)
	at org.terasology.logic.behavior.core.DelegateNode.execute(DelegateNode.java:91)
	at org.terasology.logic.behavior.DefaultBehaviorTreeRunner$1.execute(DefaultBehaviorTreeRunner.java:64)
	at org.terasology.logic.behavior.DefaultBehaviorTreeRunner.step(DefaultBehaviorTreeRunner.java:84)
	at org.terasology.logic.behavior.Interpreter.tick(Interpreter.java:73)
	at org.terasology.logic.behavior.BehaviorSystem.update(BehaviorSystem.java:105)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:171)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:468)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:431)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:407)
	at org.terasology.engine.Terasology.main(Terasology.java:182)
22:39:23.911 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
```

### Poor Deer

![PoorDeer](https://user-images.githubusercontent.com/1063833/90970446-bf2ac780-e4ca-11ea-8b99-4ab72bd40dfa.png)

**Comment by Cervator** [comment]
Here's another variant that happened while setting up MetalRenegades (plus CheatsForAll and HumanoidCharacters) on a headless server, then on first client connection the server crashed with the following in the log:

```
04:09:46.457 [New I/O worker #3] INFO  o.t.n.i.ServerHandshakeHandler - Received client certificate
04:09:46.458 [New I/O worker #3] INFO  o.t.n.i.ServerHandshakeHandler - Sending server verification
04:09:46.746 [New I/O worker #3] INFO  o.t.n.i.ServerConnectionHandler - Received Start Join
04:09:46.789 [main] INFO  o.t.n.internal.NetworkSystemImpl - New client entity: EntityRef{id = 387, netId = 340, prefab = 'engine:client'}
04:09:47.539 [Chunk-Generator-5] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[freeform,CoreAssets:DiamondOre]
04:09:47.539 [Chunk-Generator-5] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block CoreAssets:DiamondOre with id 170
04:09:47.598 [Chunk-Generator-3] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[freeform,CoreAssets:IronOre]
04:09:47.598 [Chunk-Generator-3] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block CoreAssets:IronOre with id 171
04:09:47.668 [Chunk-Generator-5] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[freeform,CoreAssets:GoldOre]
04:09:47.669 [Chunk-Generator-5] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block CoreAssets:GoldOre with id 172
04:09:47.689 [Chunk-Generator-5] INFO  o.t.w.b.internal.BlockManagerImpl - Registered BlockFamily[freeform,CoreAssets:CopperOre]
04:09:47.690 [Chunk-Generator-5] INFO  o.t.w.b.internal.BlockManagerImpl - Registered Block CoreAssets:CopperOre with id 173
04:09:49.360 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.network.NetworkComponent added to EntityRef{id = 393, netId = 346}
04:09:49.360 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.logic.location.LocationComponent added to EntityRef{id = 393, netId = 346}
04:09:49.361 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.RuntimeException: Cannot set a changed component with a null component variable
        at org.terasology.persistence.internal.EntityDelta.setChangedComponent(EntityDelta.java:34)
        at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentChange(EntitySetDeltaRecorder.java:70)
        at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentAdded(EntitySetDeltaRecorder.java:61)
        at org.terasology.persistence.internal.ReadWriteStorageManager.onEntityComponentAdded(ReadWriteStorageManager.java:514)
        at org.terasology.entitySystem.entity.internal.PojoEntityManager.notifyComponentAdded(PojoEntityManager.java:723)
        at org.terasology.entitySystem.entity.internal.PojoEntityManager.addComponent(PojoEntityManager.java:566)
        at org.terasology.entitySystem.entity.internal.BaseEntityRef.addComponent(BaseEntityRef.java:168)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.generateQueuedEntities(LocalChunkProvider.java:242)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.generateQueuedEntities(LocalChunkProvider.java:224)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.processReadyChunk(LocalChunkProvider.java:181)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.completeUpdate(LocalChunkProvider.java:173)
        at org.terasology.engine.subsystem.headless.renderer.HeadlessWorldRenderer.update(HeadlessWorldRenderer.java:104)
        at org.terasology.engine.modes.StateIngame.update(StateIngame.java:176)
        at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:472)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:435)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:411)
        at org.terasology.engine.Terasology.main(Terasology.java:155)
04:09:49.361 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
04:09:49.498 [main] ERROR o.t.l.debug.ChunkEventErrorLogger - Unload event for not loaded chunk (0, 0, 0)
04:09:49.516 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
04:09:49.523 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
04:09:49.538 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Cervator
04:09:49.542 [main] INFO  o.t.n.internal.NetworkSystemImpl - Network shutdown
04:09:49.666 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
java.lang.RuntimeException: Cannot set a changed component with a null component variable
        at org.terasology.persistence.internal.EntityDelta.setChangedComponent(EntityDelta.java:34)
        at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentChange(EntitySetDeltaRecorder.java:70)
        at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentAdded(EntitySetDeltaRecorder.java:61)
        at org.terasology.persistence.internal.ReadWriteStorageManager.onEntityComponentAdded(ReadWriteStorageManager.java:514)
        at org.terasology.entitySystem.entity.internal.PojoEntityManager.notifyComponentAdded(PojoEntityManager.java:723)
        at org.terasology.entitySystem.entity.internal.PojoEntityManager.addComponent(PojoEntityManager.java:566)
        at org.terasology.entitySystem.entity.internal.BaseEntityRef.addComponent(BaseEntityRef.java:168)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.generateQueuedEntities(LocalChunkProvider.java:242)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.generateQueuedEntities(LocalChunkProvider.java:224)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.processReadyChunk(LocalChunkProvider.java:181)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.completeUpdate(LocalChunkProvider.java:173)
        at org.terasology.engine.subsystem.headless.renderer.HeadlessWorldRenderer.update(HeadlessWorldRenderer.java:104)
        at org.terasology.engine.modes.StateIngame.update(StateIngame.java:176)
        at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:472)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:435)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:411)
```

May be easy to reproduce if the seed generates a world that triggers whatever immediately? If so this should do the trick (in `override.cfg`):

```
{
  "defaultModSelection": {
    "modules": [
      "CheatsForAll",
      "HumanoidCharacters",
      "MetalRenegades"
    ],
    "defaultGameplayModuleName": "MetalRenegades"
  },
  "worldGeneration": {
    "worldTitle": "September2020",
    "defaultSeed": "Vq1tAcQAe9cpt2FAHgkZssdfgdfgk7Kr7BEBS2qsdfgsdfg",
    "defaultGenerator": "MetalRenegades:dynamicWorld"
  }
}
```

**Comment by Cervator** [comment]
Another use case: I ran with GooeysQuests + WildAnimals + MawGooey, spawned a deer (`spawnPrefab deer`), each time I hit it I got a usual sort of stacktrace. Something to do with the damaging action.

```
	at org.terasology.engine.Terasology.main(Terasology.java:182)
22:23:25.006 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.RuntimeException: Cannot set a changed component with a null component variable
	at org.terasology.persistence.internal.EntityDelta.setChangedComponent(EntityDelta.java:34)
	at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentChange(EntitySetDeltaRecorder.java:70)
	at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentAdded(EntitySetDeltaRecorder.java:61)
	at org.terasology.persistence.internal.ReadWriteStorageManager.onEntityComponentAdded(ReadWriteStorageManager.java:514)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.notifyComponentAdded(PojoEntityManager.java:723)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.addComponent(PojoEntityManager.java:566)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.addComponent(BaseEntityRef.java:168)
	at org.terasology.logic.health.RegenAuthoritySystem.onRegenAddedWithoutComponent(RegenAuthoritySystem.java:177)
	at org.terasology.logic.health.RegenAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:532)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:292)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:283)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.logic.health.DamageAuthoritySystem.doDamage(DamageAuthoritySystem.java:106)
	at org.terasology.logic.health.DamageAuthoritySystem.checkDamage(DamageAuthoritySystem.java:135)
	at org.terasology.logic.health.DamageAuthoritySystem.onDamage(DamageAuthoritySystem.java:123)
	at org.terasology.logic.health.DamageAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:532)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:292)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:283)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.logic.health.DamageAuthoritySystem.damageEntity(DamageAuthoritySystem.java:91)
	at org.terasology.logic.health.DamageAuthoritySystem.onAttackEntity(DamageAuthoritySystem.java:76)
	at org.terasology.logic.health.DamageAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:532)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:302)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:281)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.logic.characters.CharacterSystem.onAttackRequest(CharacterSystem.java:243)
	at org.terasology.logic.characters.CharacterSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:532)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:292)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:283)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.logic.characters.CharacterSystem.onAttackRequest(CharacterSystem.java:211)
	at org.terasology.logic.characters.CharacterSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:532)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:302)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:281)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.input.internal.BindableButtonImpl.update(BindableButtonImpl.java:210)
	at org.terasology.input.InputSystem.processBindRepeats(InputSystem.java:414)
	at org.terasology.input.InputSystem.update(InputSystem.java:139)
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:192)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:55)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:488)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:442)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:418)
	at org.terasology.engine.Terasology.main(Terasology.java:182)
22:23:25.206 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.RuntimeException: Cannot set a changed component with a null component variable
```

**Comment by Cervator** [comment]
Closing as fixed (at least partially? Deer scenario for sure) by #4254
