### ISSUE TITLE
Mystery rendering issue - missing block faces

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#4143]
### What you were trying to do

Test assorted things. This issue has been seen somewhat rarely but in a wide variety of cases. I'm skeptical that it relates to modules active although it _may_ relate to the number of blocks enabled or something? Probably still unlikely.

I flew around the world some until I saw what appeared to be a tree top without a crown at all, no leaves. Flew up toward the spot where the tree trunk appeared to end, wondering if it was a chunk border issue meaning nothing had generated in the next chunk up.

### What actually happened

My player got hopelessly stuck when I entered the space that was seemingly not rendering stuff. Felt like when a chunk is broken / stuck unloaded in multiplayer, not just waiting to be made visible (but still having a mesh). Could look around but not move, even with `ghost` on. Noticed missing block faces on just some nearby trees, but not at all neatly following chunk borders.

I enabled one of the rendering debug modes for a second screenie and while at first it looked like it might have been showing leaf blocks in a mesh above my head after relogging it seemed more clearly to just be distant chunks. It looked like the chunk edge was _near_ where the tree trunk ended, but possibly not right at the same level.

On exiting to the main menu the missing block faces persisted on the saved game preview screenie.

On re-entering the same world the mystery was gone and all blocks were visible normally again

### How to reproduce

* Unknown :-(

This time it happened in single player, but we've seen it in multiplayer as well. Making this issue to better track symptoms, as I think we've observed things like one player seeing it, yet another player seeing everything perfectly fine in the same spot. Relogging may fix? But with it happening in single player it isn't like a server is just failing to send some stuff. It seems to be a rendering quirk, yet at times by getting stuck also seems to be a fundamental chunk problem.

### Logging

Only clue in the log was an instance of #4135 but that sounded more likely to be about a deer, maybe randomly taking fall damage, either naturally or via server prediction oddly? Strange thing to see for a deer in single player ..:

```
21:57:50.190 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
21:58:50.225 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Creating game snapshot
21:58:50.227 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
21:59:30.110 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.RuntimeException: Cannot set a changed component with a null component variable
	at org.terasology.persistence.internal.EntityDelta.setChangedComponent(EntityDelta.java:34)
	at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentChange(EntitySetDeltaRecorder.java:70)
	at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentAdded(EntitySetDeltaRecorder.java:61)
	at org.terasology.persistence.internal.ReadWriteStorageManager.onEntityComponentAdded(ReadWriteStorageManager.java:514)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.notifyComponentAdded(PojoEntityManager.java:723)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.addComponent(PojoEntityManager.java:566)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.addComponent(BaseEntityRef.java:168)
	at org.terasology.logic.health.RegenAuthoritySystem.onRegenAddedWithoutComponent(RegenAuthoritySystem.java:177)
	at org.terasology.logic.health.RegenAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:532)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:292)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:283)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.logic.health.DamageAuthoritySystem.doDamage(DamageAuthoritySystem.java:106)
	at org.terasology.logic.health.DamageAuthoritySystem.checkDamage(DamageAuthoritySystem.java:135)
	at org.terasology.logic.health.DamageAuthoritySystem.highSpeedDamage(DamageAuthoritySystem.java:208)
	at org.terasology.logic.health.DamageAuthoritySystem.onLand(DamageAuthoritySystem.java:186)
	at org.terasology.logic.health.DamageAuthoritySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:532)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:292)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:283)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.logic.characters.KinematicCharacterMover.walk(KinematicCharacterMover.java:663)
	at org.terasology.logic.characters.KinematicCharacterMover.updatePosition(KinematicCharacterMover.java:570)
	at org.terasology.logic.characters.KinematicCharacterMover.step(KinematicCharacterMover.java:104)
	at org.terasology.logic.characters.ServerCharacterPredictionSystem.stepState(ServerCharacterPredictionSystem.java:191)
	at org.terasology.logic.characters.ServerCharacterPredictionSystem.onPlayerInput(ServerCharacterPredictionSystem.java:143)
	at org.terasology.logic.characters.ServerCharacterPredictionSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:532)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:292)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:283)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.minion.move.MoveToAction.processDirect(MoveToAction.java:81)
	at org.terasology.minion.move.MoveToAction.modify(MoveToAction.java:43)
	at org.terasology.logic.behavior.core.ActionNode.execute(ActionNode.java:81)
	at org.terasology.logic.behavior.core.SequenceNode.execute(SequenceNode.java:56)
	at org.terasology.logic.behavior.actions.LookupAction.modify(LookupAction.java:53)
	at org.terasology.logic.behavior.core.ActionNode.execute(ActionNode.java:81)
	at org.terasology.logic.behavior.core.SequenceNode.execute(SequenceNode.java:56)
	at org.terasology.logic.behavior.actions.LookupAction.modify(LookupAction.java:53)
	at org.terasology.logic.behavior.core.ActionNode.execute(ActionNode.java:81)
	at org.terasology.logic.behavior.core.DynamicSelectorNode.execute(DynamicSelectorNode.java:54)
	at org.terasology.logic.behavior.actions.LookupAction.modify(LookupAction.java:53)
	at org.terasology.logic.behavior.core.ActionNode.execute(ActionNode.java:81)
	at org.terasology.logic.behavior.core.DelegateNode.execute(DelegateNode.java:91)
	at org.terasology.logic.behavior.DefaultBehaviorTreeRunner$1.execute(DefaultBehaviorTreeRunner.java:64)
	at org.terasology.logic.behavior.core.DynamicSelectorNode.execute(DynamicSelectorNode.java:54)
	at org.terasology.logic.behavior.core.DelegateNode.execute(DelegateNode.java:91)
	at org.terasology.logic.behavior.DefaultBehaviorTreeRunner$1.execute(DefaultBehaviorTreeRunner.java:64)
	at org.terasology.logic.behavior.DefaultBehaviorTreeRunner.step(DefaultBehaviorTreeRunner.java:84)
	at org.terasology.logic.behavior.Interpreter.tick(Interpreter.java:73)
	at org.terasology.logic.behavior.BehaviorSystem.update(BehaviorSystem.java:105)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:171)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:472)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:435)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:411)
	at org.terasology.engine.Terasology.main(Terasology.java:182)
```

### Screenie

![image](https://user-images.githubusercontent.com/1063833/92317172-8f4beb80-efc3-11ea-8276-becb0b930053.png)

With one of the debug rendering modes active:

![image](https://user-images.githubusercontent.com/1063833/92317179-baced600-efc3-11ea-9776-838863bf82f6.png)

**Comment by DarkWeird** [comment]
Reproduce: restart game many times :3

It is not loaded chunk(not ready on server ). I don't know why it is happens. It is not throws any exception.

I hope that #4140 helps with it.

**Comment by 4Denthusiast** [comment]
I agree with Darkweird that this is just an entire missing chunk, not individual missing faces. I thought we had an issue for that already, but I can't find it.

It seems to show up more frequently with the render distance set to low, and also when FallingBlocks is active, presumably because it slows down chunk loading a bit. It's still possible to interact with the non-rendered chunks: you can walk around them and break their blocks and things, but even though breaking a block in a chunk should normally trigger a re-generation of its mesh, in this case it doesn't and the chunk remains invisible.

**Comment by Cervator** [comment]
For this particular screenie it might be both? One entirely missing / unloaded chunk (reason why I got stuck on it where the one tree just stopped existing) while the busted blocks on the left are mid-chunk? That seems more like a messed up chunk mesh where the right block faces aren't rendering?

While I wasn't able to move over there to investigate (since it was fixed by a reload) I couldn't confirm, but I expect like you say 4D that I could have interacted with the blocks and so on in that messed up block area. The blocks are _there_ (that particular chunk isn't missing) they're just not rendering right, somehow 🤔 While the spot where I froze in the screenie was on the bottom edge of a completely missing chunk.

**Comment by 4Denthusiast** [comment]
> For this particular screenie it might be both? One entirely missing / unloaded chunk (reason why I got stuck on it where the one tree just stopped existing) while the busted blocks on the left are mid-chunk?

It's hard to tell from just the screenshot, especially without knowing exactly what shape the tree is meant to be, but I think the area where lots of isolated little bits render is just because of back-face culling. You're seeing that side of the tree from behind through the missing chunk, so only the relatively few faces that happen to be facing you anyway get rendered. If you can find an example of random individual faces missing where you're viewing it from in front (and it's clearly not just a slight intersection of the blocks' surface with a missing chunk), that would be more convincing that your explanation is correct.

**Comment by Cervator** [comment]
Fair enough :-) I wasn't able to get close to it this time, although at other times I've been able to move around similar mystery spots. Will keep an eye out for better screenies - unless it turns out merging #4140 ends up making this disappear as well (or I could have just been seeing things)

**Comment by 4Denthusiast** [comment]
I think #4353 fixes this.
