### ISSUE TITLE
Stackoverflow from TypeHandler / ThreadPoolExecutor$Worker in GooeyDefence

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#4215]
### What actually happened

Test unrelated bits, ran GooeyDefence, let one wave hit the vault, ghosted through the outer wall to look around, floated back toward the shrine, game suddenly crashed. Maybe of interest to @DarkWeird / @keturn (TaskManager stuff?) or @eviltak (type handling)

I tried it a second time and it took a bit longer (actually lost the game, restarted, and triggered another new wave then waited a bit), but it did happen again. Chunks were kinda wonky and I got stuck in an unloaded one that time (just did `teleport 40 40 40` and I was free again near spawn)

### How to reproduce

* Start game
* Run GooeyDefence
* `e` click the central shrine and trigger a wave
* Wait - or maybe move around a bit

### Log details and game version

Latest develop including LWJGL merge (highly unlikely to relate?) as of this submission.

Game started up with a bunch of "Position is out of chunks" messages (#4214) but that stabilized.

```
...
4:18:50.351 [Chunk-Processing-5] WARN  o.t.world.propagation.LocalChunkView - Position is out of chunks
14:18:50.351 [Chunk-Processing-5] WARN  o.t.world.propagation.LocalChunkView - Position is out of chunks
14:19:17.286 [main] INFO  o.t.logic.console.ConsoleImpl - [CONSOLE] Welcome to the wonderful world of Terasology!

Type 'help' to see a list with available commands or 'help <commandName>' for command details.
Text parameters do not need quotes, unless containing spaces. No commas between parameters.
You can use auto-completion by typing a partial command then hitting [tab] - examples:

gh + [tab] => 'ghost'
help gh + [tab] => 'help ghost' (can auto complete commands fed to help)
giv + [tab] => 'give givePermission' (use [tab] again to cycle between choices)
lS + [tab] => 'listShapes' (camel casing abbreviated commands)

14:19:18.245 [main] INFO  o.t.logic.console.ConsoleImpl - [CONSOLE] Ghost mode toggled
14:19:32.933 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Creating game snapshot
14:19:32.940 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
14:19:33.072 [Saving-0] WARN  o.t.p.t.c.RuntimeDelegatingTypeHandler - Could not find appropriate TypeHandler for runtime type 'class java.util.concurrent.ThreadPoolExecutor$Worker', serializing as base type 'class java.util.concurrent.ThreadPoolExecutor$Worker'
14:19:33.193 [Saving-0] ERROR o.t.p.t.c.RuntimeDelegatingTypeHandler - Base type 'class java.util.concurrent.ThreadPoolExecutor$Worker' does not have a handler
...
14:19:33.224 [Saving-0] ERROR o.t.p.t.c.ObjectFieldMapTypeHandler - Likely circular reference in field private java.lang.ThreadGroup java.lang.Thread.group.
14:19:33.224 [Saving-0] ERROR o.t.p.t.c.ObjectFieldMapTypeHandler - Likely circular reference in field java.lang.Thread[] java.lang.ThreadGroup.threads.
14:19:33.225 [Saving-0] ERROR o.t.p.t.c.ObjectFieldMapTypeHandler - Likely circular reference in field private java.lang.ThreadGroup java.lang.Thread.group.
14:19:33.225 [Saving-0] ERROR o.t.p.t.c.ObjectFieldMapTypeHandler - Likely circular reference in field java.lang.Thread[] java.lang.ThreadGroup.threads.
14:19:33.225 [Saving-0] ERROR o.t.p.t.c.ObjectFieldMapTypeHandler - Likely circular reference in field private final java.lang.ThreadGroup java.lang.ThreadGroup.parent.
14:19:33.225 [Saving-0] ERROR o.t.p.t.c.ObjectFieldMapTypeHandler - Likely circular reference in field private final java.lang.ThreadGroup java.util.concurrent.Executors$DefaultThreadFactory.group.
14:19:33.225 [Saving-0] ERROR o.t.p.t.c.ObjectFieldMapTypeHandler - Likely circular reference in field private volatile java.util.concurrent.ThreadFactory java.util.concurrent.ThreadPoolExecutor.threadFactory.
14:19:33.225 [Saving-0] ERROR o.t.p.t.c.ObjectFieldMapTypeHandler - Likely circular reference in field private java.util.concurrent.ExecutorService org.terasology.utilities.concurrency.TaskMaster.executorService.
14:19:33.225 [Saving-0] ERROR o.t.p.t.c.ObjectFieldMapTypeHandler - Likely circular reference in field private org.terasology.utilities.concurrency.TaskMaster org.terasology.flexiblepathfinding.PathfinderSystem.workerTaskMaster.
14:19:33.225 [Saving-0] ERROR o.t.p.t.c.ObjectFieldMapTypeHandler - Likely circular reference in field private org.terasology.flexiblepathfinding.PathfinderSystem org.terasology.gooeyDefence.movement.PathfindingManager.pathfinderSystem.
14:19:33.240 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.StackOverflowError: null
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:248)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
	at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:293)
	at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:206)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:223)
	at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:235)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.sift.SiftingAppenderBase.append(SiftingAppenderBase.java:110)
	at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:82)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:398)
	at ch.qos.logback.classic.Logger.error(Logger.java:526)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:77)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeViaDelegate(RuntimeDelegatingTypeHandler.java:162)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:118)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:72)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
...
```

**Comment by eviltak** [comment]
This looks like another case of a missing `transient` modifier in the field. From the logs, I would suggest that either the `PathfinderSystem.workerTaskMaster` field or the `TaskMaster.executorService' field needs to be `transient`.
