### ISSUE TITLE
[playets] crash: NoSuchMethodError on ImageFlowRenderer

### ISSUE THREAD

**Issue by skaldarnar** [MovingBlocks/Terasology#4265]
A user reported a crash due to a `NoSuchmethodError` in `ImageFlowRenderable` while playing Josharias Survival. Seems pretty odd, as the file hasn't been touched for some time now...

https://github.com/MovingBlocks/Terasology/blob/428218119aa46f6fef43509c70bab11afa206a25/engine/src/main/java/org/terasology/rendering/nui/widgets/browser/data/basic/flow/ImageFlowRenderable.java#L29-L45

Error message:

```log
12:43:21.130 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NoSuchMethodError: 'void org.terasology.rendering.nui.widgets.browser.data.basic.flow.ImageFlowRenderable.<init>(org.terasology.rendering.assets.texture.TextureRegion, java.lang.Integer, java.lang.Integer, java.lang.String)'
	at org.terasology.workstationInGameHelp.systems.InputProcessesHelpItem.getWorkStationProcessParagraphData(InputProcessesHelpItem.java:124)
	at org.terasology.workstationInGameHelp.systems.OutputProcessesHelpItem.getParagraphs(OutputProcessesHelpItem.java:100)
	at org.terasology.inGameHelpAPI.components.HelpItem.addHelpItemSection(HelpItem.java:51)
	at org.terasology.inGameHelp.helpCategories.ItemsCategory.initialise(ItemsCategory.java:133)
	at org.terasology.inGameHelp.helpCategories.ItemsCategory.handleNavigate(ItemsCategory.java:187)
	at org.terasology.inGameHelp.ui.InGameHelpScreen.navigateTo(InGameHelpScreen.java:78)
	at org.terasology.inGameHelp.systems.InGameHelpClientSystem.showHelpForHyperlink(InGameHelpClientSystem.java:85)
	at org.terasology.machines.ui.DefaultMachineWindow.lambda$layoutOutputItems$0(DefaultMachineWindow.java:195)
	at org.terasology.machines.ui.OverlapLayout.activate(OverlapLayout.java:97)
	at org.terasology.machines.ui.OverlapLayout.access$000(OverlapLayout.java:20)
	at org.terasology.machines.ui.OverlapLayout$1.onMouseClick(OverlapLayout.java:89)
	at org.terasology.nui.canvas.CanvasImpl.processMouseClick(CanvasImpl.java:243)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:642)
	at org.terasology.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:532)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:302)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:281)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:205)
	at org.terasology.input.InputSystem.send(InputSystem.java:505)
	at org.terasology.input.InputSystem.sendMouseEvent(InputSystem.java:478)
	at org.terasology.input.InputSystem.processMouseButtonInput(InputSystem.java:221)
	at org.terasology.input.InputSystem.processMouseInput(InputSystem.java:200)
	at org.terasology.input.InputSystem.update(InputSystem.java:136)
	at org.terasology.engine.modes.StateIngame.handleInput(StateIngame.java:192)
	at org.terasology.engine.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:55)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:481)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:435)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:411)
	at org.terasology.engine.Terasology.main(Terasology.java:182)
```

**Comment by Kbearbear** [comment]
My hammer got thanos snapped :C

**Comment by Cervator** [comment]
Duplicate of #4208 but maybe we should leave it open until the next stable release. Fixed in the dev builds.

@Kbearbear: hopefully you've been able to get a dev build working, you can use the in-game console to retrieve items lost to bugs 👍
