### ISSUE TITLE
groovyw lib list NullPointerException

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4331]
### What you were trying to do

Find out which libraries groovyw knows about with `groovyw lib list`

### What actually happened

```
Caught: java.lang.NullPointerException: Cannot invoke method contains() on null object
java.lang.NullPointerException: Cannot invoke method contains() on null object
	at common$_retrieveAvailableItems_closure9.doCall(common.groovy:409)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at common.retrieveAvailableItems(common.groovy:400)
	at common$retrieveAvailableItems$0.call(Unknown Source)
	at util.run(util.groovy:157
```

that line 409 is here:

https://github.com/MovingBlocks/Terasology/blob/5cfb0c66f5457d16cffe1246a697314ccc1cd328/config/groovy/common.groovy#L407-L412

working from `develop` at 5cfb0c66f5457d16cffe1246a697314ccc1cd328

**Comment by Cervator** [comment]
Aha, interesting catch. I will not pretend this is among any of my best coding, although with the amount of coding I've been doing for the last few years ... maybe it still is, somehow 😅 

The `groovyw` commands really were intended for modules, then the other types were thrown in as an afterthought, more or less. Modules always hit more than one page with the limit of 99 items since we've been past that count of repos under the Terasology org for years. However the MovingBlocks org is below that so there's no "next" page link to find. Thus the crash.

Fairly easy to just throw an added guard in there so it'll stop either on the pagination resetting to 1 or there not being a "next" link on the page at all. But it is still cruddy code (see all the TODOs), and with a little luck we'll replace it all within _too_ long.
