### ISSUE TITLE
Occasional chunk gen failure in cancelling something ceases all generation

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#4369]
Noted this several times testing MetalRenegades, both before and after #4368. Easy to provoke by flying around like a mad person with `hspeed` and `ghost` in MR (on a decently beefy system with 3gb ram assigned via `gradlew jar game`)

Theory: If chunk generation can't keep up and the player leaves an area not yet generated that now becomes irrelevant for chunk gen (out of range) then something can happen (or always happens?) that throws an exception when trying to cancel the chunk gen request. As a consequence all chunks stop generating.

Example 1:

```11:19:30.307 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Creating game snapshot
11:19:30.308 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
11:19:31.617 [Saving-0] INFO  o.t.p.internal.SaveTransaction - Save game finished
Exception in thread "Chunk-Processing-Reactor" java.util.concurrent.CancellationException
        at java.util.concurrent.FutureTask.report(FutureTask.java:121)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.terasology.world.chunks.pipeline.PositionFuture.get(PositionFuture.java:49)
        at org.terasology.world.chunks.pipeline.ChunkProcessingPipeline.onStageDone(ChunkProcessingPipeline.java:121)
        at org.terasology.world.chunks.pipeline.ChunkProcessingPipeline.chunkTaskHandler(ChunkProcessingPipeline.java:108)
        at java.lang.Thread.run(Thread.java:745)
11:19:38.205 [main] ERROR o.t.e.e.internal.PojoEntityManager - Adding a component (class org.terasology.network.NetworkComponent) over an existing component for entity 2577
11:19:38.592 [main] INFO  o.t.d.construction.BlockBufferSystem - Buffer before: 162, Placed: 162, Removed: 162, Buffer after: 0
```

Example 2

```
11:21:24.071 [main] INFO  o.t.logic.console.ConsoleImpl - [CONSOLE] High-speed mode activated
11:21:27.207 [main] ERROR o.t.p.t.TypeHandlerLibrary - Unsupported field: 'DynamicCities:TreeFacet.relData'
Exception in thread "Chunk-Processing-Reactor" java.util.concurrent.CancellationException
        at java.util.concurrent.FutureTask.report(FutureTask.java:121)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.terasology.world.chunks.pipeline.PositionFuture.get(PositionFuture.java:49)
        at org.terasology.world.chunks.pipeline.ChunkProcessingPipeline.onStageDone(ChunkProcessingPipeline.java:121)
        at org.terasology.world.chunks.pipeline.ChunkProcessingPipeline.chunkTaskHandler(ChunkProcessingPipeline.java:108)
        at java.lang.Thread.run(Thread.java:745)
11:21:36.462 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Creating game snapshot
11:21:36.474 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
```

**Comment by skaldarnar** [comment]
If this is the same thing I noticed before than this can be "fixed" in game by lowering the view distance (temporarily). This re-triggers chunk gen, and as it takes the player's position into account no terrain will pop up in front and around you.
This did not always work, though, but might give more clues about what is going on...
