### ISSUE TITLE
groovyw update fails with "unknown protocol: git"

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4503]
When I `groovyw module update-all` with repositories I have non-http remotes for, it crashes:

```
Caught: java.net.MalformedURLException: unknown protocol: git
java.net.MalformedURLException: unknown protocol: git
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at common.isUrlValid(common.groovy:88)
	at common$isUrlValid$2.callCurrent(Unknown Source)
	at common.updateItem(common.groovy:224)
	at common$updateItem$1.call(Unknown Source)
	at util.run(util.groovy:122)
```

Taking the `isUrlValid` call out of line 224 may be sufficient to avoid this, but maybe disabling that check lets other problems back in.

**Comment by pollend** [comment]
I've been using to update my list of repos:

https://gist.github.com/pollend/61b2db2c87ac22b3e58a80ef0539ca19
https://gist.github.com/pollend/4591bc691e75d674e0356630df53e4cc

maybe there is some space to be able to share workspace changes between developers.

**Comment by Cervator** [comment]
> Taking the isUrlValid call out

This might not be such a bad idea. It is a little helper for better logging / errors, but I took it out of the reworked GooeyCLI anyway since that also attempts to support private repos which wouldn't react well to a public repo check anyway. Probably we can just rely on actual error handling if the lookup fails.

> I've been using to update my list of repos

Trouble with that and using shell scripting in general is that it isn't portable

**Comment by pollend** [comment]
ref: https://github.com/MovingBlocks/Terasology/pull/4805
