### ISSUE TITLE
Crashed Suddenly

### ISSUE THREAD

**Issue by yasharya2901** [MovingBlocks/Terasology#4551]
### What you were trying to do
Just playing, doing nothing special
### What actually happened
Closed Unexpectedly
### How to reproduce
Don't know
### Log details and game version
https://drive.google.com/uc?id=1jRo4Hhq2v8UKLaricX5SUFEqkuSqY8xD&export=download
### Computer details
KDE Neon Latest
i5-2450M
Nvidia GeForce 410M

**Comment by pollend** [comment]
https://gist.github.com/pollend/7a0de37de7bec4c58a13f9b47f4b0e96

**Comment by Cervator** [comment]
Hi @yasharya2901 - this _looks_ like #2940 which has been linked to your issue here. Every once in a rare while we seem to run into an OpenAL crash, which is used for sound in the game. It looks like you were able to run the game for a while, with plenty of auto-saves, so hopefully your world is intact and you were able to go back to it? This may be a rare problem, I hit it maybe once a month or so.

```
10:23:50.726 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
10:24:17.105 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
org.terasology.audio.openAL.OpenALException: OpenAL Error (40963) at Buffer unqueue - Invalid Value
	at org.terasology.audio.openAL.streamingSound.OpenALStreamingSoundSource.update(OpenALStreamingSoundSource.java:80)
	at org.terasology.audio.openAL.BaseSoundPool.lambda$update$1(BaseSoundPool.java:114)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.terasology.audio.openAL.BaseSoundPool.update(BaseSoundPool.java:114)
	at org.terasology.audio.openAL.OpenALManager.update(OpenALManager.java:262)
	at org.terasology.engine.subsystem.lwjgl.LwjglAudio.postUpdate(LwjglAudio.java:62)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:504)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:458)
	at org.terasology.engine.TerasologyEngine.runMain(TerasologyEngine.java:434)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:400)
	at org.terasology.engine.Terasology.main(Terasology.java:174)
10:24:17.106 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
```

**Comment by pollend** [comment]
> Hi @yasharya2901 - this _looks_ like #2940 which has been linked to your issue here. Every once in a rare while we seem to run into an OpenAL crash, which is used for sound in the game. It looks like you were able to run the game for a while, with plenty of auto-saves, so hopefully your world is intact and you were able to go back to it? This may be a rare problem, I hit it maybe once a month or so.
> 
> ```
> 10:23:50.726 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
> 10:24:17.105 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
> org.terasology.audio.openAL.OpenALException: OpenAL Error (40963) at Buffer unqueue - Invalid Value
> 	at org.terasology.audio.openAL.streamingSound.OpenALStreamingSoundSource.update(OpenALStreamingSoundSource.java:80)
> 	at org.terasology.audio.openAL.BaseSoundPool.lambda$update$1(BaseSoundPool.java:114)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
> 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
> 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
> 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> 	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
> 	at org.terasology.audio.openAL.BaseSoundPool.update(BaseSoundPool.java:114)
> 	at org.terasology.audio.openAL.OpenALManager.update(OpenALManager.java:262)
> 	at org.terasology.engine.subsystem.lwjgl.LwjglAudio.postUpdate(LwjglAudio.java:62)
> 	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:504)
> 	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:458)
> 	at org.terasology.engine.TerasologyEngine.runMain(TerasologyEngine.java:434)
> 	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:400)
> 	at org.terasology.engine.Terasology.main(Terasology.java:174)
> 10:24:17.106 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
> ```

we do a lot of per-emptively protection by returning a (0,0,0) if the position goes invalid. we don't do this for all cases but problematically this hides some larger underlying problems where a hard crash would tell you where the problem is but this behavior seems to hide some other underlying problems that we're seeing with stuff like this. this is usually because a Vector that was passed into openAL is nan/infinite.

**Comment by DarkWeird** [comment]
> > Hi @yasharya2901 - this _looks_ like #2940 which has been linked to your issue here. Every once in a rare while we seem to run into an OpenAL crash, which is used for sound in the game. It looks like you were able to run the game for a while, with plenty of auto-saves, so hopefully your world is intact and you were able to go back to it? This may be a rare problem, I hit it maybe once a month or so.
> > ```
> > 10:23:50.726 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
> > 10:24:17.105 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
> > org.terasology.audio.openAL.OpenALException: OpenAL Error (40963) at Buffer unqueue - Invalid Value
> > 	at org.terasology.audio.openAL.streamingSound.OpenALStreamingSoundSource.update(OpenALStreamingSoundSource.java:80)
> > 	at org.terasology.audio.openAL.BaseSoundPool.lambda$update$1(BaseSoundPool.java:114)
> > 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
> > 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
> > 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
> > 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> > 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> > 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
> > 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
> > 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> > 	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
> > 	at org.terasology.audio.openAL.BaseSoundPool.update(BaseSoundPool.java:114)
> > 	at org.terasology.audio.openAL.OpenALManager.update(OpenALManager.java:262)
> > 	at org.terasology.engine.subsystem.lwjgl.LwjglAudio.postUpdate(LwjglAudio.java:62)
> > 	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:504)
> > 	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:458)
> > 	at org.terasology.engine.TerasologyEngine.runMain(TerasologyEngine.java:434)
> > 	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:400)
> > 	at org.terasology.engine.Terasology.main(Terasology.java:174)
> > 10:24:17.106 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
> > ```
> 
> we do a lot of per-emptively protection by returning a (0,0,0) if the position goes invalid. we don't do this for all cases but problematically this hides some larger underlying problems where a hard crash would tell you where the problem is. this crash is usually because a Vector that was passed into openAL is nan/infinite.

This is another problem. not vector is nan/infinity.
Reproduces sometimes when reloads loop music in game menu
