### ISSUE TITLE
engine-test HeadlessEnvironment does not load bullet natives

### ISSUE THREAD

**Issue by keturn** [MovingBlocks/Terasology#4566]
This came up in [tests for the Pathfinding module](http://jenkins.terasology.io/teraorg/job/Terasology/job/Modules/job/P/job/Pathfinding/job/chore%252Fmigrate-junit5/1/testReport/org.terasology.pathfinding/PathfinderTest/test__/).

```
java.lang.NoClassDefFoundError: Could not initialize class com.badlogic.gdx.physics.bullet.collision.CollisionJNI
	at com.badlogic.gdx.physics.bullet.collision.btBoxShape.<init>(btBoxShape.java:103)
	at org.terasology.physics.bullet.shapes.BulletBoxShape.<init>(BulletBoxShape.java:28)
…
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180)
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228)
	at org.terasology.assets.AssetType.lambda$reload$2(AssetType.java:359)
…
	at org.terasology.utilities.Assets.get(Assets.java:80)
	at org.terasology.world.block.internal.BlockBuilder.<init>(BlockBuilder.java:38)
…
	at org.terasology.HeadlessEnvironment.setupBlockManager(HeadlessEnvironment.java:160)
	at org.terasology.Environment.reset(Environment.java:74)
	at org.terasology.Environment.<init>(Environment.java:49)
	at org.terasology.HeadlessEnvironment.<init>(HeadlessEnvironment.java:115)
	at org.terasology.WorldProvidingHeadlessEnvironment.<init>(WorldProvidingHeadlessEnvironment.java:35)
	at org.terasology.pathfinding.PathfinderTest.setup(PathfinderTest.java:102)
```

my hunch is that something in HeadlessEnvironment changed and the PathManager for that environment isn't pointing to a natives directory anymore, or something like that.

PathManager explodes if it can't find natives when it's constructed, but maybe that exception got swallowed somewhere and lost in the sea of log messages? or maybe my hunch about it being PathManager is wrong.

**Comment by keturn** [comment]
well shucks. I failed to reproduce this locally: most of Pathfinder's tests pass when run from gradle, and the bit that doesn't is a totally different error.

that complicates things.

**Comment by pollend** [comment]
> well shucks. I failed to reproduce this locally: most of Pathfinder's tests pass when run from gradle, and the bit that doesn't is a totally different error.
> 
> that complicates things.
 
probably going down a code path where it doesn't call `Bullet.init();`. I've littered in a couple places but that makes it inconsistent and crazy.

**Comment by keturn** [comment]
"inconsistent and crazy" was my DJ name in high school.

Would a failure look like this if it was the other way around? If `Bullet.init()` was called _before_ PathManager sets org.terasology.librarypath?

**Comment by pollend** [comment]
Not sure actually.

**Comment by pollend** [comment]
can we abstract the bullet physics so we don't rely on it @keturn :?

**Comment by keturn** [comment]
idk. even headless environments still need to run physics, don't they?
