### ISSUE TITLE
Can't open the game after we close the game from taskbar when the game is minimized

### ISSUE THREAD

**Issue by mahela97** [MovingBlocks/Terasology#4596]
### What you were trying to do

The game crashed after the splash screen.

### What actually happened

I try to run the game as usual and it gave this exception. The reason for this exception is "windowWidth", "windowHeight" Values in config.cfg(In root directory) is set to 0(zero) after we close the game from the taskbar when the game is minimized.  

java.lang.RuntimeException: Failed to create window
	at org.terasology.engine.core.subsystem.lwjgl.LwjglGraphics.initWindow(LwjglGraphics.java:152)
	at org.terasology.engine.core.subsystem.lwjgl.LwjglGraphics.postInitialise(LwjglGraphics.java:78)
	at org.terasology.engine.core.TerasologyEngine.postInitSubsystems(TerasologyEngine.java:295)
	at org.terasology.engine.core.TerasologyEngine.initialize(TerasologyEngine.java:225)
	at org.terasology.engine.core.TerasologyEngine.initializeRun(TerasologyEngine.java:408)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:399)
	at org.terasology.engine.Terasology.main(Terasology.java:179)
For more details, see the log files in D:\My works\Terasology\logs\2021-03-23_16-09-36 

### How to reproduce

* Step 1
 Open the game as usual. 
* Step 2
 Minimize the game and close the game from the preview in the taskbar. Do not maximize again.
* Step 3
Run the game again and it will crash after the splash screen.

### Computer details

Asus tuf 504, Running on windows 10

**Comment by Cervator** [comment]
Fixed by #4619
