### ISSUE TITLE
groovyw can't download net.java.dev.jna#jna;4.1.0!jna.jar

### ISSUE THREAD

**Issue by Hume2** [MovingBlocks/Terasology#4709]
### What you were trying to do
I tried to setup my environment according to: https://github.com/MovingBlocks/Terasology/wiki/Contributor-Quick-Start#set-up-your-terasology-development-workspace

When I got to the step `./groovyw module init iota`, it threw an error saying that it can't download: net.java.dev.jna#jna;4.1.0!jna.jar

### What actually happened
`groovyw`threw the error saying that it can't download `net.java.dev.jna#jna;4.1.0!jna.jar`. I tried to re-run it several times but it always threw this error.

### How to reproduce

* Step 1: Clone https://github.com/MovingBlocks/Terasology to a local workspace
* Step 2: Change into the new "Terasology" directory
* Step 3: run `./groovyw module init iota`, the error appears

### Log details and game version
version: current top of master branch (4b12fcccf)
mixed stdout and stderr:
```
Downloading https://services.gradle.org/distributions/gradle-6.8.2-all.zip
..............10%..............20%...............30%..............40%..............50%...............60%..............70%..............80%...............90%..............100%
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/ok1asw/.gradle/wrapper/dists/gradle-6.8.2-all/446le5pselpgh0bzinc35sp0d/gradle-6.8.2/lib/groovy-all-1.3-2.5.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing Grapes -- [download failed: net.java.dev.jna#jna;4.1.0!jna.jar, download failed: net.java.dev.jna#jna-platform;4.1.0!jna-platform.jar]

java.lang.RuntimeException: Error grabbing Grapes -- [download failed: net.java.dev.jna#jna;4.1.0!jna.jar, download failed: net.java.dev.jna#jna-platform;4.1.0!jna-platform.jar]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
	at groovy.grape.GrapeIvy.getDependencies(GrapeIvy.groovy:502)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:167)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at groovy.grape.GrapeIvy.resolve(GrapeIvy.groovy:678)
	at groovy.grape.GrapeIvy.resolve(GrapeIvy.groovy:643)
	at groovy.grape.GrapeIvy.grab(GrapeIvy.groovy:276)
	at groovy.grape.Grape.grab(Grape.java:166)
	at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:376)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:358)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:965)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:642)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:618)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:595)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:401)
	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:341)
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:338)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:336)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:320)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:245)
	at groovy.lang.GroovyClassLoader$parseClass.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at util.run(util.groovy:3)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:266)
	at groovy.lang.GroovyShell.run(GroovyShell.java:376)
	at groovy.lang.GroovyShell.run(GroovyShell.java:365)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:592)
	at groovy.ui.GroovyMain.run(GroovyMain.java:336)
	at groovy.ui.GroovyMain.access$1400(GroovyMain.java:69)
	at groovy.ui.GroovyMain$GroovyCommand.process(GroovyMain.java:295)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:134)
	at groovy.ui.GroovyMain.main(GroovyMain.java:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.wrapper.GroovyBootstrapMainStarter.start(GroovyBootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GroovyWrapperMain.main(GroovyWrapperMain.java:60)

1 error
```
### Computer details
OS: Ubuntu 18.04 64-bit
CPU: Intel® Core™ i3-6100U CPU @ 2.30GHz × 4 
GPU: Intel® HD Graphics 520 (SKL GT2)
java --version:
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```
groovy --version:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/usr/share/groovy/lib/groovy-2.4.16.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Groovy Version: 2.4.16 JVM: 11.0.11 Vendor: Ubuntu OS: Linux
```
Why does the --version command throw waringins??? O_O

**Comment by keturn** [comment]
I wish the groovy.grape error messages would give us more to go on here. Was it a server error? What kind of error? Which server(s) did it try?

According to the [Groovy documentation](http://docs.groovy-lang.org/docs/groovy-2.5.12/html/documentation/#Grape-Logging) there are some variables to set for more log detail.

I think that would look like
```sh
JAVA_OPTS='-Dgroovy.grape.report.downloads=true' ./groovyw module init iota
```

**Comment by Hume2** [comment]
This is the output:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/ok1asw/.gradle/wrapper/dists/gradle-6.8.2-all/446le5pselpgh0bzinc35sp0d/gradle-6.8.2/lib/groovy-all-1.3-2.5.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Resolving dependency: org.ajoberstar#grgit;1.9.3 {default=[default]}
Resolving dependency: org.slf4j#slf4j-nop;1.6.1 {default=[default]}
Resolving dependency: org.slf4j#slf4j-api;1.6.1 {default=[default]}
Preparing to download artifact org.ajoberstar#grgit;1.9.3!grgit.jar
Preparing to download artifact org.slf4j#slf4j-nop;1.6.1!slf4j-nop.jar
Preparing to download artifact org.slf4j#slf4j-api;1.6.1!slf4j-api.jar
Preparing to download artifact org.eclipse.jgit#org.eclipse.jgit;4.5.2.201704071617-r!org.eclipse.jgit.jar
Preparing to download artifact org.eclipse.jgit#org.eclipse.jgit.ui;4.5.2.201704071617-r!org.eclipse.jgit.ui.jar
Preparing to download artifact com.jcraft#jsch.agentproxy.jsch;0.0.9!jsch.agentproxy.jsch.jar
Preparing to download artifact com.jcraft#jsch.agentproxy.pageant;0.0.9!jsch.agentproxy.pageant.jar(bundle)
Preparing to download artifact com.jcraft#jsch.agentproxy.sshagent;0.0.9!jsch.agentproxy.sshagent.jar(bundle)
Preparing to download artifact com.jcraft#jsch.agentproxy.usocket-jna;0.0.9!jsch.agentproxy.usocket-jna.jar(bundle)
Preparing to download artifact com.jcraft#jsch.agentproxy.usocket-nc;0.0.9!jsch.agentproxy.usocket-nc.jar(bundle)
Preparing to download artifact com.jcraft#jsch;0.1.54!jsch.jar
Preparing to download artifact com.googlecode.javaewah#JavaEWAH;0.7.9!JavaEWAH.jar(bundle)
Preparing to download artifact org.apache.httpcomponents#httpclient;4.3.6!httpclient.jar
Preparing to download artifact org.apache.httpcomponents#httpcore;4.3.3!httpcore.jar
Preparing to download artifact commons-logging#commons-logging;1.1.3!commons-logging.jar
Preparing to download artifact commons-codec#commons-codec;1.6!commons-codec.jar
Preparing to download artifact com.jcraft#jsch.agentproxy.core;0.0.9!jsch.agentproxy.core.jar(bundle)
Preparing to download artifact net.java.dev.jna#jna;4.1.0!jna.jar
Preparing to download artifact net.java.dev.jna#jna-platform;4.1.0!jna-platform.jar
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing Grapes -- [download failed: net.java.dev.jna#jna;4.1.0!jna.jar, download failed: net.java.dev.jna#jna-platform;4.1.0!jna-platform.jar]

java.lang.RuntimeException: Error grabbing Grapes -- [download failed: net.java.dev.jna#jna;4.1.0!jna.jar, download failed: net.java.dev.jna#jna-platform;4.1.0!jna-platform.jar]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
	at groovy.grape.GrapeIvy.getDependencies(GrapeIvy.groovy:502)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:167)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
	at groovy.grape.GrapeIvy.resolve(GrapeIvy.groovy:678)
	at groovy.grape.GrapeIvy.resolve(GrapeIvy.groovy:643)
	at groovy.grape.GrapeIvy.grab(GrapeIvy.groovy:276)
	at groovy.grape.Grape.grab(Grape.java:166)
	at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:376)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:358)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:965)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:642)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:618)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:595)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:401)
	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:341)
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:338)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:336)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:320)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:245)
	at groovy.lang.GroovyClassLoader$parseClass.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at util.run(util.groovy:3)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:266)
	at groovy.lang.GroovyShell.run(GroovyShell.java:376)
	at groovy.lang.GroovyShell.run(GroovyShell.java:365)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:592)
	at groovy.ui.GroovyMain.run(GroovyMain.java:336)
	at groovy.ui.GroovyMain.access$1400(GroovyMain.java:69)
	at groovy.ui.GroovyMain$GroovyCommand.process(GroovyMain.java:295)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:134)
	at groovy.ui.GroovyMain.main(GroovyMain.java:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.wrapper.GroovyBootstrapMainStarter.start(GroovyBootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GroovyWrapperMain.main(GroovyWrapperMain.java:60)

1 error
```

**Comment by keturn** [comment]
Well, I guess that's more logging, but not about why or how the jna downloads failed. Try adding `-Divy.message.logger.level=4` as well?

**Comment by Hume2** [comment]
I ran `JAVA_OPTS='-Dgroovy.grape.report.downloads=true -Divy.message.logger.level=4' ./groovyw module init iota 2> ../stderr > ../stdout`

stdout: [https://pastebin.com/uHyCqj1Y](url)

stderr: [https://pastebin.com/NmzQ8Xgm](url)

**Comment by Hume2** [comment]
Removing the directory `~/.groovy/grapes/net.java.dev.jna` seems to fix the issue.

**Comment by jdrueckert** [comment]
Closing this as the issue was resolved.
