### ISSUE TITLE
Fatal "Component not registered" error on creating a second world

### ISSUE THREAD

**Issue by jdrueckert** [MovingBlocks/Terasology#4716]
### What you were trying to do
After having started a first world and having exited it to the main menu, starting a second world.

### What actually happened
Fatal error during "AwaitCharacterSpawn" loading phase:
```
21:12:13.741 [main] ERROR o.t.engine.core.modes.StateLoading - Error while loading org.terasology.engine.core.modes.loadProcesses.AwaitCharacterSpawn@7af22a6
com.google.common.base.VerifyException: Component org.terasology.module.inventory.components.SelectedInventorySlotComponent@4a1978df not registered (in prefab Prefab(engine:player){ components: [org.terasology.engine.logic.characters.CharacterComponent@cd7871e, org.terasology.engine.logic.players.RemotePersonHeldItemMountPointComponent@b14a2c, org.terasology.engine.logic.characters.VisualCharacterComponent@b7da2c4, org.terasology.module.inventory.components.SelectedInventorySlotComponent@4a1978df, org.terasology.engine.physics.components.TriggerComponent@a23ecf4, org.terasology.engine.logic.characters.CharacterSoundComponent@3a7c75d9, org.terasology.module.inventory.components.StartingInventoryComponent@3096a890, org.terasology.engine.logic.characters.GazeMountPointComponent@569b57c4, org.terasology.module.health.components.HealthComponent@43ca45af, org.terasology.engine.logic.players.PlayerCharacterComponent@1a4132b2, org.terasology.engine.logic.characters.CharacterHeldItemComponent@1f96db42, org.terasology.module.health.core.BaseRegenComponent@13bf9a03, org.terasology.engine.logic.characters.AliveCharacterComponent@2c952e6, org.terasology.engine.logic.characters.CharacterMovementComponent@118e24af, org.terasology.module.inventory.components.InventoryComponent@38ebb117, org.terasology.engine.logic.location.LocationComponent@8ada8e22, org.terasology.engine.network.NetworkComponent@57eb4b8b], parent: null })
        at com.google.common.base.Verify.verify(Verify.java:124)
        at com.google.common.base.Verify.verifyNotNull(Verify.java:500)
        at org.terasology.engine.entitySystem.entity.EntityBuilder.addPrefab(EntityBuilder.java:82)
        at org.terasology.engine.entitySystem.entity.EntityBuilder.addPrefab(EntityBuilder.java:66)
        at org.terasology.engine.entitySystem.entity.internal.PojoEntityPool.newBuilder(PojoEntityPool.java:221)
        at org.terasology.engine.entitySystem.entity.internal.PojoEntityManager.newBuilder(PojoEntityManager.java:128)
        at org.terasology.engine.logic.players.PlayerFactory.newInstance(PlayerFactory.java:51)
        at org.terasology.engine.logic.players.PlayerSystem.spawnPlayer(PlayerSystem.java:260)
        at org.terasology.engine.logic.players.PlayerSystem.update(PlayerSystem.java:78)
        at org.terasology.engine.core.modes.loadProcesses.AwaitCharacterSpawn.step(AwaitCharacterSpawn.java:37)
        at org.terasology.engine.core.modes.StateLoading.update(StateLoading.java:240)
        at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:503)
        at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:463)
        at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:440)
        at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:406)
        at org.terasology.engine.Terasology.main(Terasology.java:179)
```

### How to reproduce

Unfortunately this seems to be a sporadic...
Generally the steps I did were:
1. Singleplayer -> Create -> (Core Gameplay) -> Advanced -> Start Playing
2. Walk around a bit
3. Exit to Main Menu
4. Singleplayer -> Create -> (Core Gameplay) -> Start Playing
5. Observe error

### Log details and game version

Engine commit 8e265d0e08b2c2ee64b391ee7dfbebc1203551c8

### Computer details

Linux, Nvidia graphics

**Comment by pollend** [comment]
resolved in PR: https://github.com/MovingBlocks/Terasology/pull/4829
