### ISSUE TITLE
Game Crashes When I Click Single Player

### ISSUE THREAD

**Issue by runlevel-4** [MovingBlocks/Terasology#4910]
12:48:16.153 [main] ERROR o.t.engine.core.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.engine.rendering.nui.layers.mainMenu.SelectionScreen.updateDescription(SelectionScreen.java:84)
	at org.terasology.engine.rendering.nui.layers.mainMenu.SelectGameScreen.lambda$initialise$0(SelectGameScreen.java:71)
	at org.terasology.nui.widgets.UIList.setSelection(UIList.java:218)
	at org.terasology.nui.widgets.UIList.select(UIList.java:267)
	at org.terasology.engine.rendering.nui.layers.mainMenu.SelectionScreen.refreshGameInfoList(SelectionScreen.java:175)
	at org.terasology.engine.rendering.nui.layers.mainMenu.SelectGameScreen.onOpened(SelectGameScreen.java:138)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.pushScreen(NUIManagerInternal.java:441)
	at org.terasology.engine.rendering.nui.CoreScreenLayer.lambda$triggerForwardAnimation$0(CoreScreenLayer.java:360)
	at org.terasology.engine.rendering.nui.animation.MenuAnimationSystemStub.triggerToNext(MenuAnimationSystemStub.java:32)
	at org.terasology.engine.rendering.nui.animation.DeferredMenuAnimationSystem.triggerToNext(DeferredMenuAnimationSystem.java:38)
	at org.terasology.engine.rendering.nui.CoreScreenLayer.triggerForwardAnimation(CoreScreenLayer.java:361)
	at org.terasology.engine.rendering.nui.layers.mainMenu.MainMenuScreen.lambda$initialise$0(MainMenuScreen.java:49)
	at org.terasology.nui.ActivatableWidget.activateWidget(ActivatableWidget.java:46)
	at org.terasology.nui.widgets.UIButton.activateWidget(UIButton.java:203)
	at org.terasology.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:94)
	at org.terasology.nui.canvas.CanvasImpl.processMouseRelease(CanvasImpl.java:266)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:680)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:379)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:254)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:233)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.network.NetworkEventSystemDecorator.send(NetworkEventSystemDecorator.java:54)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.recording.RecordingEventSystemDecorator.send(RecordingEventSystemDecorator.java:34)
	at org.terasology.engine.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:190)
	at org.terasology.engine.input.InputSystem.send(InputSystem.java:524)
	at org.terasology.engine.input.InputSystem.sendMouseEvent(InputSystem.java:496)
	at org.terasology.engine.input.InputSystem.processMouseButtonInput(InputSystem.java:216)
	at org.terasology.engine.input.InputSystem.processMouseInput(InputSystem.java:195)
	at org.terasology.engine.input.InputSystem.update(InputSystem.java:130)
	at org.terasology.engine.core.modes.StateMainMenu.handleInput(StateMainMenu.java:133)
	at org.terasology.engine.core.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:39)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:510)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:462)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:438)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:404)
	at org.terasology.engine.Terasology.main(Terasology.java:179)

**Comment by jdrueckert** [comment]
Hey there @runlevel-4 
Thanks for reporting this issue!
Can you please give us a bit more information on your system and what exactly happened?
Helpful information would include:
- your OS
- whether you started Terasology from the launcher or from source
  - if from the launcher: which version of Terasology (e.g. release 5.1.1) you started
  - if from source: which modules you have checked out and when you last updated your workspace (engine and modules)
- the exact steps (clicks and selections) that led to the error

**Comment by jdrueckert** [comment]
> Helpful information would include:
    * your OS
    * whether you started Terasology from the launcher or from source
      * if from the launcher: which version of Terasology (e.g. release 5.1.1) you started
      * if from source: which modules you have checked out and when you last updated your workspace (engine and modules)
    * the exact steps (clicks and selections) that led to the error


@runlevel-4 Hi again, are you still around and interested in providing some more information as requested above?

**Comment by jdrueckert** [comment]
Closing this as author didn't respond
