### ISSUE TITLE
Game crashes when opened from TerasologyLauncher and click on "Continue to Universe setup" button

### ISSUE THREAD

**Issue by ujjman** [MovingBlocks/Terasology#4911]
### What you were trying to do
I was trying to play game from TerasologyLauncher and wanted to setup universe for that.
### What actually happened
As soon as I clicked "Continue to Universe setup" button  , the game crashed
### How to reproduce

* Step 1 - Open Game from TerasologyLauncher
* Step 2 - Click on Singleplayer>Create>Advanced>Continue to Universe Setup
* Step 3 - The game crashes

### Log details and game version
17:09:51.782 [main] WARN  o.t.engine.registry.InjectionHelper - CoreCommands wanted BlockManager injected but CoreRegistry has none.
17:09:51.796 [main] WARN  o.t.engine.registry.InjectionHelper - LocalPlayerSystem wanted WorldProvider injected but CoreRegistry has none.
17:09:51.797 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted Physics injected but CoreRegistry has none.
17:09:51.797 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted BlockEntityRegistry injected but CoreRegistry has none.
17:09:51.799 [main] WARN  o.t.engine.registry.InjectionHelper - CameraTargetSystem wanted WorldRenderer injected but CoreRegistry has none.
17:09:52.203 [main] WARN  org.terasology.nui.WidgetUtil - Contents of org.terasology.engine.rendering.nui.layers.mainMenu.MainMenuScreen@7dea9ff9 missing button with id 'storageServiceAction'
17:09:52.206 [main] WARN  o.t.engine.core.internal.TimeBase - Delta too great (8624), capping to 1000
17:09:57.826 [main] ERROR o.t.engine.core.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.IllegalStateException: class org.terasology.engine.rendering.assets.mesh.Mesh is not a supported type of asset
	at org.terasology.gestalt.assets.management.AssetManager.loadAsset(AssetManager.java:259)
	at org.terasology.engine.utilities.Assets.generateAsset(Assets.java:209)
	at org.terasology.engine.rendering.assets.mesh.MeshBuilder.build(MeshBuilder.java:127)
	at org.terasology.engine.rendering.assets.font.FontMeshBuilder$Builder.generateResult(FontMeshBuilder.java:78)
	at org.terasology.engine.rendering.assets.font.FontMeshBuilder$Builder.invoke(FontMeshBuilder.java:72)
	at org.terasology.engine.rendering.assets.font.FontMeshBuilder.createTextMesh(FontMeshBuilder.java:35)
	at org.terasology.engine.rendering.nui.internal.LwjglCanvasRenderer.drawText(LwjglCanvasRenderer.java:364)
	at org.terasology.nui.canvas.CanvasImpl.drawTextRawShadowed(CanvasImpl.java:606)
	at org.terasology.nui.canvas.CanvasImpl.drawText(CanvasImpl.java:468)
	at org.terasology.nui.canvas.CanvasImpl.drawText(CanvasImpl.java:461)
	at org.terasology.nui.widgets.UILabel.onDraw(UILabel.java:95)
	at org.terasology.nui.canvas.CanvasImpl.drawStyledWidget(CanvasImpl.java:442)
	at org.terasology.nui.canvas.CanvasImpl.drawWidget(CanvasImpl.java:428)
	at org.terasology.nui.layouts.relative.RelativeLayout.onDraw(RelativeLayout.java:86)
	at org.terasology.nui.canvas.CanvasImpl.drawStyledWidget(CanvasImpl.java:442)
	at org.terasology.nui.canvas.CanvasImpl.drawWidget(CanvasImpl.java:428)
	at org.terasology.engine.rendering.nui.CoreScreenLayer.onDraw(CoreScreenLayer.java:209)
	at org.terasology.nui.canvas.CanvasImpl.drawStyledWidget(CanvasImpl.java:442)
	at org.terasology.nui.canvas.CanvasImpl.drawWidget(CanvasImpl.java:428)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.render(NUIManagerInternal.java:577)
	at org.terasology.engine.core.modes.StateMainMenu.render(StateMainMenu.java:147)
	at org.terasology.engine.core.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:76)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:510)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:462)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:438)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:404)
	at org.terasology.engine.Terasology.main(Terasology.java:179)
17:09:57.826 [main] INFO  o.t.engine.core.TerasologyEngine - Shutting down Terasology...

### Computer details
Windows 10
Ryzen 9
RTX 3050
![error](https://user-images.githubusercontent.com/49057926/134668666-a1645a6b-cfee-47b0-846d-e77062460fb7.png)

**Comment by jdrueckert** [comment]
Thanks for the report! I can confirm the issue happening on Windows with Terasology 5.1.1.

**Comment by jdrueckert** [comment]
Also confirmed on Linux with Terasology 5.1.1
I also can confirm that the issue has been resolved already with Terasology preview 5.2.0-rc.1.
@ujjman Please note, that to select this preview version, you'll need to enable development releases in the Terasology Launcher settings:
![image](https://user-images.githubusercontent.com/29981695/134763400-262321fa-65d4-43fc-8f82-584caf34ec3e.png)

I'll add a note to the Terasology 5.1.1 release that the issue reported here exists and is known.
