### ISSUE TITLE
Application crash on new game start.

### ISSUE THREAD

**Issue by Smascar** [MovingBlocks/Terasology#4923]
### What you were trying to do
Start a new game.
### What actually happened
1. Crash Reporter shows up.
2. Error pop up : Failed to load game. There was an error during  "Loading Prefabs..."

### How to reproduce

* Step 1: Open Terasology application.
* Step 2: Go to "Single Player > Start Playing"

### Log details and game version
16:14:13.507 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: engine:4.3.0
16:14:13.510 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: BiomesAPI:4.1.1-SNAPSHOT
16:14:13.510 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: CoreAssets:2.3.0-SNAPSHOT
16:14:13.510 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: CoreWorlds:2.0.0-SNAPSHOT
16:14:13.510 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Health:1.2.0-SNAPSHOT
16:14:13.510 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Inventory:1.5.0-SNAPSHOT
16:14:13.510 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Hunger:1.2.0-SNAPSHOT
16:14:13.510 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: FlowingLiquids:1.3.0-SNAPSHOT
16:14:13.510 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Fluid:2.1.0-SNAPSHOT
16:14:13.510 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: ItemRendering:1.2.0-SNAPSHOT
16:14:13.510 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: CustomOreGen:1.0.0-SNAPSHOT
16:14:13.510 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: OreGeneration:2.0.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Workstation:1.2.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: SubstanceMatters:2.1.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: SimpleFarming:2.2.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Thirst:1.1.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: EdibleFlora:1.0.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: AdditionalFruits:1.1.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Pathfinding:1.0.1-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Behaviors:1.1.1-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Caves:1.1.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: MusicDirector:1.1.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: ChrisVolume1OST:1.1.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: ChrisVolume2OST:1.1.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Drops:1.2.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Explosives:1.1.1-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Furnishings:1.1.1-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: CoreAdvancedAssets:1.3.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: CoreRendering:1.1.2-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Durability:1.2.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: EdibleSubstance:1.1.0-SNAPSHOT
16:14:13.511 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Notifications:0.2.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: EventualSkills:1.0.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: MobileBlocks:1.1.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: ModularComputers:1.1.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: FluidComputerIntegration:1.1.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: InGameHelpAPI:1.1.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: InGameHelp:1.1.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: PotentialEnergyDevices:1.2.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: Machines:1.3.1-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: MarkovChains:1.6.1-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: NameGenerator:1.1.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: WorldlyTooltipAPI:1.1.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: WildAnimals:1.1.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: ManualLabor:1.4.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: MultiBlock:1.1.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: StructuralResources:2.3.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: IRLCorp:1.1.3-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: ManualLaborEventualSkills:1.1.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: PlantPack:1.2.2-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: WorkstationInGameHelp:1.1.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: WorldlyTooltip:1.3.0-SNAPSHOT
16:14:13.512 [main] INFO  o.t.e.c.m.loadProcesses.RegisterMods - Activating module: JoshariasSurvival:1.1.0-SNAPSHOT
16:14:20.636 [main] WARN  o.t.engine.core.internal.TimeBase - Delta too great (3199), capping to 1000
16:14:20.982 [main] WARN  o.t.e.p.serializers.PrefabSerializer - Prefab 'EdibleFlora:SeedCraftingRecipes' contains unknown component 'ListRecipes'
16:14:21.260 [main] ERROR o.t.module.sandbox.ModuleClassLoader - Denied access to class (not allowed with this module's permissions): org.terasology.module.sandbox.API
16:14:21.260 [main] ERROR o.t.module.sandbox.ModuleClassLoader - Denied access to class (not allowed with this module's permissions): org.terasology.module.sandbox.API
16:14:21.261 [main] ERROR o.t.module.sandbox.ModuleClassLoader - Denied access to class (not allowed with this module's permissions): org.terasology.module.sandbox.API
16:14:21.261 [main] ERROR o.t.module.sandbox.ModuleClassLoader - Denied access to class (not allowed with this module's permissions): org.terasology.module.sandbox.API
16:14:21.327 [main] WARN  o.t.e.p.serializers.PrefabSerializer - Prefab 'WildAnimals:babyDeer' contains unknown component 'StrayIfIdle'
16:14:21.333 [main] WARN  o.t.e.p.s.ComponentSerializer - Cannot deserialize unknown field 'groundFriction' onto 'engine:CharacterMovement'
16:14:21.334 [main] WARN  o.t.e.p.s.ComponentSerializer - Cannot deserialize unknown field 'distanceBetweenSwimStrokes' onto 'engine:CharacterMovement'
16:14:21.365 [main] WARN  o.t.e.p.serializers.PrefabSerializer - Prefab 'PlantPack:Radish' contains unknown component 'ChangingBlocks'
16:14:21.412 [main] WARN  o.t.e.p.s.ComponentSerializer - Cannot deserialize unknown field 'renderedBlockFamily' onto 'Machines:RotatingAxle'
16:14:21.413 [main] WARN  o.t.e.p.s.ComponentSerializer - Cannot deserialize unknown field 'renderedBlockFamily' onto 'Machines:RotatingAxle'
16:14:21.419 [main] WARN  o.t.e.p.serializers.PrefabSerializer - Prefab 'SimpleFarming:componentIngredientMapping' contains unknown component 'ComponentToIngredient'
16:14:21.424 [main] WARN  o.t.e.p.serializers.PrefabSerializer - Prefab 'PlantPack:MilkPlant' contains unknown component 'ChangingBlocks'
16:14:21.448 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered BlockFamily[freeform,AdditionalFruits:MelonVineStem]
16:14:21.448 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered Block AdditionalFruits:MelonVineStem with id 1
16:14:21.536 [main] WARN  o.t.e.p.s.ComponentSerializer - Cannot deserialize unknown field 'renderWithIcon' onto 'engine:Item'
16:14:21.556 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered BlockFamily[horizontal,CoreAdvancedAssets:door-cyan-top]
16:14:21.556 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered Block CoreAdvancedAssets:door-cyan-top.LEFT with id 2
16:14:21.556 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered Block CoreAdvancedAssets:door-cyan-top.RIGHT with id 3
16:14:21.556 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered Block CoreAdvancedAssets:door-cyan-top.FRONT with id 4
16:14:21.556 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered Block CoreAdvancedAssets:door-cyan-top.BACK with id 5
16:14:21.557 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered BlockFamily[horizontal,CoreAdvancedAssets:door-cyan-bottom]
16:14:21.557 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered Block CoreAdvancedAssets:door-cyan-bottom.LEFT with id 6
16:14:21.557 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered Block CoreAdvancedAssets:door-cyan-bottom.RIGHT with id 7
16:14:21.557 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered Block CoreAdvancedAssets:door-cyan-bottom.FRONT with id 8
16:14:21.558 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered Block CoreAdvancedAssets:door-cyan-bottom.BACK with id 9
16:14:21.568 [main] WARN  o.t.e.p.serializers.PrefabSerializer - Prefab 'PlantPack:Corn' contains unknown component 'ChangingBlocks'
16:14:21.628 [main] ERROR o.t.engine.core.modes.StateLoading - Error while loading org.terasology.engine.core.modes.loadProcesses.LoadPrefabs@4cb25b53
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.concurrent.atomic.AtomicLong java.util.Random.seed accessible: module java.base does not "opens java.util" to unnamed module @3b07a0d6
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:931)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.getPrimitiveNode(BehaviorTreeBuilder.java:200)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:144)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:48)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.getCompositeNode(BehaviorTreeBuilder.java:236)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:146)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:48)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.getCompositeNode(BehaviorTreeBuilder.java:236)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:146)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:48)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:870)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.fromJson(BehaviorTreeBuilder.java:92)
	at org.terasology.engine.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:72)
	at org.terasology.engine.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:57)
	at org.terasology.engine.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:30)
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292)
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180)
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228)
	at org.terasology.assets.AssetType.lambda$reload$2(AssetType.java:359)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.terasology.assets.AssetType.reload(AssetType.java:357)
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:386)
	at org.terasology.assets.AssetType.getAsset(AssetType.java:262)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:223)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder$1.read(BehaviorTreeBuilder.java:131)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder$1.read(BehaviorTreeBuilder.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.getCompositeNode(BehaviorTreeBuilder.java:227)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:146)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:48)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.getCompositeNode(BehaviorTreeBuilder.java:236)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:146)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:48)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.getCompositeNode(BehaviorTreeBuilder.java:233)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:146)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:48)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.getCompositeNode(BehaviorTreeBuilder.java:236)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:146)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.deserialize(BehaviorTreeBuilder.java:48)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:870)
	at org.terasology.engine.logic.behavior.core.BehaviorTreeBuilder.fromJson(BehaviorTreeBuilder.java:92)
	at org.terasology.engine.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:72)
	at org.terasology.engine.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:57)
	at org.terasology.engine.logic.behavior.asset.BehaviorTreeFormat.load(BehaviorTreeFormat.java:30)
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292)
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180)
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228)
	at org.terasology.assets.AssetType.lambda$reload$2(AssetType.java:359)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.terasology.assets.AssetType.reload(AssetType.java:357)
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:386)
	at org.terasology.assets.AssetType.getAsset(AssetType.java:262)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:223)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:203)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:187)
	at org.terasology.engine.utilities.Assets.get(Assets.java:67)
	at org.terasology.engine.persistence.typeHandling.extensionTypes.AssetTypeHandler.getFromString(AssetTypeHandler.java:35)
	at org.terasology.engine.persistence.typeHandling.extensionTypes.AssetTypeHandler.getFromString(AssetTypeHandler.java:15)
	at org.terasology.persistence.typeHandling.StringRepresentationTypeHandler.deserialize(StringRepresentationTypeHandler.java:24)
	at org.terasology.persistence.typeHandling.TypeHandler.deserializeOrNull(TypeHandler.java:55)
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:83)
	at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:140)
	at org.terasology.engine.persistence.serializers.ComponentSerializer.deserializeOnto(ComponentSerializer.java:184)
	at org.terasology.engine.persistence.serializers.ComponentSerializer.deserialize(ComponentSerializer.java:101)
	at org.terasology.engine.persistence.serializers.PrefabSerializer.applyComponentChanges(PrefabSerializer.java:151)
	at org.terasology.engine.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:123)
	at org.terasology.engine.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:103)
	at org.terasology.engine.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:45)
	at org.terasology.engine.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:23)
	at org.terasology.assets.module.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:292)
	at org.terasology.assets.module.UnloadedAssetData.load(UnloadedAssetData.java:180)
	at org.terasology.assets.module.ModuleAssetDataProducer.getAssetData(ModuleAssetDataProducer.java:228)
	at org.terasology.assets.AssetType.lambda$reload$2(AssetType.java:359)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.terasology.assets.AssetType.reload(AssetType.java:357)
	at org.terasology.assets.AssetType.getNormalAsset(AssetType.java:386)
	at org.terasology.assets.AssetType.getAsset(AssetType.java:262)
	at org.terasology.assets.management.AssetManager.getAsset(AssetManager.java:223)
	at org.terasology.engine.core.modes.loadProcesses.LoadPrefabs.step(LoadPrefabs.java:43)
	at org.terasology.engine.core.modes.StateLoading.update(StateLoading.java:240)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:495)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:458)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:434)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:400)
	at org.terasology.engine.Terasology.main(Terasology.java:179)

### Computer details
Operating System: Manjaro Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.13.19-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 12 × Intel® Core™ i7-8750H CPU @ 2.20GHz
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2

**Comment by jdrueckert** [comment]
Hi @Smascar 
thank you for reporting this issue.
Can you please tell me, how you tried to start Terasology (from launcher / from source) and in the "from launcher" case which version of Terasology you used respectively in the "from source" case which commit you're on?
Also it would help to know, whether you selected one of the pre-configured gameplays only or added some modules manually in the advanced game setup (AGS)?

**Comment by jdrueckert** [comment]
Oh I'm actually neither sure how up-to-date that is (we're at alpha 5.2.0-rc.3 at the moment) nor whether that's even published by us 👀 
I would recommend to get the launcher from our website https://terasology.org/download.html and either select the latest alpha release (should be 5.1.1) or try out the latest pre-release (5.2.0-rc.3). Please note that you might need to explicitly enable pre-releases in the launcher if you want to try them out. 

FYI: In our latest playtest last Sunday, we noticed a few bugs that we'll need to fix before releasing 5.2.0. But hopefully, we'll be able to make a new release this month.

**Comment by jdrueckert** [comment]
@Smascar glad to hear 👍 
if you face other issues, feel free to open more issues or come talk to us directly on Discord (https://discord.gg/terasology) 🙃 or both 😁
