### ISSUE TITLE
Game crashes while opening NUI Screen Editor 

### ISSUE THREAD

**Issue by ujjman** [MovingBlocks/Terasology#4925]
### What you were trying to do
I was trying to use the Terasology's Developer tools feature (NUI Screen Editor) 
### What actually happened
NUI Screen Editor worked fine while using for the first time but when I exit the game(exit to main menu) and then try to use it again, the game crashes.
### How to reproduce

Repro steps
* Start game using any module
* Load the NUI Screen Editor using developer tools
* Close the NUI Screen Editor
* Exit to main menu (dont close the game)
* Repeat steps 1 and 2

### Log details and game version
Game version - 5.1.1 and 5.2.0-rc-1

java.lang.IllegalStateException: Cannot reload disposed asset 'temp:4adbd0f6-3aa0-47f0-93f5-049f5c594ec5'
	at org.terasology.gestalt.assets.Asset.reload(Asset.java:108)
	at org.terasology.engine.rendering.nui.internal.LineRenderer.draw(LineRenderer.java:220)
	at org.terasology.engine.rendering.nui.internal.LwjglCanvasRenderer.drawLine(LwjglCanvasRenderer.java:242)
	at org.terasology.nui.canvas.CanvasImpl.drawLine(CanvasImpl.java:725)
	at org.terasology.nui.layouts.miglayout.MigLayout.onDraw(MigLayout.java:136)
	at org.terasology.nui.canvas.CanvasImpl.drawStyledWidget(CanvasImpl.java:442)
	at org.terasology.nui.canvas.CanvasImpl.drawWidget(CanvasImpl.java:428)
	at org.terasology.engine.rendering.nui.CoreScreenLayer.onDraw(CoreScreenLayer.java:209)
	at org.terasology.engine.rendering.nui.editor.layers.AbstractEditorScreen.onDraw(AbstractEditorScreen.java:147)
	at org.terasology.nui.canvas.CanvasImpl.drawStyledWidget(CanvasImpl.java:442)
	at org.terasology.nui.canvas.CanvasImpl.drawWidget(CanvasImpl.java:428)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.render(NUIManagerInternal.java:577)
	at org.terasology.engine.core.modes.StateIngame.renderUserInterface(StateIngame.java:239)
	at org.terasology.engine.core.modes.StateIngame.render(StateIngame.java:223)
	at org.terasology.engine.core.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:76)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:510)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:462)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:438)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:404)
	at org.terasology.engine.Terasology.main(Terasology.java:179)

### Computer details
Windows 10
RTX 3050
Ryzen 9
![e1](https://user-images.githubusercontent.com/49057926/136839308-ae0292ba-1e3c-44c7-b4bb-8efaa209cd87.png)

**Comment by jdrueckert** [comment]
I was able to reproduce this also from current source and currently have two theories on what might be happening:
Theory 1: the NUI Screen Editor creates temporary copies / saves of screen assets. While I can understand it does this when changes were made, this also seems to be the case if no screen was edited (or actively saved). I don't know why we would need this in that case.
Theory 2: the NUI Screen Editor creates references to specific assets that we dispose of when going back to the main menu. No idea why we would need this kind of reference or why it's not cleaned up with everything else.
