### ISSUE TITLE
Unsupported JVM? while init

### ISSUE THREAD

**Issue by Ygarr** [MovingBlocks/Terasology#4953]
```
21:35:20.994 [DISCORD-RPC-THREAD] INFO  o.t.s.discordrpc.DiscordRPCThread - Connecting to Discord RPC...
Exception in thread "DISCORD-RPC-THREAD" java.lang.RuntimeException: org.newsclub.net.unix.AFUNIXSocketException: Cannot find method "setCreated" in java.net.Socket. Unsupported JVM?
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:167)
	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:67)
	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:116)
	at org.terasology.subsystem.discordrpc.DiscordRPCThread.run(DiscordRPCThread.java:170)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: org.newsclub.net.unix.AFUNIXSocketException: Cannot find method "setCreated" in java.net.Socket. Unsupported JVM?
	at org.newsclub.net.unix.NativeUnixSocket.setCreated(Native Method)
	at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:36)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:54)
	at com.jagrosh.discordipc.entities.pipe.UnixPipe.<init>(UnixPipe.java:45)
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:163)
	... 4 more
```
	
	is it noticable error, what version recommended?

**Comment by DarkWeird** [comment]
Hi!
How you runs game?

We works at java 11.

This error happes after java 13.

**Comment by Ygarr** [comment]
I used 16 one... hm, need. to consider to use different versions for different apps. AFAIK MC also "like" java 11

**Comment by DarkWeird** [comment]
TerasologyLauncher providing bundled jdk 11 for running game.
This option don't use system's jdk.

**Comment by jdrueckert** [comment]
Is there an action item here or was it resolved by using the correct java version?

**Comment by Ygarr** [comment]
now using
java -version
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8)
OpenJDK 64-Bit Server VM (build 11.0.13+8, mixed mode)

seems working

**Comment by Cervator** [comment]
Thanks for the update 👍 Closing as resolved :-)
