### ISSUE TITLE
Awaiting character spawn.......

### ISSUE THREAD

**Issue by Obliquedbishop** [MovingBlocks/Terasology#4978]
The game didn't load. There was an error during "Awaiting character spawn.....".
I was trying to start the game by following the contributor's quick start.
I'm working on windows 10.

Here's the log file
[Terasology-Game.log](https://github.com/MovingBlocks/Terasology/files/7794563/Terasology-Game.log)

**Comment by Cervator** [comment]
Huh, that's an interesting one. You are trying from source, using the engine's `develop` branch with `groovyw module init iota` done? Which other steps did you take, like what IDE are you using, which command did you use to run the game (`gradlew game` probably)?

```
02:04:23.933 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered BlockFamily[symmetric,CoreAssets:Cactus]
02:04:23.933 [main] INFO  o.t.e.w.b.internal.BlockManagerImpl - Registered Block CoreAssets:Cactus with id 30
02:04:26.798 [main] ERROR o.t.engine.core.modes.StateLoading - Error while loading org.terasology.engine.core.modes.loadProcesses.AwaitCharacterSpawn@29e94753
com.google.common.base.VerifyException: Component org.terasology.module.inventory.components.StartingInventoryComponent@3287cf03 not registered (in prefab Prefab(engine:player){ components: [org.terasology.engine.logic.players.PlayerCharacterComponent@40f53ea, org.terasology.module.inventory.components.StartingInventoryComponent@3287cf03, org.terasology.module.health.core.BaseRegenComponent@5a1216b0, org.terasology.module.inventory.components.SelectedInventorySlotComponent@5c4404dd, org.terasology.engine.logic.location.LocationComponent@8ada8e22, org.terasology.engine.logic.characters.AliveCharacterComponent@76a2db3f, org.terasology.engine.logic.characters.CharacterComponent@8cc5602, org.terasology.engine.logic.characters.CharacterHeldItemComponent@4221663d, org.terasology.engine.logic.characters.GazeMountPointComponent@3ebfe048, org.terasology.engine.logic.players.RemotePersonHeldItemMountPointComponent@5e24af83, org.terasology.engine.logic.characters.VisualCharacterComponent@34329e03, org.terasology.engine.physics.components.TriggerComponent@7d6b0636, org.terasology.engine.network.NetworkComponent@3c971473, org.terasology.module.health.components.HealthComponent@47b4fcd5, org.terasology.engine.logic.characters.CharacterSoundComponent@67d6b0a6, org.terasology.module.inventory.components.InventoryComponent@42a940dc, org.terasology.engine.logic.characters.CharacterMovementComponent@4619e076], parent: null })
	at com.google.common.base.Verify.verifyNotNull(Verify.java:503)
	at org.terasology.engine.entitySystem.entity.EntityBuilder.addPrefab(EntityBuilder.java:82)
	at org.terasology.engine.entitySystem.entity.EntityBuilder.addPrefab(EntityBuilder.java:66)
	at org.terasology.engine.entitySystem.entity.internal.PojoEntityPool.newBuilder(PojoEntityPool.java:221)
	at org.terasology.engine.entitySystem.entity.internal.PojoEntityManager.newBuilder(PojoEntityManager.java:128)
	at org.terasology.engine.logic.players.PlayerFactory.newInstance(PlayerFactory.java:51)
	at org.terasology.engine.logic.players.PlayerSystem.spawnPlayer(PlayerSystem.java:263)
	at org.terasology.engine.logic.players.PlayerSystem.update(PlayerSystem.java:79)
	at org.terasology.engine.core.modes.loadProcesses.AwaitCharacterSpawn.step(AwaitCharacterSpawn.java:37)
	at org.terasology.engine.core.modes.StateLoading.update(StateLoading.java:257)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:499)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:459)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:435)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:401)
	at org.terasology.engine.Terasology.call(Terasology.java:206)
	at org.terasology.engine.Terasology.call(Terasology.java:69)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at org.terasology.engine.Terasology.main(Terasology.java:138)
```

**Comment by Obliquedbishop** [comment]
Yes, I'm trying from source with `groovyw module init iota`. I'm using intellij 2021.2.1. Apart from this, I didn't run any other command except `gradlew game`.

**Comment by Cervator** [comment]
If you don't mind terribly, could you please try again in a fresh directory without involving IntelliJ at all and see if that works differently? I just did the following in a new dir:

1. `git clone https://github.com/MovingBlocks/Terasology`
2. `cd Terasology`
3. `groovyw module init iota`
4. `gradlew game`
5. Created a new game with core sample gameplay (not going through the extra screens for a custom game)
6. Started OK

If there's something in your flow that differs maybe we have something to fix. If that exact lineup still fails ... I'm not honestly sure what it could be 🤔 Which JDK are you using?

**Comment by Obliquedbishop** [comment]
Yes, it worked without involving Intellij. After this, I loaded the project in Intellij and ran it from there. It worked again without any errors. I don't know what went wrong before.
I'm using Open JDK 11.

**Comment by Cervator** [comment]
I think that sometimes Gradle vs IntelliJ can lead to funny workspace state. If anything "weird" happens then running something like `gradlew clean jar game` or using the Gradle refresh button inside IntelliJ may clear it up :-)

Will close this as resolved then, thanks for submitting, glad we cleared it up! Hop on Discord any time if you like to say hi or jump on any issues you consider interesting 👍
