### ISSUE TITLE
`Out of bounds` error on new world (various gameplays)

### ISSUE THREAD

**Issue by 20kdc** [MovingBlocks/Terasology#5056]
Was prompted to send issue by game.
Version 5.2.0, Josharias Survival
Did not occur again on a second attempt.

Logs:
https://drive.google.com/uc?id=1YR8_6t3m52i92LJRtOJ4ZuE882MQY9Gh&export=download

**Comment by jdrueckert** [comment]
Extract from the full logs:
```
15:59:10.409 [main] ERROR o.t.engine.core.modes.StateLoading - Error while loading org.terasology.engine.core.modes.loadProcesses.SetupLocalPlayer@128f0a3c
java.lang.IllegalArgumentException: Out of bounds: (-33, -33) for region BlockArea[(-30, -30)...(30, 30)]
	at org.terasology.engine.world.generation.facets.base.BaseFacet2D.getWorldIndex(BaseFacet2D.java:41)
	at org.terasology.engine.world.generation.facets.base.BaseFieldFacet2D.getWorld(BaseFieldFacet2D.java:31)
	at org.terasology.core.world.generator.facetProviders.DensityNoiseProvider.process(DensityNoiseProvider.java:59)
	at org.terasology.engine.world.generation.ScalableFacetProvider.process(ScalableFacetProvider.java:10)
	at org.terasology.engine.world.generation.RegionImpl.getFacet(RegionImpl.java:41)
	at org.terasology.engine.logic.spawner.AbstractSpawner.findSpawnPosition(AbstractSpawner.java:46)
	at org.terasology.engine.logic.spawner.FixedSpawner.getSpawnPosition(FixedSpawner.java:36)
	at org.terasology.core.world.generator.worldGenerators.SimplexFacetedWorldGenerator.getSpawnPosition(SimplexFacetedWorldGenerator.java:51)
	at org.terasology.engine.logic.players.PlayerSystem.onConnect(PlayerSystem.java:142)
	at org.terasology.engine.logic.players.PlayerSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:379)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:244)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:235)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.network.NetworkEventSystemDecorator.send(NetworkEventSystemDecorator.java:54)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.recording.RecordingEventSystemDecorator.send(RecordingEventSystemDecorator.java:34)
	at org.terasology.engine.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:190)
	at org.terasology.engine.network.internal.NetworkSystemImpl.connectClient(NetworkSystemImpl.java:863)
	at org.terasology.engine.network.internal.NetworkSystemImpl.joinLocal(NetworkSystemImpl.java:305)
	at org.terasology.engine.core.modes.loadProcesses.SetupLocalPlayer.step(SetupLocalPlayer.java:29)
	at org.terasology.engine.core.modes.StateLoading.update(StateLoading.java:257)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:499)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:459)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:435)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:401)
	at org.terasology.engine.Terasology.call(Terasology.java:206)
	at org.terasology.engine.Terasology.call(Terasology.java:69)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at org.terasology.engine.Terasology.main(Terasology.java:138)
```

**Comment by jdrueckert** [comment]
@20kdc This is a sporadic issue we see from time to time. Usually, retrying to create a world works.
Unfortunately, we were not yet able to identify the root cause of this issue.

**Comment by soloturn** [comment]
duplicate of #5312
