### ISSUE TITLE
Crash The Game

### ISSUE THREAD

**Issue by MoamenA** [MovingBlocks/Terasology#5072]
```
18:56:19.968 [main] ERROR o.t.engine.core.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.ArithmeticException: / by zero
	at org.terasology.nui.widgets.UIIconBar.getPreferredContentSize(UIIconBar.java:110)
	at org.terasology.nui.canvas.CanvasImpl.calculateRestrictedSize(CanvasImpl.java:383)
	at org.terasology.nui.layouts.relative.RelativeLayout.getRegion(RelativeLayout.java:143)
	at org.terasology.nui.layouts.relative.RelativeLayout.onDraw(RelativeLayout.java:85)
	at org.terasology.nui.canvas.CanvasImpl.drawStyledWidget(CanvasImpl.java:442)
	at org.terasology.nui.canvas.CanvasImpl.drawWidget(CanvasImpl.java:428)
	at org.terasology.engine.rendering.nui.layers.hud.CoreHudWidget.onDraw(CoreHudWidget.java:45)
	at org.terasology.nui.canvas.CanvasImpl.drawStyledWidget(CanvasImpl.java:442)
	at org.terasology.nui.canvas.CanvasImpl.drawWidget(CanvasImpl.java:428)
	at org.terasology.engine.rendering.nui.layers.hud.HUDScreenLayer.onDraw(HUDScreenLayer.java:149)
	at org.terasology.nui.canvas.CanvasImpl.drawStyledWidget(CanvasImpl.java:442)
	at org.terasology.nui.canvas.CanvasImpl.drawWidget(CanvasImpl.java:428)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.render(NUIManagerInternal.java:577)
	at org.terasology.engine.core.modes.StateLoading.render(StateLoading.java:302)
	at org.terasology.engine.core.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:76)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:508)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:459)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:435)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:401)
	at org.terasology.engine.Terasology.call(Terasology.java:206)
	at org.terasology.engine.Terasology.call(Terasology.java:69)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at org.terasology.engine.Terasology.main(Terasology.java:138)
```

[Full logs](https://pastebin.com/tJ0zjtKW)

**Comment by jdrueckert** [comment]
@MoamenA Can you please tell us a bit more on how you ran into this issue?
E.g., Which Terasology version? Which gameplay mode / module selection? What did you do/click before the bug occurred?

Might be related to https://github.com/MovingBlocks/Terasology/issues/4834

**Comment by skaldarnar** [comment]
Duplicate of #4575.
