### ISSUE TITLE
Crash when starting the game with Java 19 (versions 18 and above all affected)

### ISSUE THREAD

**Issue by BenjaminAmos** [MovingBlocks/Terasology#5090]
### General Info

Terasology Launcher Version: N/A - Works when run through the Launcher
Terasology Version: 5.3.0
Operating System: All (Tested on Windows)
Onboard / Dedicated Graphics: N/A
Java Version: Java >= 18 (possibly 17 as well)

### What you were trying to do

Attempt to run the game directly using Java 19.

### What actually happened

The game crashed with the error:
```stacktrace
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:425)
        at org.terasology.engine.core.module.ModuleManager.setupSandbox(ModuleManager.java:272)
        at org.terasology.engine.core.module.ModuleManager.<init>(ModuleManager.java:88)
        at org.terasology.engine.core.module.ModuleManager.<init>(ModuleManager.java:98)
        at org.terasology.engine.core.TerasologyEngine.initManagers(TerasologyEngine.java:332)
        at org.terasology.engine.core.TerasologyEngine.initialize(TerasologyEngine.java:226)
        at org.terasology.engine.Terasology.call(Terasology.java:183)
        at org.terasology.engine.Terasology.call(Terasology.java:70)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at org.terasology.engine.Terasology.main(Terasology.java:139)
```

### How to reproduce

Attempt to start Terasology with Java 19 installed.

### Log details

[Terasology-init.log](https://github.com/MovingBlocks/Terasology/files/10737517/Terasology-init.log)

### Workaround

Running the game with `java -Djava.security.manager=allow libs\Terasology.jar` re-enables the security manager, allowing the game to run.

I'll try and send a pull request adding this work-around to the launch scripts soon.

### Additional Information / Context

This was discovered after a user reported the error on Discord: https://discord.com/channels/270264625419911192/713903952764207164/1075131426741174322. I could also reproduce it through my own testing.

Gestalt uses the `SecurityManager` API as one of its defences to sandbox modules. `SecurityManager` was [deprecated for removal in Java 17](https://openjdk.org/jeps/411), It is not currently known when it will be removed completely, however, from Java 18 onwards it is disabled by-default. Gestalt can function without a `SecurityManager` (as it does on Android) but it's less than ideal.

**Comment by DarkWeird** [comment]
What about replace SecurityManager with custom module loading scan?

It should improve performance during runtime (irc.. we had problem during deep classloading via all classloader on omega)

I see it like: when module adding to module manager - module should to scan for class/package usage by whitelist. (E.g.Binary classes scaning via reflections or asm4/javaassist)
