### ISSUE TITLE
Crash on trying to use shaping table

### ISSUE THREAD

**Issue by ghost** [MovingBlocks/Terasology#5143]
### General Info

Terasology Launcher Version: Linux X64 4.8.0
Terasology Version: 5.3.0 stable
Operating System: Garuda linux
Onboard / Dedicated Graphics: AMD Ryzen 3 5300U (no dedicated graphics)
Java Version: Launcher bundled

### What you were trying to do

Using a shaping table in josharias survival.

### What actually happened

Terasology crashed, the bug report window opened but i was unable to use it since my mouse pointer disappeared.

### How to reproduce

1. Select Terasology version 5.3.0
1. Start Terasology
1. Select gameplay josharias survival
1. Start game
1. Get a shaping table
1. Use it
1. See error (NullPointerException)

### Log details

Here is the world's log (i hope it's the right one)
[Terasology-Survivalworld.log](https://github.com/MovingBlocks/Terasology/files/12737780/Terasology-Surv.log)

### Additional Infos / Context

Please note that after restarting and crafting a new shaping table it worked without crashing.

**Comment by ghost** [comment]
Just happened again.
Anybody reproduced it?

**Comment by jdrueckert** [comment]
Hi @Miner34dev,
thanks for reporting this, I can reproduce it based on the steps you shared 👍 
NPE seems to come from our `ManualLabor` module:
```
java.lang.NullPointerException: null
	at org.terasology.manualLabor.processParts.SymmetricBlockOutputProcessPartCommonSystem.validateToStartExecution(SymmetricBlockOutputProcessPartCommonSystem.java:82)
	at org.terasology.manualLabor.processParts.SymmetricBlockOutputProcessPartCommonSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:399)
```

More precisely, from [SymmetricBlockOutputProcessPartCommonSystem#validateToStartExecution](https://github.com/Terasology/ManualLabor/blob/develop/src/main/java/org/terasology/manualLabor/processParts/SymmetricBlockOutputProcessPartCommonSystem.java#L82).
My working theory is that the `slotAmountsComponent` might not be properly initialized or something... wanted to check in an entity dump (in-game console `dumpEntities`), but it seems we have another bug there when on windows (see #5144)...
I'll need to check on my Linux, but won't get to that today, I'll comment once I have any updates.

**Comment by jdrueckert** [comment]
I can now confirm that with a shaping table placed in the world in a dump of all entities of the world, a `InventoryInputProcessPartSlotAmountsComponent` as trying to be fetched in [SymmetricBlockOutputProcessPartCommonSystem.java line 81](https://github.com/Terasology/ManualLabor/blob/develop/src/main/java/org/terasology/manualLabor/processParts/SymmetricBlockOutputProcessPartCommonSystem.java#L81C105-L81C150) is no where to be found which results in `slotAmountsComponent` being `null` which in turns results in the NPE when it's attempted to be accessed.

Having said that, it's unclear to me when this last worked and when it broke. With our current development capacities bound elsewhere, I don't think we'll fix this anytime soon.

**Comment by soloturn** [comment]
## Still valid, and I can now explain why it happens - traced in the current `develop`.

`SymmetricBlockOutputProcessPartCommonSystem.validateToStartExecution` fetches `InventoryInputProcessPartSlotAmountsComponent` and dereferences it on the very next line with no null check - unchanged since the report.

That component is added to the process entity by a *different* system, `InventoryInputProcessPartCommonSystem` (in Workstation), reacting to the *same* `ProcessEntityIsInvalidToStartEvent` on the *same* entity. It's null whenever that other handler didn't find a matching item this pass, or the event was already consumed before it ran - and that's an expected, not exceptional, state: every other reader of this exact component already treats it that way. `SymmetricBlockInputProcessPartCommonSystem.execute()`, `ShapedBlockInputProcessPartCommonSystem.execute()`, and `InventoryInputProcessPartCommonSystem`'s own `execute()` all guard it with the identical comment: `// this will be null if another process part has already consumed the items`. This was the one caller of it in the codebase missing that guard - not a mystery regression, a straightforward oversight relative to its own siblings.

Opened a fix that adds the same guard, falling through to the method's own existing "invalid to start" handling a few lines below rather than crashing before reaching it.

**Comment by soloturn** [comment]
Fix opened: Terasology/ManualLabor#65
