### ISSUE TITLE
BasicCrafting module causes crash during load after start game

### ISSUE THREAD

**Issue by LoudMouthJester** [MovingBlocks/Terasology#5169]
link to pastebin

https://pastebin.com/zwKimUJd

any help much appreciated. game looks cool. can't wait to play

**Comment by BenjaminAmos** [comment]
This appears to be the main issue:
```stacktrace
15:00:34.855 [main] ERROR o.t.engine.core.modes.StateLoading - Error while loading org.terasology.engine.core.modes.loadProcesses.LoadPrefabs@7d7097af
java.lang.IllegalArgumentException: Can not set java.util.SortedMap field org.terasology.crafting.listCrafting.components.ListRecipesComponent.recipes to java.util.LinkedHashMap
    at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
    at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
    at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
    at java.base/java.lang.reflect.Field.set(Field.java:780)
    at org.terasology.reflection.reflect.ReflectionReflectFactory$ReflectionFieldAccessor.setValue(ReflectionReflectFactory.java:127)
    at org.terasology.reflection.metadata.FieldMetadata.setValue(FieldMetadata.java:173)
    at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:84)
    at org.terasology.persistence.typeHandling.Serializer.deserializeOnto(Serializer.java:140)
    at org.terasology.engine.persistence.serializers.ComponentSerializer.deserializeOnto(ComponentSerializer.java:185)
    at org.terasology.engine.persistence.serializers.ComponentSerializer.deserialize(ComponentSerializer.java:101)
    at org.terasology.engine.persistence.serializers.PrefabSerializer.applyComponentChanges(PrefabSerializer.java:152)
    at org.terasology.engine.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:124)
    at org.terasology.engine.persistence.serializers.PrefabSerializer.deserialize(PrefabSerializer.java:104)
    at org.terasology.engine.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:45)
    at org.terasology.engine.entitySystem.prefab.internal.PrefabFormat.load(PrefabFormat.java:23)
    at org.terasology.gestalt.assets.format.producer.UnloadedAssetData$AssetSourceResolver.load(UnloadedAssetData.java:311)
    at org.terasology.gestalt.assets.format.producer.UnloadedAssetData.load(UnloadedAssetData.java:181)
    at org.terasology.gestalt.assets.format.producer.AssetFileDataProducer.getAssetData(AssetFileDataProducer.java:227)
    at org.terasology.gestalt.assets.AssetType.lambda$reload$2(AssetType.java:360)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at org.terasology.gestalt.assets.AssetType.reload(AssetType.java:358)
    at org.terasology.gestalt.assets.AssetType.getNormalAsset(AssetType.java:387)
    at org.terasology.gestalt.assets.AssetType.getAsset(AssetType.java:265)
    at org.terasology.gestalt.assets.management.AssetManager.getAsset(AssetManager.java:225)
    at org.terasology.engine.core.modes.loadProcesses.LoadPrefabs.step(LoadPrefabs.java:30)
    at org.terasology.engine.core.modes.StateLoading.update(StateLoading.java:259)
```
The `ListRecipesComponent` component in the `BasicCrafting` module is failing to deserialise.

https://github.com/Terasology/BasicCrafting/blob/88ff60ec129287c356abca505d7250989cc977b4/src/main/java/org/terasology/crafting/listCrafting/components/ListRecipesComponent.java#L22

```java
public class ListRecipesComponent implements Component<ListRecipesComponent>, RecipeComponent {
    public List<String> categories = Collections.singletonList("InHand");
    public SortedMap<String, ListRecipeContainer> recipes = new TreeMap<>();
```

I'll need to double-check if `SortedMap` is supported.

**Comment by BenjaminAmos** [comment]
Did you manually enable the `BasicCrafting` module yourself? It still needs to be fixed but it shouldn't be enabled by-default. If you disable it then the game should load.

**Comment by LoudMouthJester** [comment]
yes i did. will give it a shot. ty
