### ISSUE TITLE
remove or replace regexfilteraction

### ISSUE THREAD

**Issue by soloturn** [MovingBlocks/Terasology#5187]
regexfilteraction is incomatibel with newer logback versions. when i  remove regexfilteraction the following happens.
```
❯ git grep RegexFilterAction
engine/src/main/resources/org/terasology/engine/logback/filter-reflections.xml:    <!-- Requires org.terasology.logback.RegexFilterAction; see setup.xml -->
engine/src/main/resources/org/terasology/engine/logback/setup.xml:    <newRule pattern="*/appender/denyRegex" actionClass="org.terasology.logback.RegexFilterAction" />
engine/src/main/resources/org/terasology/engine/logback/setup.xml:    <newRule pattern="*/appender/requireRegex" actionClass="org.terasology.logback.RegexFilterAction" />

```

```
10db82ae, [configuration][root][appender-ref]=ch.qos.logback.classic.joran.JoranConfigurator$$Lambda/0x00007f8c900275c8@501edcf1, [*][param]=ch.qos.logback.core.joran.JoranConfiguratorBase$$Lambda/0x00007f8c900241a8@78b729e6}   ) - Could not instantiate class [org.terasology.logback.RegexFilterAction] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.terasology.logback.RegexFilterAction
        at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.terasology.logback.RegexFilterAction
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:44)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:33)
        at      at ch.qos.logback.core.joran.spi.SimpleRuleStore.addRule(SimpleRuleStore.java:82)
        at      at ch.qos.logback.core.joran.action.NewRuleAction.begin(NewRuleAction.java:51)
        at      at ch.qos.logback.core.joran.spi.SaxEventInterpreter.callBeginAction(SaxEventInterpreter.java:240)
        at      at ch.qos.logback.core.joran.spi.SaxEventInterpreter.startElement(SaxEventInterpreter.java:139)
        at      at ch.qos.logback.core.joran.spi.SaxEventInterpreter.startElement(SaxEventInterpreter.java:120)
        at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:52)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.playSaxEvents(GenericXMLConfigurator.java:196)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.buildModelFromSaxEventList(GenericXMLConfigurator.java:190)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:164)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:122)
        at      at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:65)
        at      at ch.qos.logback.classic.util.DefaultJoranConfigurator.configureByResource(DefaultJoranConfigurator.java:68)
        at      at ch.qos.logback.classic.util.DefaultJoranConfigurator.configure(DefaultJoranConfigurator.java:35)
        at      at ch.qos.logback.classic.util.ContextInitializer.invokeConfigure(ContextInitializer.java:122)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:97)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:65)
        at      at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:52)
        at      at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
        at      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:195)
        at      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:182)
        at      at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:490)
        at      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:476)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:425)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:451)
        at      at org.terasology.engine.Terasology.<clinit>(Terasology.java:80)
Caused by: java.lang.ClassNotFoundException: org.terasology.logback.RegexFilterAction
        at      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
        at      ... 27 common frames omitted

```

**Comment by soloturn** [comment]
is done.
