### ISSUE TITLE
Crash  when pressing CTRL

### ISSUE THREAD

**Issue by Khaled-Dridi** [MovingBlocks/Terasology#5224]
### General Info

Terasology Launcher Version: 4.8.0
Terasology Version: 5.3.0
Operating System: 10 x64
Onboard / Dedicated Graphics: Nvidia RTX 2060
Java Version: 17.0.10

### i pressed Lctrl 
i was exploring the map and then i pressed Lctrl 

### the game crashed and i was kicked out  
A clear and concise description of what didn't match your expectations, a.k.a. the crash or malfunction you faced.

### How to reproduce

Select Terasology version '5.3.0'
Start Terasology
make a map
press Lctrl

### Log details

[Terasology-init.log](https://github.com/MovingBlocks/Terasology/files/14587179/Terasology-init.log)
[Terasology-menu.log](https://github.com/MovingBlocks/Terasology/files/14587180/Terasology-menu.log)
[Terasology-Game_1.log](https://github.com/MovingBlocks/Terasology/files/14587181/Terasology-Game_1.log)

### Screenshots

![image](https://github.com/MovingBlocks/Terasology/assets/95275414/8d9faf5c-a3b4-4d00-b99c-55939b2ad6ea)

### Workaround

dont press Lctrl 

### Additional Infos / Context

i did it again and it gave me this 
[Terasology-Game_1.log](https://github.com/MovingBlocks/Terasology/files/14587235/Terasology-Game_1.log)
[Terasology-init.log](https://github.com/MovingBlocks/Terasology/files/14587237/Terasology-init.log)
[Terasology-menu.log](https://github.com/MovingBlocks/Terasology/files/14587239/Terasology-menu.log)
![image](https://github.com/MovingBlocks/Terasology/assets/95275414/19038e7b-44df-4b40-bd79-41ff13089394)
 
i searched in the inputs and i don't have a key bind that has Lctrl in it

**Comment by Cervator** [comment]
Interesting bug report, thank you for the details! It looks like you ran the game with GooeysQuests active, I'm not sure how well maintained that is. Does it also happen in plain Core gameplay? 

CTRL is used for crouching or descending when flying or swimming, both of which are pretty rarely used and possibly buggy. This will need a bit of looking into

**Comment by soloturn** [comment]
on linux, java21, develop version at #1b480337c i configured "show mouse" on LCTRL. but when pressing RCTRL it crashes. the game is saved though, so not super tragic:
```
10:50:20.744 [main] WARN  o.t.engine.core.internal.TimeBase - Delta too great (1495), capping to 1000
10:50:30.960 [main] ERROR o.t.engine.core.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.IllegalArgumentException: moduleName must not be null or empty
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.terasology.gestalt.assets.ResourceUrn.<init>(ResourceUrn.java:185)
	at org.terasology.gestalt.assets.ResourceUrn.<init>(ResourceUrn.java:128)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.bindEvent(NUIManagerInternal.java:767)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:399)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:274)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:253)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.network.NetworkEventSystemDecorator.send(NetworkEventSystemDecorator.java:54)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.recording.RecordingEventSystemDecorator.send(RecordingEventSystemDecorator.java:32)
	at org.terasology.engine.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:188)
	at org.terasology.engine.input.internal.BindableButtonImpl.updateBindState(BindableButtonImpl.java:153)
	at org.terasology.engine.input.InputSystem.updateBindState(InputSystem.java:314)
	at org.terasology.engine.input.InputSystem.processKeyboardInput(InputSystem.java:389)
	at org.terasology.engine.input.InputSystem.update(InputSystem.java:132)
	at org.terasology.engine.core.modes.StateIngame.handleInput(StateIngame.java:209)
	at org.terasology.engine.core.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:39)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:521)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:472)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:448)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:414)
	at org.terasology.engine.Terasology.call(Terasology.java:189)
	at org.terasology.engine.Terasology.call(Terasology.java:69)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at org.terasology.engine.Terasology.main(Terasology.java:138)
10:50:30.966 [main] INFO  o.t.engine.core.TerasologyEngine - Shutting down Terasology...
```

**Comment by Khaled-Dridi** [comment]
> Interesting bug report, thank you for the details! It looks like you ran the game with GooeysQuests active, I'm not sure how well maintained that is. Does it also happen in plain Core gameplay?
> 
> CTRL is used for crouching or descending when flying or swimming, both of which are pretty rarely used and possibly buggy. This will need a bit of looking into

hello Cervator as you can see here i did not bind my CTRL button to any input 
![image](https://github.com/MovingBlocks/Terasology/assets/95275414/cff862da-e8f5-4179-8255-a5fce18bda3f)

**Comment by Khaled-Dridi** [comment]
> Interesting bug report, thank you for the details! It looks like you ran the game with GooeysQuests active, I'm not sure how well maintained that is. Does it also happen in plain Core gameplay?
> 
> CTRL is used for crouching or descending when flying or swimming, both of which are pretty rarely used and possibly buggy. This will need a bit of looking into

hii again i tried to reproduce it in other mods and it crashed again so i don't think that the problem is the mod 

[Terasology-Game.log](https://github.com/MovingBlocks/Terasology/files/14899135/Terasology-Game.log)
[Terasology-init.log](https://github.com/MovingBlocks/Terasology/files/14899136/Terasology
[Terasology-menu.log](https://github.com/MovingBlocks/Terasology/files/14899137/Terasology-menu.log)
this is a video showing the mode and what the game does when i press the CTRL
https://github.com/MovingBlocks/Terasology/assets/95275414/bc2529d1-5613-4f46-9d0d-23c2faed83e3

-init.log)

**Comment by soloturn** [comment]
Still valid, confirmed reproducing on current develop as soloturn noted.

## Root cause

`SortOrderSystem.postBegin()` creates fallback `BindableButtonImpl`s for RIGHT_CTRL, LEFT_CTRL and TAB whenever `BindsManager.getKeyBinds()` has no entry for that physical key yet - the common case, since only LEFT_CTRL has a `@DefaultBinding` (`CrouchButton`). Each fallback built its id via the single-arg constructor:

```java
new SimpleUri("ctrlMod")
```

`SimpleUri(String)` only sets `moduleName`/`objectName` when the string contains a `:` separator; without one it silently returns an invalid URI (both names empty) instead of failing fast. The id sits unused until `NUIManagerInternal.bindEvent()` builds a `ResourceUrn` straight from it:

```java
new ResourceUrn(event.getId().getModuleName(), event.getId().getObjectName())
```

`ResourceUrn`'s constructor does validate, and throws exactly the `moduleName must not be null or empty` seen in the trace here - `bindEvent` → `BindableButtonImpl.updateBindState`, matching the reported stack frames.

## Fix

1. `SortOrderSystem` now builds the ids with the proper `SimpleUri(Name, String)` constructor and `TerasologyConstants.ENGINE_MODULE`, the same convention the engine's own binds use.
2. `NUIManagerInternal.bindEvent()` gained a defensive `isValid()` guard so any other malformed bind id logs instead of crashing the input pipeline.

`:engine:compileJava` and `:engine-tests:compileTestJava` both clean.

Fix opened: #5376
