### ISSUE TITLE
No UI error on headless server on player death

### ISSUE THREAD

**Issue by jdrueckert** [MovingBlocks/Terasology#5251]
### What happened

I died in-game and the server logged an error.

### How to reproduce

1. Run a headless server
1. Join the server
1. Die
1. Check the server logs and see the following error logged:
   ```
   18:28:18.165 [main] ERROR o.t.e.network.internal.NetClient - Error processing event
   java.lang.NullPointerException: Cannot invoke "org.terasology.engine.rendering.nui.NUIManager.getHUD()" because "this.nuiManager" is null
       at org.terasology.module.inventory.systems.CharacterInventorySystem.resetDropMark(CharacterInventorySystem.java:212)
       at org.terasology.module.inventory.systems.CharacterInventorySystem.onPlayerDeath(CharacterInventorySystem.java:241)
   ```

### Proposed Fix

A headless server shouldn't try to run the respective code path in the first place as it is not expected to have a UI.
If the respective code is relevant for players, this should be run client-side.

**Comment by RavalAnkesh** [comment]
to fix that
Re-enable Sonar by adding the SonarQube Gradle plugin and running analysis in CI with a valid token.

**Comment by soloturn** [comment]
Still valid, and it's a real bug - not in `Terasology/Inventory`, in the engine's `@NetFilterEvent` enforcement itself.

`CharacterInventorySystem.onPlayerDeath()` is already annotated `@NetFilterEvent(netFilter = RegisterMode.CLIENT)`, specifically to skip on headless servers. That should already be exactly the fix this issue's own "Proposed Fix" section asks for - it just doesn't work, because of a bug in the engine.

## Root cause

`RegisterMode.isValidFor(isAuthority, headless)` computes:

```java
(isAuthority ? validWhenAuthority : validWhenRemote) && (!headless || validWhenHeadless)
```

Both `EventSystemImpl` and `EventSystemReplayImpl` call this with the `headless` parameter hardcoded to `false`:

```java
netFilterAnnotation.netFilter().isValidFor(isAuthority, false)
```

so the `!headless || validWhenHeadless` term is always `true`, and `RegisterMode.CLIENT`-filtered handlers (`validWhenHeadless=false`, meant to be excluded on headless) register and run everywhere the authority-side check allows - including headless dedicated servers. `ComponentSystemManager` gets this right for class-level `@RegisterSystem` filtering (sourcing `isHeadless` from `DisplayDevice.isHeadless()`); the per-method `@NetFilterEvent` path just never picked up the same value.

## Fix

Thread the real `DisplayDevice.isHeadless()` value through both event systems. No change needed in `Terasology/Inventory` - its annotation was already correct.

Fix opened: #5382
