### ISSUE TITLE
SocketException on Arch Linux with Java 21

### ISSUE THREAD

**Issue by soloturn** [MovingBlocks/Terasology#5254]
starting latest terasology on arch linux with java-21 results in an exception beeing thrown, but game seems to work:
```
19:26:11.443 [DISCORD-RPC-THREAD] ERROR o.t.s.discordrpc.DiscordRPCThread - Could not create or connect Discord client: 
java.lang.RuntimeException: java.net.SocketException: No such file or directory; errno=2
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:167)
	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:67)
	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:116)
	at org.terasology.subsystem.discordrpc.DiscordRPCThread.run(DiscordRPCThread.java:170)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.net.SocketException: No such file or directory; errno=2
	at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
	at org.newsclub.net.unix.AFUNIXSocketImpl.connect0(AFUNIXSocketImpl.java:317)
	at org.newsclub.net.unix.AFUNIXSocket.connect0(AFUNIXSocket.java:196)
	at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:175)
	at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:170)
	at com.jagrosh.discordipc.entities.pipe.UnixPipe.<init>(UnixPipe.java:46)
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:163)
	... 4 common frames omitted

```

**Comment by jdrueckert** [comment]
Could it be a permission issue regarding socket creation/access?

**Comment by soloturn** [comment]
does it try to connect to discord @jdrueckert  ?
