### ISSUE TITLE
installing terasology into program files results in "permission denied"

### ISSUE THREAD

**Issue by soloturn** [MovingBlocks/Terasology#5281]
```
C:\Program Files\terasology>Terasology.bat
16:15:00.341 [main] INFO  o.terasology.engine.core.PathManager - PathManager: Initial code location is C:\Program Files\terasology\libs\engine-5.4.0-SNAPSHOT.jar
16:15:00.404 [main] INFO  o.terasology.engine.core.PathManager - PathManager: Working directory is C:\Program Files\terasology
java.nio.file.AccessDeniedException: C:\Program Files\terasology\.local
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:527)
        at java.base/java.nio.file.Files.createDirectory(Files.java:699)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        at java.base/java.nio.file.Files.createDirectories(Files.java:793)
        at org.terasology.engine.core.PathManager.updateDirs(PathManager.java:333)
        at org.terasology.engine.core.PathManager.useDefaultHomePath(PathManager.java:203)
        at org.terasology.engine.Terasology.handleLaunchArguments(Terasology.java:283)
        at org.terasology.engine.Terasology.call(Terasology.java:143)
        at org.terasology.engine.Terasology.call(Terasology.java:69)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at org.terasology.engine.Terasology.main(Terasology.java:138)
```

or, started from different directory:
```
C:\Users\st>"\Program Files\terasology\Terasology.bat"
Error: Unable to access jarfile libs\Terasology.jar
```

**Comment by BenjaminAmos** [comment]
I think creating the `.local` folder on Windows is in itself a bug.
