### ISSUE TITLE
Crash on trying to open TerasologyLauncher 4.8.0 3 on Mac OS 15

### ISSUE THREAD

**Issue by carleeto** [MovingBlocks/Terasology#5286]
### General Info

Terasology Launcher Version: TerasologyLauncher-mac-4.8.0 3
Terasology Version: don't know - the launcher crashes
Operating System: Mac OS 15.0.1, Apple M1 Pro
Onboard / Dedicated Graphics: unknown
Java Version: unknown

### What you were trying to do

I was trying to launch the game. I downloaded the launcher from the site and then opened it to try out the game.

### What actually happened

I got a "checking for updates" window, which suddenly disappeared, and then the launcher icon disappeared from the dock, so I assume it crashed. 

### How to reproduce

1. Download Terasology for MacOS from https://terasology.org/downloads/
2. Launch on an M1 Pro with Mac OS 15.0.1 installed (bypass gatekeeper)
3. The launcher icon appears in the dock and a window appears which says it is checking for updates.
4. Both abruptly disappear 

### Log details

There was no crash reporter, so I don't know where to find the logs.

### Workaround

I have not found a workaround.

### Additional Infos / Context

I was trying to run it because schools have heard of this project, and the kids want to try it out.

**Comment by BenjaminAmos** [comment]
Unfortunately, I believe the latest release of the game still has issues running on M1 Mac devices. Some efforts have been made to support macOS (AArch64) but we have a limited capacity to test there due to only a few contributors possessing the required hardware. The launcher might be experiencing similar issues.

It is unlikely to work but does the game run at all under Rosetta?

You might be able to obtain some logging from the launcher if you run it from the terminal. Being able to run the jar file directly with `java -jar Contents/lib/TerasologyLauncher.jar` inside of `TerasologyLauncher.app` may also show some things (I have not tried this on macOS yet though).

**Comment by nanikh91** [comment]
Hello, I am working on a MacBook Air M1 (2020), running macOS Ventura 13.5. Here is what I did to try and reproduce the issue with the TerasologyLauncher (version 4.8.0):

1. Downloaded the launcher from the [Terasology website](https://terasology.org/downloads/).

2. After bypassing Gatekeeper, I attempted to launch the game, but the launcher crashed shortly after displaying the "checking for updates" window (just as described)

3. I also tried running the launcher from the terminal with : `/Applications/TerasologyLauncher.app/Contents/MacOS/TerasologyLauncher` 

4. The launcher started successfully, but I encountered repeated errors while fetching game versions:
`Invalid version (no major version)`
`Missing game asset`

5. I downloaded Terasology 5.3.0 through the launcher, but the game failed to launch properly due to an error related to GLFW : 
`java.lang.IllegalStateException: GLFW may only be used on the main thread `

6. Additionally, I received an error when the launcher tried to connect to Discord's RPC: 
`Could not create or connect Discord client: java.net.SocketException: No such file or directory`

7. I also tested launching the app using Rosetta, but I was unable to force it to run 

I plan to test the launcher on older versions of macOS to see if the issues persist on other versions.

I would like to work on fixing this issue, as I have the required hardware and can test any necessary patches. Could you please assign this issue to me? Let me know if you need additional logs or specific tests, and I’m happy to help with further debugging on this M1 device.

**Comment by soloturn** [comment]
@carleeto @nanikh91 would you mind trying latest release from here:
https://github.com/MovingBlocks/Terasology/releases/tag/v5.4.0-rc.1

**Comment by carleeto** [comment]
@soloturn - I only see a .exe and .bat in the zip. What do I need to do to open this on a Mac M1?

**Comment by Cervator** [comment]
Hey @carleeto - the `Terasology` file in the root of that zip is actually a shell script, I'm not sure why we never added a `.sh` to it 🤔 

You'll have to have a JRE17 or newer (but not _too_ new) available on the command line for it to work (try `java -version` to confirm)

**Comment by carleeto** [comment]
@Cervator - thanks! Just tried it and this is what I got:

```
~/Downloads/TerasologyOmega ❯ ./Terasology                                                                                                                                                                                                  11:30:51
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/terasology/engine/Terasology has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:641)
~/Downloads/TerasologyOmega ❯ java -version                                                                                                                                                                                                 11:30:56
java version "1.8.0_431"
Java(TM) SE Runtime Environment (build 1.8.0_431-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.431-b10, mixed mode)
```

Looks like I have the most recent version of the Java runtime - when I download from java.com, the version is `8u431`..

Is there anything I'm missing?

**Comment by Cervator** [comment]
That sounds like the latest Java 8. For this release you need 17 :-)

**Comment by carleeto** [comment]
Thanks! Got a little further this time - I use openjdk 17. 

Still didn't launch, but here are the logs, in case its helpful
[log.txt](https://github.com/user-attachments/files/18466479/log.txt)

**Comment by nanikh91** [comment]
Hello,

After testing the version 5.4.0-rc.1 of Terasology on a MacBook Air M1 running macOS Ventura (Java 17.0.13 via Homebrew), I encountered the same GLFW error I mentioned in my initial message: "GLFW may only be used on the main thread".

To work around this issue, I launched the game with the following option to force GLFW to run on the main thread:

`java -XstartOnFirstThread -jar libs/Terasology.jar`

Another challenge was related to macOS Gatekeeper, which blocks some unsigned files. After temporarily disabling the checks, I was able to run the binary provided in the archive without restrictions.

With these adjustments, the game is now working correctly on the M1 machine. I’m available if you’d like me to test other fixes or configurations.

Thanks for this promising RC version, and great work to the whole team !

**Comment by carleeto** [comment]
Echoing what @nanikh91 said. Works for me now! Thanks to the whole team for all the hard work!

**Comment by Cervator** [comment]
Awesome! Yeah that argument sounds familiar. I thought we added it _somewhere_ ages ago, but maybe it was only ever for testing.

@nanikh91 would you mind documenting the exact steps you took for Gatekeeper, maybe with a screenshot or two, so we can add it to a readme or common issues doc?

I'm thrilled it works. I'm not really sure if there are any Mac specific issues left then. Which would be good news!

I'll slowly be catching up with issues and things in the near future, I'll try to keep this in mind and look for other related stuff :-)

If nothing else we'll eventually sort something out with the launcher so we can try to test that. Maybe that's where we somehow embedded the Mac flag. Unsure. Been a long while.

Thanks both!

**Comment by nanikh91** [comment]
@Cervator Sure! Here are the steps I took to bypass Gatekeeper :

**1. Disable Gatekeeper temporarily** : Open Terminal and run the following commande : 

`sudo spctl --master-disable`

**2. Allow the app through System Settings** : If Gatekeeper still blocks the app, go to System Settings → Privacy & Security.

You should see a message allowing you to open the app by clicking the Allow Anyway button (You may need to scroll down). This button is available for about an hour after you try to open the app.

**3. Re-enable Gatekeeper** (optional, for security purposes) : After launching the game, you can re-enable Gatekeeper with:

`sudo spctl --master-enable`

Here are some screenshots :

![Image](https://github.com/user-attachments/assets/97d12718-753b-49be-8a7d-be845d6f42d5)

![Image](https://github.com/user-attachments/assets/3e76a043-8416-4765-802a-1ba870fc5f08)

Let me know if you need more details !

**Comment by soloturn** [comment]
recent builds of terasology work on macos with java-17 and newer. newest version tested was java-26. latest build alwasys on:

https://jenkins.terasology.io/job/Terasology/job/Omega/job/develop/lastSuccessfulBuild/artifact/distros/omega/build/distributions/TerasologyOmega.zip
